import {test,expect} from 'bun:test';import {mkdtemp,mkdir,rm,stat,readFile,realpath} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';import MailTools from '../opencode-plugins/legalwork-mail-tools.js';import {provisionMailCapability,capabilityFileName} from './agent-capabilities.js';
test('bundled plugin selects exact trusted instance directory, never returns capabilities or accepts another workspace grant',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-agent-plugin-')),caps=join(root,'private'),one=join(root,'one'),two=join(root,'two');await mkdir(one);await mkdir(two);const first={id:randomUUID(),token:'a'.repeat(64)},second={id:randomUUID(),token:'b'.repeat(64)};await provisionMailCapability(caps,one,first);await provisionMailCapability(caps,two,second);
 const originalFetch=globalThis.fetch,previousRoot=process.env.LEGALWORK_MAIL_CAPABILITY_SECRET_DIR,previousUrl=process.env.LEGALWORK_SERVER_URL;process.env.LEGALWORK_MAIL_CAPABILITY_SECRET_DIR=caps;process.env.LEGALWORK_SERVER_URL='http://127.0.0.1:9999';let calls=0;
 globalThis.fetch=Object.assign(async(_input:Parameters<typeof fetch>[0],init?:Parameters<typeof fetch>[1])=>{calls++;expect(new Headers(init?.headers).get('authorization')).toBe('Bearer '+first.token);return Response.json({value:{id:first.id,accountId:'own'},trust:'untrusted_email_data'});},{preconnect:originalFetch.preconnect});
 try{const plugin=await MailTools({directory:one}),context={sessionID:'task',messageID:'message'};const result=await plugin.tool.mail_scopes.execute({},context);expect(result).toContain(first.id);expect(result).not.toContain(first.token);expect(result).not.toContain(second.id);await expect(plugin.tool.mail_read.execute({grantId:second.id,request:'{}'},context)).rejects.toThrow();expect(calls).toBe(1);
  await mkdir(join(one,'child'));const child=await MailTools({directory:join(one,'child')});expect(await child.tool.mail_scopes.execute({},context)).toBe('[]');expect(calls).toBe(1);
  const mode=(await stat(join(caps,capabilityFileName(await realpath(one))))).mode;if(process.platform!=='win32')expect(mode&0o077).toBe(0);
  expect(await readFile(join(caps,capabilityFileName(await realpath(one))),'utf8')).not.toContain(second.token);
 }finally{globalThis.fetch=originalFetch;if(previousRoot===undefined)delete process.env.LEGALWORK_MAIL_CAPABILITY_SECRET_DIR;else process.env.LEGALWORK_MAIL_CAPABILITY_SECRET_DIR=previousRoot;if(previousUrl===undefined)delete process.env.LEGALWORK_SERVER_URL;else process.env.LEGALWORK_SERVER_URL=previousUrl;await rm(root,{recursive:true,force:true});}
});
test('serialized provisioning prunes revoked history without evicting older active grants or losing concurrent additions',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-agent-provision-')),caps=join(root,'private'),active=new Set<string>(),old={id:randomUUID(),token:'c'.repeat(64)};active.add(old.id);const ids=async()=>[...active];try{await provisionMailCapability(caps,root,old,ids);for(let i=0;i<105;i++){const current={id:randomUUID(),token:'d'.repeat(64)};active.add(current.id);await provisionMailCapability(caps,root,current,ids);active.delete(current.id);await provisionMailCapability(caps,root,null,ids);}const first={id:randomUUID(),token:'e'.repeat(64)},second={id:randomUUID(),token:'f'.repeat(64)};active.add(first.id);active.add(second.id);await Promise.all([provisionMailCapability(caps,root,first,ids),provisionMailCapability(caps,root,second,ids)]);const saved=JSON.parse(await readFile(join(caps,capabilityFileName(await realpath(root))),'utf8'));expect(saved.grants.map((value:{id:string})=>value.id).sort()).toEqual([...active].sort());expect(saved.grants.find((value:{id:string})=>value.id===old.id).token).toBe(old.token);}finally{await rm(root,{recursive:true,force:true});}
});
