import {z} from 'zod';
export const qualificationTransportCodeSchema=z.enum(['invalid_input','invalid_response','response_too_large','raw_too_large','access_token_rejected','reconsent_required','forbidden','rate_limited','quota_exceeded','transient','not_found','request_rejected','timeout','cancelled','consumer_failed']);
export const qualificationReasonSchema=z.enum(['dailyLimitExceeded','quotaExceeded','rateLimitExceeded','userRateLimitExceeded','insufficientPermissions','domainPolicy','authError','backendError']);
const count=z.number().int().nonnegative();
export const qualificationInputSchema=z.discriminatedUnion('action',[
 z.object({action:z.literal('start'),accountId:z.string().min(1).max(4096),mode:z.enum(['full','samples']).default('full'),maxMessages:z.number().int().min(1).max(10000).default(2000),samples:z.number().int().min(1).max(20).default(10)}).strict(),
 z.object({action:z.enum(['read','cancel']),id:z.string().uuid()}).strict(),
]);
export const qualificationReportSchema=z.object({id:z.string().uuid(),provider:z.literal('gmail'),mode:z.enum(['full','samples']),sampleComparison:z.enum(['pending','match','mismatch','inconclusive']),httpStatus:z.number().int().min(100).max(599).nullable(),providerReason:qualificationReasonSchema.nullable(),startedAt:count,finishedAt:count.nullable(),state:z.enum(['running','complete','inconclusive','limited','cancelled','failed']),comparison:z.enum(['pending','match','mismatch','inconclusive']),phase:z.enum(['enumeration','memberships','samples','finished']),
 maxMessages:count,sampleLimit:count,scope:z.literal('all_messages_including_spam_trash'),providerMessages:count,localMessages:count,missingLocal:count,extraLocal:count,duplicateProviderIds:count,providerLabels:count,localLabels:count,missingLabels:count,extraLabels:count,membershipsChecked:count,metadataRetries:count,membershipMismatches:count,
 rawSamples:count,rawMismatches:count,attachmentSamples:count,attachmentMismatches:count,bodySamples:count,bodyMismatches:count,incompleteSamples:count,incompleteReasons:z.object({readerNotComplete:count,storedProjectionNotComplete:count,missingRaw:count,missingBody:count,unavailableParts:count,bodyTooLarge:count,freshUnsupported:count,freshMalformed:count,freshLimit:count,freshOther:count}).strict(),skippedOversizeSamples:count,downloadedSampleBytes:count,providerStable:z.boolean().nullable(),localStable:z.boolean().nullable(),transportCode:qualificationTransportCodeSchema.nullable(),retryAfterMs:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).nullable(),failedPhase:z.enum(['enumeration','memberships','samples']).nullable(),error:z.enum(['unavailable','provider_failed','limit','changed','cancelled']).nullable()}).strict();
export type QualificationInput=z.infer<typeof qualificationInputSchema>;
export type QualificationReport=z.infer<typeof qualificationReportSchema>;
