import {test,expect} from 'bun:test';import {registerMailRoutes} from '../routes/mail.js';import {matchRoute,type Route,type RequestContext} from '../routes/registry.js';import {LocalMailService} from './service.js';
// Scoped route fixture: unrelated RequestContext services are not accessed by these handlers.
function context(request:Request,params:Record<string,string>,host=true):RequestContext{return {request,url:new URL(request.url),params,actor:host?{type:'host'}:undefined} as RequestContext;}
test('retention routes require host, exact confirmation and native-only backup paths; response contains counts only',async()=>{
 const service=new LocalMailService({ownerId:'synthetic',databasePath:'/unused',loadKey:async()=>{throw Error('must not open');},executable:{kind:'node',path:process.execPath},entryPoint:'/unused'}),routes:Route[]=[];let calls=0;
 service.retention=async()=>{calls++;return{removedDays:null};};service.maintain=async()=>{calls++;return{accounts:1,messages:2,references:3,bytes:4,retainedRecords:0,retainedParts:0,incompleteParts:1,schemaVersion:25};};registerMailRoutes(routes,'127.0.0.1',service);
 async function post(path:string,body:unknown,host=true){const route=matchRoute(routes,'POST',path);if(!route)throw Error('missing route');return route.handler(context(new Request('http://127.0.0.1'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),route.params,host));}
 await expect(post('/mail/v1/accounts/a/retention/apply',{token:'a'.repeat(64),confirmation:'yes'})).rejects.toMatchObject({status:400});await expect(post('/mail/v1/accounts/a/retention/settings',{removedDays:30,ownerId:'foreign'})).rejects.toMatchObject({status:400});await expect(post('/mail/v1/accounts/a/retention/settings',{removedDays:30},false)).rejects.toMatchObject({status:401});await expect(post('/mail/v1/security/backup',{passphrase:'synthetic-passphrase',path:'/forbidden'})).rejects.toMatchObject({status:400});expect(calls).toBe(0);
 const value=await(await post('/mail/v1/security/backup',{passphrase:'synthetic-passphrase'})).json();expect(value.report.references).toBe(3);expect(JSON.stringify(value)).not.toContain('synthetic-passphrase');expect(value.report).not.toHaveProperty('path');expect(calls).toBe(1);
});
