import {linkTestModules} from '../../../../scripts/mail/link-test-modules.mjs';
import { createRequire } from 'node:module';
import {setTimeout as delay} from 'node:timers/promises';
import {test,expect} from 'bun:test';
import {execFileSync} from 'node:child_process';
import {mkdtemp,realpath,symlink,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {LocalMailService} from './service.js';
import {registerMailRoutes} from '../routes/mail.js';
import {startServer} from '../server.js';
import type {ServerConfig} from '../types.js';
import type {Route} from '../routes/registry.js';
test('desktop search API persists encrypted queries, matches attachment sections, and reopens through actual worker',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-extraction-e2e-')),serverRoot=join(import.meta.dir,'../..'),key=randomBytes(32),databasePath=join(root,'mail.sqlite');
 const envNames=['LEGALWORK_ENV_STORE','LEGALWORK_TOKEN_STORE','XDG_DATA_HOME'];const originalEnv=new Map(envNames.map(name=>[name,process.env[name]]));for(const name of envNames)process.env[name]=join(root,name);
 let service:LocalMailService|undefined;let server:Awaited<ReturnType<typeof startServer>>|undefined;
 try{
  const nodePath=Bun.which('node');if(!nodePath)throw Error('Node required');
  await writeFile(join(root,'package.json'),'{"type":"module"}');await linkTestModules(await realpath(join(serverRoot,'node_modules')),join(root,'node_modules'));
  execFileSync(nodePath,[createRequire(import.meta.url).resolve('typescript/bin/tsc'),'--outDir',join(root,'build'),'--rootDir','src','--module','NodeNext','--moduleResolution','NodeNext','--target','ES2022','--strict','--skipLibCheck','--types','node,bun-types','src/mail/runtime/worker.ts','src/mail/extraction/process.ts'],{cwd:serverRoot,timeout:30000});
  const module=(path:string)=>JSON.stringify(pathToFileURL(join(root,'build/mail',path+'.js')).href);
  const seed=`import {readFileSync} from 'node:fs';import {openEncryptedMailDatabase} from ${module('storage/database')};import {migrateMailSchema} from ${module('storage/schema')};import {MailRepository} from ${module('storage/repository')};import {MailContentStore} from ${module('storage/content-store')};import {MimeProjectionStore} from ${module('storage/mime-projection-store')};const input=JSON.parse(readFileSync(0,'utf8'));const key=Buffer.from(input.key,'base64');const db=await openEncryptedMailDatabase({path:input.path,key});key.fill(0);migrateMailSchema(db);for(const [owner,id,subject] of [['owner','a','Prüfung AZ-12/34.5'],['foreign-owner','foreign','Foreign secret']]){const repo=new MailRepository(db,owner);repo.createAccount({id,provider:'gmail',displayName:id});repo.ingestMessage(id,{locator:{provider:'gmail',messageId:'one'},rfcMessageId:null,subject,memberships:[]});}const content=new MailContentStore(db,'owner'),locator={provider:'gmail',messageId:'one'},raw=await content.writePart('a',locator,{kind:'raw',maxBytes:3},[Buffer.from('raw')]),bytes=Buffer.from('ATTACHMENT_HTTP_UNIQUE_Kündigung'),attachment=await content.writePart('a',locator,{kind:'attachment',partId:'p',maxBytes:bytes.length},[bytes]),bodyBytes=Buffer.from(JSON.stringify({bodies:[{contentType:'text/plain',text:'mail'}]})),body=await content.writePart('a',locator,{kind:'body',maxBytes:bodyBytes.length},[bodyBytes]);new MimeProjectionStore(db,'owner').complete('a',locator,raw.id,{metadata:{subject:'Mail',from:null,to:null,cc:null,bcc:null,replyTo:null,date:null,messageId:null},bodies:[{partId:'b',contentType:'text/plain'}],body,attachments:[{partId:'p',filename:'brief.txt',contentType:'text/plain',disposition:'attachment',contentId:null,reference:attachment}]});console.log(JSON.stringify({locator,partId:'p',referenceId:attachment.id}));db.close();`;
  const request=JSON.parse(execFileSync(nodePath,['--input-type=module','-e',seed],{input:JSON.stringify({path:databasePath,key:key.toString('base64')}),timeout:10000}).toString());
  service=new LocalMailService({ownerId:'owner',databasePath,entryPoint:join(root,'build/mail/runtime/worker.js'),executable:{kind:'node',path:nodePath},loadKey:async()=>new Uint8Array(key)});
  const config:ServerConfig={host:'127.0.0.1',port:0,token:'collaborator',hostToken:'host-secret',configPath:join(root,'server.json'),approval:{mode:'auto',timeoutMs:1000},corsOrigins:[],workspaces:[],authorizedRoots:[],readOnly:false,startedAt:Date.now(),tokenSource:'cli',hostTokenSource:'cli',logFormat:'pretty',logRequests:false};
  server=await startServer(config,{mail:service});const base=`http://127.0.0.1:${server.port}/mail/v1`;
  const post=(path:string,value:unknown,token='host-secret')=>fetch(base+path,{method:'POST',headers:{'content-type':'application/json','x-legalwork-host-token':token},body:JSON.stringify(value)});
  const path='/accounts/a/attachments/extraction/';
  expect((await post(path+'status',request)).status).toBe(423);await service.unlock();
  expect((await post(path+'status',request,'collaborator')).status).toBe(401);
  expect((await post('/accounts/foreign/attachments/extraction/status',request)).status).toBe(404);
  expect((await post(path+'status',{...request,ownerId:'foreign-owner'})).status).toBe(400);
  const deadline=Date.now()+6000;let state='queued';while(Date.now()<deadline){state=(await (await post(path+'status',request)).json()).state;if(state==='complete')break;await delay(25);}expect(state).toBe('complete');
  const read=await post(path+'read',{...request,limit:12});expect(read.headers.get('cache-control')).toBe('no-store');const first=await read.json();expect(first.status.downloaded).toBe(true);expect(first.status.referenceId).toBe(request.referenceId);expect(first.text).toBe('ATTACHMENT_H');
  const second=await(await post(path+'read',{...request,offset:first.nextOffset})).json();expect(first.offset).toBe(0);expect(second.offset).toBe(first.nextOffset);expect(first.text+second.text).toBe('ATTACHMENT_HTTP_UNIQUE_Kündigung');
  let found;while(Date.now()<deadline){found=await(await post('/search',{literal:'ATTACHMENT_HTTP_UNIQUE_Kündigung'})).json();if(found.total===1)break;await delay(25);}expect(found.total).toBe(1);expect(found.items[0].snippet).toContain('attachment_http_unique_kündigung');expect(found.items[0].attachmentSources).toEqual([{partId:'p',referenceId:request.referenceId}]);expect(found.items[0].attachmentMatches).toEqual([{partId:'p',referenceId:request.referenceId,section:0,offset:0,source:'text'}]);
  const savedId=crypto.randomUUID(),save={action:'save',id:savedId,expectedRevision:null,name:'Encrypted search',query:{literal:'ATTACHMENT_HTTP_UNIQUE_Kündigung',accountIds:['a']}};
  expect((await post('/search/saved',save,'collaborator')).status).toBe(401);expect((await post('/search/saved',{...save,ownerId:'foreign'})).status).toBe(400);
  const savedResponse=await post('/search/saved',save);expect(savedResponse.headers.get('cache-control')).toBe('no-store');const saved=await savedResponse.json();expect(saved.item.revision).toBe(1);
  expect((await post('/search/saved',save)).status).toBe(409);
  expect((await post('/search/saved',{...save,id:crypto.randomUUID(),query:{accountIds:['foreign']}})).status).toBe(404);

  expect((await post(path+'read',{...request,referenceId:'wrong'})).status).toBe(404);
  const reset=await(await post(path+'reset',request)).json();expect(reset.state).toBe('queued');expect(reset.attempts).toBe(0);
  await service.lock();expect((await post(path+'read',request)).status).toBe(423);await service.unlock();expect((await post(path+'status',request)).status).toBe(200);expect((await(await post('/search/saved',{action:'list'})).json()).items).toEqual([saved.item]);expect((await post('/search/saved',{action:'delete',id:savedId,expectedRevision:1})).status).toBe(200);
  const routes:Route[]=[];registerMailRoutes(routes,'0.0.0.0',service);expect(routes).toHaveLength(0);
 }finally{await server?.stop();await service?.stop();key.fill(0);for(const name of envNames){const old=originalEnv.get(name);if(old===undefined)delete process.env[name];else process.env[name]=old;}await rm(root,{recursive:true,force:true});}
},60000);
