import {MailContentStore} from './content-store.js';
import {MimeProjectionStore} from './mime-projection-store.js';
import {mailHtmlText} from './search.js';
import {MailFilingStore} from './filing-store.js';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {agentControlSchema,agentGrantSchema,agentProposalSchema,agentPermissionSchema,type AgentControl,type AgentControlResult,type AgentGrant} from '../agent-view.js';
import type {MailDatabase,MailSqlRow} from './database-interface.js';
import {MailCredentialRepository} from './credentials.js';
import {providerMessageLocatorSchema} from '../model.js';
export const agentHash=(value:string)=>createHash('sha256').update(value).digest('hex');
export class MailAgentDenied extends Error {constructor(){super('mail_agent_denied');}}
export class MailAgentGrants {
 constructor(private readonly db:MailDatabase,private readonly ownerId:string,private readonly now=Date.now){}
 private view(row:MailSqlRow):AgentGrant{return agentGrantSchema.parse({id:row.id,accountId:row.account_id,workspaceId:row.workspace_id,directory:row.directory,matterId:row.matter_id,permissions:JSON.parse(z.string().parse(row.permissions_json)),credentialGeneration:row.credential_generation,state:row.state,createdAt:row.created_at,expiresAt:row.expires_at,revision:row.revision});}
 private custody(accountId:string){const account=this.db.get('SELECT provider FROM mail_accounts WHERE id=? AND owner_id=?',[accountId,this.ownerId]);if(!account)throw new MailAgentDenied();if(account.provider==='archive')return{generation:'archive:'+accountId,archive:true};const status=new MailCredentialRepository(this.db,this.ownerId).status(accountId);if(status.state!=='connected'||status.archiveLocked)throw new MailAgentDenied();return{generation:status.version.generation,archive:false};}
 private owned(id:string){const row=this.db.get('SELECT g.* FROM mail_agent_grants g JOIN mail_accounts a ON a.id=g.account_id WHERE g.id=? AND a.owner_id=?',[id,this.ownerId]);if(!row)throw new MailAgentDenied();return this.view(row);}
 check(id:string,revision?:number,permission?:z.infer<typeof agentPermissionSchema>){const grant=this.owned(id);const status=this.custody(grant.accountId);
  if(grant.state!=='active'||grant.expiresAt<=this.now()||revision!==undefined&&revision!==grant.revision||permission&&!grant.permissions.includes(permission)||status.generation!==grant.credentialGeneration)throw new MailAgentDenied();return grant;
 }
 private proposal(id:string){const row=this.db.get('SELECT p.* FROM mail_agent_proposals p JOIN mail_accounts a ON a.id=p.account_id WHERE p.id=? AND a.owner_id=?',[id,this.ownerId]);if(!row)throw new MailAgentDenied();return agentProposalSchema.parse({id:row.id,accountId:row.account_id,grantId:row.grant_id,grantRevision:row.grant_revision,payload:JSON.parse(z.string().parse(row.payload_json)),sessionId:row.session_id,messageId:row.message_id,createdAt:row.created_at,expiresAt:row.expires_at,state:row.state,actionId:row.action_id});}
 execute(supplied:AgentControl):AgentControlResult{const input=agentControlSchema.parse(supplied);return this.db.transaction(()=>{switch(input.action){
 case 'body':{const grant=this.check(input.grantId,input.revision,'read');if(grant.matterId){if(!input.sourceVersion)throw new MailAgentDenied();new MailFilingStore(this.db,this.ownerId).execute({action:'source-version',accountId:grant.accountId,locator:input.locator,expected:input.sourceVersion});}
  const projection=new MimeProjectionStore(this.db,this.ownerId).read(grant.accountId,input.locator);if(!projection||!('metadata' in projection)||projection.body.bytes>2*1024*1024)return{body:{text:'',offset:input.offset,nextOffset:null,totalCharacters:0,complete:false,notice:'Readable body unavailable or exceeds 2 MiB. Original export requires a separate export permission.'}};
  const bytes=Buffer.concat([...new MailContentStore(this.db,this.ownerId).read(grant.accountId,projection.body.id)]),parsed=z.object({bodies:z.array(z.object({contentType:z.enum(['text/plain','text/html']),text:z.string(),presentation:z.boolean().optional()})).max(1000)}).parse(JSON.parse(bytes.toString('utf8'))),selected=parsed.bodies.filter(part=>part.presentation!==false),text=selected.map(part=>part.contentType==='text/plain'?part.text:mailHtmlText(part.text)).join('\n');
  const end=Math.min(text.length,input.offset+input.limit);return{body:{text:text.slice(input.offset,end),offset:input.offset,nextOffset:end<text.length?end:null,totalCharacters:text.length,complete:end>=text.length,notice:selected.some(part=>part.contentType==='text/html')?'HTML converted to plain text; formatting omitted. MIME alternatives may repeat where grouping is unavailable; all selected sections are retained.':null}};}
 case 'create':{const value=input.input;if(value.permissions.includes('propose_send')&&!value.permissions.includes('draft'))throw new MailAgentDenied();const status=this.custody(value.accountId);if(status.archive&&value.permissions.some(permission=>!['search','read','attachments','export'].includes(permission))||value.expiresAt<=this.now()||value.expiresAt>this.now()+90*86400000)throw new MailAgentDenied();
  if(Number(this.db.get('SELECT count(*) n FROM mail_agent_grants WHERE state=\'active\' AND expires_at>?',[this.now()])?.n)>=100)throw new MailAgentDenied();
  const token=randomBytes(32).toString('hex'),id=randomUUID();this.db.run('INSERT INTO mail_agent_grants VALUES(?,?,?,?,?,?,?,?,?,?,?,1)',[id,value.accountId,agentHash(token),value.workspaceId,input.directory,value.matterId,JSON.stringify([...new Set(value.permissions)]),status.generation,'active',this.now(),value.expiresAt]);return{grant:this.owned(id),token};}
 case 'list':return{grants:this.db.all('SELECT g.* FROM mail_agent_grants g JOIN mail_accounts a ON a.id=g.account_id WHERE a.owner_id=? ORDER BY CASE WHEN state=\'active\' AND expires_at>? THEN 0 ELSE 1 END,created_at DESC LIMIT 100',[this.ownerId,this.now()]).map(row=>this.view(row))};
 case 'revoke':this.owned(input.id);this.db.run("UPDATE mail_agent_grants SET state='revoked',revision=revision+1 WHERE id=?",[input.id]);this.db.run("UPDATE mail_agent_proposals SET state='revoked' WHERE grant_id=? AND state='pending'",[input.id]);return{ok:true};
 case 'resolve':{const row=this.db.get('SELECT id FROM mail_agent_grants WHERE token_hash=?',[agentHash(input.token)]);if(!row)throw new MailAgentDenied();return{grant:this.check(z.string().parse(row.id),undefined,input.permission)};}
 case 'check':return{grant:this.check(input.id,input.revision,input.permission)};
 case 'draft-bind':{const grant=this.check(input.grantId,undefined,'draft');if(grant.matterId&&(!input.source||!input.sourceVersion))throw new MailAgentDenied();this.db.run('INSERT INTO mail_agent_drafts VALUES(?,?,?,?,?)',[grant.accountId,grant.id,input.draftId,input.source?JSON.stringify(input.source):null,input.sourceVersion]);return{ok:true};}
 case 'draft-source':{this.check(input.grantId,undefined,'draft');const row=this.db.get('SELECT source_json,source_version FROM mail_agent_drafts WHERE grant_id=? AND draft_id=?',[input.grantId,input.draftId]);if(!row)throw new MailAgentDenied();return{sourceVersion:row.source_version===null?null:z.string().parse(row.source_version),source:row.source_json===null?null:providerMessageLocatorSchema.parse(JSON.parse(z.string().parse(row.source_json)))};}
 case 'propose':{const grant=this.check(input.grantId,input.revision,input.payload.kind==='send'?'propose_send':'propose_delete'),id=randomUUID();if(grant.matterId){const locator=input.payload.kind==='send'?input.payload.source:input.payload.locator;if(!locator||!input.payload.sourceVersion)throw new MailAgentDenied();new MailFilingStore(this.db,this.ownerId).execute({action:'source-version',accountId:grant.accountId,locator,expected:input.payload.sourceVersion});}if(input.payload.kind==='send'){const bound=this.db.get('SELECT source_json,source_version FROM mail_agent_drafts WHERE grant_id=? AND draft_id=?',[grant.id,input.payload.draftId]);if(!bound||bound.source_json!==(input.payload.source?JSON.stringify(input.payload.source):null)||bound.source_version!==input.payload.sourceVersion)throw new MailAgentDenied();}this.db.run('INSERT INTO mail_agent_proposals VALUES(?,?,?,?,?,?,?,?,?,?,?,NULL)',[id,grant.accountId,grant.id,grant.revision,input.payload.kind,JSON.stringify(input.payload),input.sessionId,input.messageId,this.now(),Math.min(grant.expiresAt,this.now()+15*60000),'pending']);return{proposal:this.proposal(id)};}
 case 'proposals':return{proposals:this.db.all('SELECT p.id FROM mail_agent_proposals p JOIN mail_accounts a ON a.id=p.account_id WHERE a.owner_id=? ORDER BY created_at DESC LIMIT 100',[this.ownerId]).map(row=>this.proposal(z.string().parse(row.id)))};
 case 'proposal':return{proposal:this.proposal(input.id)};
 case 'save-draft':throw new MailAgentDenied();
 case 'approve':throw new MailAgentDenied();
 case 'decide':{const proposal=this.proposal(input.id);if(proposal.state!=='pending')throw new MailAgentDenied();if(input.approve){this.check(proposal.grantId,proposal.grantRevision,proposal.payload.kind==='send'?'propose_send':'propose_delete');if(proposal.expiresAt<=this.now()||!input.actionId)throw new MailAgentDenied();}this.db.run('UPDATE mail_agent_proposals SET state=?,action_id=? WHERE id=?',[input.approve?'approved':'rejected',input.actionId,input.id]);return{proposal:this.proposal(input.id)};}
 }});}
}
