import {isRestoredMailWork} from './recovery-quarantine.js';
import {MailLocalApiStore} from './local-api.js';
import {projectDraftRecipients} from '../mime/compose.js';
import {z} from 'zod';
import type {MailDatabase} from './database-interface.js';
import {MailCredentialRepository} from './credentials.js';
import {mailLocalVersionSchema} from '../local-view.js';
import {draftRemoteRefSchema,draftSyncStatusSchema,draftSyncRequestSchema,type DraftSyncRequest,type DraftRemoteRef} from '../draft-sync-view.js';
export class DraftSyncError extends Error{constructor(readonly code:'not_found'|'locked'|'conflict'|'invalid_input'){super('mail_draft_sync_'+code);}}
const rowSchema=z.object({account_id:z.string(),draft_id:z.string(),enabled:z.number(),state:draftSyncStatusSchema.shape.state,revision:z.number(),operation:draftSyncStatusSchema.shape.operation,generation:z.string().nullable(),local_revision:z.number().nullable(),remote_json:z.string().nullable(),baseline_hash:z.string().nullable(),conflict_hash:z.string().nullable(),conflict_raw:z.instanceof(Uint8Array).nullable(),dispatch_id:z.string().nullable(),dispatch_raw:z.instanceof(Uint8Array).nullable(),dispatch_generation:z.string().nullable(),dispatch_revision:z.number().nullable(),credential_generation:z.string().nullable(),replacement_json:z.string().nullable(),replacement_hash:z.string().nullable(),error:draftSyncStatusSchema.shape.error,updated_at:z.number()});
export type DraftSyncRow=z.infer<typeof rowSchema>;
export class DraftSyncStore{
 constructor(readonly db:MailDatabase,readonly ownerId:string){}
 account(accountId:string){if(!this.db.get('SELECT 1 FROM mail_accounts WHERE id=? AND owner_id=?',[accountId,this.ownerId]))throw new DraftSyncError('not_found');const status=new MailCredentialRepository(this.db,this.ownerId).status(accountId);if(status.state!=='connected'||status.archiveLocked)throw new DraftSyncError('locked');}
 head(accountId:string,draftId:string){const row=this.db.get('SELECT generation,revision,deleted FROM mail_local_drafts WHERE account_id=? AND id=?',[accountId,draftId]);if(!row)throw new DraftSyncError('not_found');return z.object({generation:z.string(),revision:z.number(),deleted:z.number()}).parse(row);}
 row(accountId:string,draftId:string){const value=this.db.get('SELECT * FROM mail_draft_sync WHERE account_id=? AND draft_id=?',[accountId,draftId]);return value?rowSchema.parse(value):null;}
 status(accountId:string,draftId:string){this.account(accountId);const head=this.head(accountId,draftId),row=this.row(accountId,draftId),dirty=!row||row.generation!==head.generation||row.local_revision!==head.revision;return draftSyncStatusSchema.parse({accountId,draftId,state:row?.state??'local',recipientInputLocalOnly:!head.deleted&&projectDraftRecipients(new MailLocalApiStore(this.db,this.ownerId).readDraft(accountId,{draftId}).content).recipientInputLocalOnly,enabled:row?.enabled===1,dirty,revision:row?.revision??0,remote:row?.remote_json?draftRemoteRefSchema.parse(JSON.parse(row.remote_json)):null,remoteHash:row?.conflict_hash??null,error:row?.error??null,operation:row?.operation??'upsert',updatedAt:row?.updated_at??0});}
 request(accountId:string,supplied:DraftSyncRequest){return this.db.transaction(()=>{this.account(accountId);const input=draftSyncRequestSchema.parse(supplied),head=this.head(accountId,input.draftId);if(head.deleted||head.generation!==input.expected.generation||head.revision!==input.expected.revision)throw new DraftSyncError('conflict');let row=this.row(accountId,input.draftId);
  if(!row){this.db.run('INSERT INTO mail_draft_sync(account_id,draft_id) VALUES(?,?)',[accountId,input.draftId]);row=this.row(accountId,input.draftId)!;}
  if(isRestoredMailWork(this.db,accountId,'draft',input.draftId)&&input.action!=='disable')throw new DraftSyncError('locked');
  if(row.state==='syncing')throw new DraftSyncError('conflict');
  if(input.action==='disable'){this.db.run("UPDATE mail_draft_sync SET enabled=0,revision=revision+1,updated_at=? WHERE account_id=? AND draft_id=?",[Date.now(),accountId,input.draftId]);return this.status(accountId,input.draftId);}
  if(input.action==='keep_local'||input.action==='use_remote'){if(row.state!=='conflict'||!input.remoteHash||input.remoteHash!==row.conflict_hash)throw new DraftSyncError('conflict');if(input.action==='use_remote'&&!row.conflict_raw)throw new DraftSyncError('invalid_input');}
  if(row.state==='conflict'&&!['keep_local','use_remote','retry'].includes(input.action))throw new DraftSyncError('conflict');
  // Uncertain dispatches may only be reconciled, never blindly re-created.
  const uncertain=row.state==='uncertain'||(row.state==='error'&&!!row.dispatch_id);const state=uncertain?'uncertain':'queued',operation=input.action==='delete'?'delete':input.action==='use_remote'?'adopt':uncertain?row.operation:'upsert';
  this.db.run('UPDATE mail_draft_sync SET enabled=1,state=?,operation=?,baseline_hash=CASE WHEN ? THEN conflict_hash ELSE baseline_hash END,error=NULL,revision=revision+1,updated_at=? WHERE account_id=? AND draft_id=?',[state,operation,input.action==='keep_local'?1:0,state==='uncertain'?0:Date.now(),accountId,input.draftId]);if(input.action==='use_remote')this.db.run('UPDATE mail_draft_sync SET dispatch_generation=?,dispatch_revision=? WHERE account_id=? AND draft_id=?',[input.expected.generation,input.expected.revision,accountId,input.draftId]);return this.status(accountId,input.draftId);
 });}
 work(){return this.db.all("SELECT s.account_id,s.draft_id FROM mail_draft_sync s JOIN mail_accounts a ON a.id=s.account_id JOIN mail_local_drafts d ON d.account_id=s.account_id AND d.id=s.draft_id WHERE a.owner_id=? AND s.enabled=1 AND (s.state IN ('queued','uncertain') OR (s.state='error' AND ((s.error='retryable' AND s.updated_at<?) OR (s.error='incomplete' AND d.updated_at>s.updated_at))) OR (s.state='synced' AND (s.generation<>d.generation OR s.local_revision<>d.revision OR s.updated_at<?))) ORDER BY s.updated_at LIMIT 100",[this.ownerId,Date.now()-30000,Date.now()-60000]).map(row=>({accountId:z.string().parse(row.account_id),draftId:z.string().parse(row.draft_id)}));}
 replacement(accountId:string,draftId:string,remote:DraftRemoteRef,hash:string){this.db.run('UPDATE mail_draft_sync SET replacement_json=?,replacement_hash=? WHERE account_id=? AND draft_id=?',[JSON.stringify(remote),hash,accountId,draftId]);}
 recover(){this.db.run("UPDATE mail_draft_sync SET state='uncertain',error='dispatch_unknown',revision=revision+1 WHERE state='syncing' AND dispatch_id IS NOT NULL");}
 prepare(accountId:string,draftId:string,input:{id:string;raw:Uint8Array;version:{generation:string;revision:number};credentialGeneration:string}){this.db.run("UPDATE mail_draft_sync SET state='syncing',dispatch_id=?,dispatch_raw=?,dispatch_generation=?,dispatch_revision=?,credential_generation=?,error=NULL,revision=revision+1,updated_at=? WHERE account_id=? AND draft_id=?",[input.id,input.raw,input.version.generation,input.version.revision,input.credentialGeneration,Date.now(),accountId,draftId]);}
 result(accountId:string,draftId:string,remote:DraftRemoteRef|null,hash:string|null,version:{generation:string;revision:number},removed=false){this.db.run("UPDATE mail_draft_sync SET state=?,operation='upsert',remote_json=?,baseline_hash=?,generation=?,local_revision=?,dispatch_id=NULL,dispatch_raw=NULL,dispatch_generation=NULL,dispatch_revision=NULL,replacement_json=NULL,replacement_hash=NULL,conflict_hash=NULL,conflict_raw=NULL,error=NULL,revision=revision+1,updated_at=? WHERE account_id=? AND draft_id=?",[removed?'removed':'synced',remote?JSON.stringify(remote):null,hash,version.generation,version.revision,Date.now(),accountId,draftId]);}
 problem(accountId:string,draftId:string,state:'conflict'|'uncertain'|'error',error:z.infer<typeof draftSyncStatusSchema.shape.error>,raw?:Uint8Array,hash?:string,remote?:DraftRemoteRef){this.db.run('UPDATE mail_draft_sync SET state=?,error=?,conflict_raw=?,conflict_hash=?,remote_json=coalesce(?,remote_json),revision=revision+1,updated_at=? WHERE account_id=? AND draft_id=?',[state,error,raw??null,hash??null,remote?JSON.stringify(remote):null,Date.now(),accountId,draftId]);}
 /** Trusted EIG-146 hook: the action journal, not a renderer claim, proves send success. */
 cleanupAfterSend(accountId:string,actionId:string){return this.db.transaction(()=>{this.account(accountId);if(isRestoredMailWork(this.db,accountId,'submission',actionId))return false;const pin=this.db.get("SELECT p.draft_id,p.generation,p.revision FROM mail_local_action_drafts p JOIN mail_action_jobs a ON a.account_id=p.account_id AND a.id=p.action_id WHERE p.account_id=? AND p.action_id=? AND a.kind='submission' AND a.state='succeeded'",[accountId,actionId]);if(!pin)throw new DraftSyncError('invalid_input');const draftId=z.string().parse(pin.draft_id),version=mailLocalVersionSchema.parse({generation:pin.generation,revision:pin.revision}),row=this.row(accountId,draftId);if(!row||row.generation!==version.generation||row.local_revision!==version.revision)return false;if(row.state==='removed')return true;if(row.state!=='synced')return false;this.db.run("UPDATE mail_draft_sync SET enabled=1,state='queued',operation='cleanup',revision=revision+1,updated_at=? WHERE account_id=? AND draft_id=?",[Date.now(),accountId,draftId]);return true;});}
}
