import {MailContentStore} from "./content-store.js";
import {mailDraftAttachmentSchema,mailDraftAttachmentViewSchema,type MailDraftAttachment} from "../local-view.js";
import {randomUUID} from "node:crypto";
import {z} from "zod";
import type {MailDatabase} from "./database-interface.js";
import {MailActionJournal,MailActionError} from "./action-journal.js";
import {MailCredentialRepository} from "./credentials.js";
import {MailRepository} from "./repository.js";
import {providerMessageKey} from "../model.js";
import {mailDraftSaveSchema,mailDraftReadSchema,mailDraftDeleteSchema,mailLocalPageSchema,mailDraftViewSchema,mailDraftSummarySchema,mailSubmissionSchema,mailMutationSchema,mailActionReadSchema,mailActionCancelSchema,mailLocalActionSchema,mailEventQuerySchema,mailLocalEventSchema,
 type MailDraftSave,type MailDraftRead,type MailDraftDelete,type MailLocalPage,type MailSubmission,type MailMutation,type MailActionCancel,type MailEventQuery} from "../local-view.js";
export class MailLocalError extends Error{constructor(readonly code:'not_found'|'locked'|'conflict'|'invalid_input'|'unavailable'){super(`mail_local_${code}`);}}
const headSchema=z.object({id:z.string().uuid(),generation:z.string().uuid(),revision:z.number().int().min(1).max(Number.MAX_SAFE_INTEGER),updated_at:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),deleted:z.union([z.literal(0),z.literal(1)])});
const string=z.string();
function parse<T>(schema:z.ZodType<T>,input:unknown):T{const result=schema.safeParse(input);if(!result.success)throw new MailLocalError('invalid_input');return result.data;}
/** Local-only durable state; provider execution is deliberately absent from this API. */
export class MailLocalApiStore{
 private readonly journal:MailActionJournal;private readonly credentials:MailCredentialRepository;private readonly repository:MailRepository;
 constructor(private readonly db:MailDatabase,private readonly ownerId:string,private readonly now:()=>number=Date.now){this.journal=new MailActionJournal(db,ownerId,now);this.credentials=new MailCredentialRepository(db,ownerId,now);this.repository=new MailRepository(db,ownerId);}
 private safe<T>(fn:()=>T):T{try{return this.db.transaction(fn);}catch(error){if(error instanceof MailLocalError)throw error;if(error instanceof MailActionError){if(['replay_conflict','stale_version','invalid_state'].includes(error.code))throw new MailLocalError('conflict');if(error.code==='not_found'||error.code==='account_not_found')throw new MailLocalError('not_found');}throw new MailLocalError('unavailable');}}
 private account(accountId:string):void{if(!this.db.get('SELECT id FROM mail_accounts WHERE id=? AND owner_id=?',[accountId,this.ownerId]))throw new MailLocalError('not_found');if(this.credentials.status(accountId).state==='disconnected')throw new MailLocalError('locked');}
 private head(accountId:string,draftId:string){const row=this.db.get('SELECT * FROM mail_local_drafts WHERE account_id=? AND id=?',[accountId,draftId]);if(!row)throw new MailLocalError('not_found');return headSchema.parse(row);}
 private version(head:z.infer<typeof headSchema>){return{generation:head.generation,revision:head.revision};}
 private snapshot(accountId:string,id:string,version:{generation:string;revision:number}){const row=this.db.get('SELECT content_json FROM mail_local_draft_versions WHERE account_id=? AND draft_id=? AND generation=? AND revision=?',[accountId,id,version.generation,version.revision]);if(!row)throw new MailLocalError('not_found');return mailDraftSaveSchema.shape.content.parse(JSON.parse(string.parse(row.content_json)));}
 saveDraft(accountId:string,supplied:MailDraftSave){return this.safe(()=>{
  this.account(accountId);const input=parse(mailDraftSaveSchema,supplied),serialized=JSON.stringify(input.content);const found=this.db.get('SELECT * FROM mail_local_drafts WHERE account_id=? AND id=?',[accountId,input.draftId]);const old=found?headSchema.parse(found):null;
  if(old){
   if(old.deleted)throw new MailLocalError('conflict');
   const same=JSON.stringify(this.snapshot(accountId,input.draftId,this.version(old)))===serialized;
   if((input.expected===null&&old.revision===1&&same)||(input.expected&&old.generation===input.expected.generation&&old.revision===input.expected.revision+1&&same))return this.readDraft(accountId,{draftId:input.draftId});
   if(!input.expected||old.generation!==input.expected.generation||old.revision!==input.expected.revision||old.revision===Number.MAX_SAFE_INTEGER)throw new MailLocalError('conflict');
  }else if(input.expected!==null)throw new MailLocalError('conflict');
  const previous=old?this.snapshot(accountId,input.draftId,this.version(old)):null;
  for(const attachment of input.content.attachments){
   const key=providerMessageKey(attachment.locator);const retained=previous?.attachments.some(part=>part.referenceId===attachment.referenceId&&part.partId===attachment.partId&&providerMessageKey(part.locator)===key);
   if(!retained&&!this.db.get("SELECT 1 FROM mail_content_manifests WHERE account_id=? AND message_key=? AND kind='attachment' AND part_id=? AND ref_id=? AND state='stored'",[accountId,key,attachment.partId,attachment.referenceId]))throw new MailLocalError('not_found');
   if(!this.db.get("SELECT 1 FROM mail_blob_publications p JOIN mail_blob_objects o ON o.account_id=p.account_id AND o.id=p.object_id WHERE p.account_id=? AND p.ref_id=? AND o.state='published'",[accountId,attachment.referenceId]))throw new MailLocalError('not_found');
  }
  const generation=old?.generation??randomUUID(),revision=(old?.revision??0)+1,updatedAt=parse(z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),this.now());
  this.db.run('INSERT INTO mail_local_drafts(account_id,id,generation,revision,updated_at,deleted) VALUES(?,?,?,?,?,0) ON CONFLICT(account_id,id) DO UPDATE SET revision=excluded.revision,updated_at=excluded.updated_at',[accountId,input.draftId,generation,revision,updatedAt]);
  this.db.run('INSERT INTO mail_local_draft_versions(account_id,draft_id,generation,revision,updated_at,content_json) VALUES(?,?,?,?,?,?)',[accountId,input.draftId,generation,revision,updatedAt,serialized]);
  input.content.attachments.forEach((part,index)=>this.db.run('INSERT INTO mail_local_draft_parts(account_id,draft_id,generation,revision,ordinal,ref_id) VALUES(?,?,?,?,?,?)',[accountId,input.draftId,generation,revision,index,part.referenceId]));
  return this.readDraft(accountId,{draftId:input.draftId});
 });}
 readDraft(accountId:string,supplied:MailDraftRead){return this.safe(()=>{this.account(accountId);const input=parse(mailDraftReadSchema,supplied),head=this.head(accountId,input.draftId);if(head.deleted&&!input.version)throw new MailLocalError('not_found');const version=input.version??this.version(head),content=this.snapshot(accountId,input.draftId,version);return mailDraftViewSchema.parse({id:head.id,version,updatedAt:this.db.get("SELECT updated_at FROM mail_local_draft_versions WHERE account_id=? AND draft_id=? AND generation=? AND revision=?",[accountId,head.id,version.generation,version.revision])?.updated_at,deleted:head.deleted===1,subject:content.subject,content});});}
 listDrafts(accountId:string,supplied:MailLocalPage){return this.safe(()=>{this.account(accountId);const page=parse(mailLocalPageSchema,supplied);const rows=this.db.all('SELECT id FROM mail_local_drafts WHERE account_id=? AND deleted=0 AND id>? ORDER BY id LIMIT ?',[accountId,page.after??'',page.limit+1]);const items=rows.slice(0,page.limit).map(row=>{const {content,...summary}=this.readDraft(accountId,{draftId:string.parse(row.id)});return mailDraftSummarySchema.parse(summary);});return{accountId,items,nextCursor:rows.length>page.limit?items.at(-1)?.id??null:null};});}
 deleteDraft(accountId:string,supplied:MailDraftDelete){return this.safe(()=>{this.account(accountId);const input=parse(mailDraftDeleteSchema,supplied),head=this.head(accountId,input.draftId);if(head.generation!==input.expected.generation||head.revision!==input.expected.revision||head.revision===Number.MAX_SAFE_INTEGER)throw new MailLocalError('conflict');const content=this.snapshot(accountId,head.id,this.version(head));const generation=randomUUID(),revision=head.revision+1,updatedAt=parse(z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),this.now());this.db.run('UPDATE mail_local_drafts SET deleted=1,generation=?,revision=?,updated_at=? WHERE account_id=? AND id=?',[generation,revision,updatedAt,accountId,head.id]);return mailDraftSummarySchema.parse({id:head.id,version:{generation,revision},updatedAt,deleted:true,subject:content.subject});});}
 private action(accountId:string,actionId:string){const status=this.journal.read(accountId,actionId),row=this.db.get('SELECT payload_json FROM mail_action_jobs WHERE account_id=? AND id=?',[accountId,actionId]);let generation:unknown;try{const payload:unknown=JSON.parse(string.parse(row?.payload_json));if(payload&&typeof payload==='object'&&'credentialGeneration' in payload)generation=payload.credentialGeneration;}catch{/* Legacy opaque intent is not dispatchable by this API. */}const credentials=this.credentials.status(accountId);return mailLocalActionSchema.parse({...status,executionSupported:status.kind==='mutation'&&this.db.get('SELECT provider FROM mail_accounts WHERE id=?',[accountId])?.provider==='imap',providerResult:this.db.get('SELECT result FROM mail_imap_action_results WHERE account_id=? AND id=?',[accountId,actionId])?.result??null,credentialCurrent:credentials.state==='connected'&&generation===credentials.version.generation});}
 private enqueue(accountId:string,kind:'submission'|'mutation',replayKey:string,intent:object,validate:()=>void,precondition:string|null){
  this.account(accountId);const existing=this.db.get('SELECT id,kind,payload_json FROM mail_action_jobs WHERE account_id=? AND replay_key=?',[accountId,replayKey]);
  if(existing){const payload=z.object({version:z.literal(1),intent:z.unknown(),credentialGeneration:z.string().uuid()}).strict().safeParse(JSON.parse(string.parse(existing.payload_json)));if(existing.kind!==kind||!payload.success||JSON.stringify(payload.data.intent)!==JSON.stringify(intent))throw new MailLocalError('conflict');return this.action(accountId,string.parse(existing.id));}
  const credentials=this.credentials.status(accountId);if(credentials.state!=='connected')throw new MailLocalError('locked');validate();
  const status=this.journal.enqueue(accountId,{kind,replayKey,payloadJson:JSON.stringify({version:1,intent,credentialGeneration:credentials.version.generation}),precondition,conflictPolicy:'manual'});return this.action(accountId,status.id);
 }
 enqueueSubmission(accountId:string,supplied:MailSubmission){return this.safe(()=>{const input=parse(mailSubmissionSchema,supplied),intent={kind:'submission',draftId:input.draftId,version:input.version};const result=this.enqueue(accountId,'submission',input.replayKey,intent,()=>{const head=this.head(accountId,input.draftId);if(head.deleted)throw new MailLocalError('not_found');const content=this.snapshot(accountId,input.draftId,input.version);if(!content.to.length&&!content.cc.length&&!content.bcc.length)throw new MailLocalError('invalid_input');},null);this.db.run('INSERT INTO mail_local_action_drafts(account_id,action_id,draft_id,generation,revision) VALUES(?,?,?,?,?) ON CONFLICT(account_id,action_id) DO NOTHING',[accountId,result.id,input.draftId,input.version.generation,input.version.revision]);return result;});}
 enqueueMutation(accountId:string,supplied:MailMutation){return this.safe(()=>{const input=parse(mailMutationSchema,supplied),intent={kind:'mutation',locator:input.locator,precondition:input.precondition,change:input.change};return this.enqueue(accountId,'mutation',input.replayKey,intent,()=>{if(input.change.kind==='mailbox'){if(this.db.get('SELECT provider FROM mail_accounts WHERE id=?',[accountId])?.provider!=='imap'||input.locator||input.precondition!=='imap-mailbox-v1')throw new MailLocalError('invalid_input');}else if(!input.locator||!this.repository.readMessage(accountId,input.locator))throw new MailLocalError('not_found');if(input.change.kind==='memberships')for(const folder of [...input.change.add,...input.change.remove])if(!this.db.get('SELECT id FROM mail_folders WHERE account_id=? AND id=?',[accountId,folder]))throw new MailLocalError('not_found');},input.precondition);});}
 readAction(accountId:string,actionId:string){return this.safe(()=>{this.account(accountId);parse(mailActionReadSchema,{actionId});return this.action(accountId,actionId);});}
 listActions(accountId:string,supplied:MailLocalPage){return this.safe(()=>{this.account(accountId);const page=parse(mailLocalPageSchema,supplied);const rows=this.db.all('SELECT id FROM mail_action_jobs WHERE account_id=? AND id>? ORDER BY id LIMIT ?',[accountId,page.after??'',page.limit+1]);const items=rows.slice(0,page.limit).map(row=>this.action(accountId,string.parse(row.id)));return{accountId,items,nextCursor:rows.length>page.limit?items.at(-1)?.id??null:null};});}
 cancelAction(accountId:string,supplied:MailActionCancel){return this.safe(()=>{this.account(accountId);const input=parse(mailActionCancelSchema,supplied);this.journal.cancel(accountId,input.actionId,input.expected);return this.action(accountId,input.actionId);});}
 readDraftAttachment(accountId:string,supplied:MailDraftAttachment){return this.safe(()=>{this.account(accountId);const input=parse(mailDraftAttachmentSchema,supplied),content=this.snapshot(accountId,input.draftId,input.version),part=content.attachments[input.ordinal];
  if(!part||part.referenceId!==input.referenceId||!this.db.get('SELECT 1 FROM mail_local_draft_parts WHERE account_id=? AND draft_id=? AND generation=? AND revision=? AND ordinal=? AND ref_id=?',[accountId,input.draftId,input.version.generation,input.version.revision,input.ordinal,input.referenceId]))throw new MailLocalError('not_found');
  return mailDraftAttachmentViewSchema.parse({draftId:input.draftId,version:input.version,ordinal:input.ordinal,chunk:{accountId,locator:part.locator,referenceId:input.referenceId,offset:input.offset,...new MailContentStore(this.db,this.ownerId).readRange(accountId,input.referenceId,input.offset,input.limit)}});
 });}
 events(accountId:string,supplied:MailEventQuery){return this.safe(()=>{this.account(accountId);const page=parse(mailEventQuerySchema,supplied),stream=string.parse(this.db.get('SELECT generation FROM mail_local_event_streams WHERE account_id=?',[accountId])?.generation);if(page.stream!==undefined&&page.stream!==stream)return{accountId,stream,resetRequired:true,items:[],nextCursor:z.number().int().parse(this.db.get('SELECT coalesce(max(sequence),0) AS n FROM mail_local_events WHERE account_id=?',[accountId])?.n),hasMore:false};const rows=this.db.all('SELECT * FROM mail_local_events WHERE account_id=? AND sequence>? ORDER BY sequence LIMIT ?',[accountId,page.after,page.limit+1]);const items=rows.slice(0,page.limit).map(row=>mailLocalEventSchema.parse({sequence:row.sequence,kind:row.kind,entityId:row.entity_id,state:row.state,version:row.generation===null?null:{generation:row.generation,revision:row.revision}}));return{accountId,stream,resetRequired:false,items,nextCursor:items.at(-1)?.sequence??page.after,hasMore:rows.length>page.limit};});}
}
