import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {storageSaveInputSchema,storageSaveSchema,storageSaveFolder,type StorageSaveInput,type StorageSaveResult} from '../storage-save-view.js';
import {MailServiceError} from '../service-interface.js';
import {MailFilingStore} from './filing-store.js';
import {MailCredentialRepository} from './credentials.js';
import type {MailDatabase} from './database-interface.js';
const text=z.string();
export class MailStorageSaveStore {
 constructor(private readonly db:MailDatabase,private readonly ownerId:string){}
 private generation(accountId:string){const row=this.db.get('SELECT provider FROM mail_accounts WHERE id=? AND owner_id=?',[accountId,this.ownerId]);if(!row)throw new MailServiceError('not_found');const access=new MailCredentialRepository(this.db,this.ownerId).status(accountId);if(row.provider!=='archive'&&(access.state!=='connected'||access.archiveLocked))throw new MailServiceError('locked');return access.state==='connected'?access.version.generation:'offline:'+accountId;}
 private read(accountId:string,id:string){const currentGeneration=this.generation(accountId);const row=this.db.get('SELECT j.*,s.account_id FROM mail_storage_saves j JOIN mail_filing_snapshots s ON s.id=j.snapshot_id WHERE j.id=? AND s.account_id=?',[id,accountId]);if(!row)throw new MailServiceError('not_found');return storageSaveSchema.parse({id:row.id,snapshotId:row.snapshot_id,accountId:row.account_id,workspaceId:row.workspace_id,storageId:row.storage_id,rootRevision:row.root_revision,folderPath:row.folder_path,selection:JSON.parse(text.parse(row.selection_json)),state:row.state,generation:row.generation,currentGeneration,revision:row.revision,error:row.error,quarantined:!!this.db.get("SELECT 1 FROM mail_recovery_quarantine WHERE kind='filing' AND entity_id=?",['storage-save:'+id]),parts:this.db.all('SELECT * FROM mail_storage_save_parts WHERE save_id=? ORDER BY ordinal',[id]).map(part=>({ordinal:part.ordinal,partIndex:part.part_index,path:part.path,bytes:part.bytes,sha256:part.sha256,mimeType:part.mime_type,state:part.state,version:part.version}))});}
 execute(supplied:StorageSaveInput):StorageSaveResult{const input=storageSaveInputSchema.parse(supplied);switch(input.action){
  case 'read':return{action:'read',save:this.read(input.accountId,input.id)};
  case 'list':{for(const id of input.accountIds)this.generation(id);const rows=this.db.all(`SELECT j.id,s.account_id FROM mail_storage_saves j JOIN mail_filing_snapshots s ON s.id=j.snapshot_id WHERE j.workspace_id=? AND s.account_id IN (${input.accountIds.map(()=>'?').join(',')}) AND j.id>? ORDER BY j.id LIMIT 51`,[input.workspaceId,...input.accountIds,input.after??'']);const items=rows.slice(0,50).map(row=>this.read(text.parse(row.account_id),text.parse(row.id)));while(Buffer.byteLength(JSON.stringify(items))>48000&&items.length>1)items.pop();return{action:'list',items,nextCursor:rows.length>items.length?items.at(-1)?.id??null:null};}
  case 'create':return this.db.transaction(()=>{
   const generation=this.generation(input.accountId),snapshot=new MailFilingStore(this.db,this.ownerId).execute({action:'snapshot',accountId:input.accountId,snapshotId:input.snapshotId});if(snapshot.action!=='snapshot')throw new MailServiceError('unavailable');
   const selection=[...new Set(input.selection)].sort((a,b)=>a-b),folder=storageSaveFolder(input.folderPath);if(selection.some(index=>!snapshot.snapshot.manifest.parts[index]))throw new MailServiceError('invalid_input');
   const previous=this.db.get('SELECT id FROM mail_storage_saves WHERE snapshot_id=? AND workspace_id=? AND storage_id=? AND root_revision=? AND folder_path=? AND selection_json=?',[input.snapshotId,input.workspaceId,input.storageId,input.rootRevision,folder,JSON.stringify(selection)]);if(previous){const save=this.read(input.accountId,text.parse(previous.id));if(save.quarantined)throw new MailServiceError('conflict');return{action:'create',save};}
   const id=randomUUID(),now=Date.now();this.db.run("INSERT INTO mail_storage_saves(id,snapshot_id,workspace_id,storage_id,root_revision,folder_path,selection_json,state,generation,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'queued',?,?,?)",[id,input.snapshotId,input.workspaceId,input.storageId,input.rootRevision,folder,JSON.stringify(selection),generation,now,now]);
   for(const [ordinal,index] of selection.entries()){const part=snapshot.snapshot.manifest.parts[index],name=part.filename.replace(/[<>:\"/\\|?*\x00-\x1f\x7f]/g,'_').replace(/[. ]+$/,'').slice(0,120)||'Attachment';this.db.run("INSERT INTO mail_storage_save_parts VALUES(?,?,?,?,?,?,?,'queued',NULL)",[id,ordinal,index,`mail-${id}-${String(index).padStart(3,'0')}-${name}`,part.size,part.sha256,part.mime_type]);}
   const manifest=Buffer.from(JSON.stringify(snapshot.snapshot.manifest));this.db.run("INSERT INTO mail_storage_save_parts VALUES(?,?,?,?,?,?,?,'queued',NULL)",[id,selection.length,-1,`mail-${id}-provenance.json`,manifest.length,createHash('sha256').update(manifest).digest('hex'),'application/json']);return{action:'create',save:this.read(input.accountId,id)};
  });
  case 'part':return this.db.transaction(()=>{const save=this.read(input.accountId,input.id),part=save.parts[input.ordinal];if(!part||save.quarantined||save.generation!==input.generation||this.generation(input.accountId)!==input.generation||save.revision!==input.revision||save.state==='cancelled'||part.state==='saved'||input.state==='saved'&&!input.version||input.state!=='saved'&&input.version!==null)throw new MailServiceError('conflict');this.db.run('UPDATE mail_storage_save_parts SET state=?,version=? WHERE save_id=? AND ordinal=?',[input.state,input.version,input.id,input.ordinal]);const complete=!this.db.get("SELECT 1 FROM mail_storage_save_parts WHERE save_id=? AND state!='saved'",[input.id]);this.db.run('UPDATE mail_storage_saves SET state=?,revision=revision+1,error=?,updated_at=? WHERE id=?',[complete?'complete':input.state==='uncertain'?'uncertain':'uploading',input.error,Date.now(),input.id]);return{action:'part',save:this.read(input.accountId,input.id)};});
 }}
}
