// AUTO-GENERATED by scripts/gen-office-fonts.mjs — DO NOT EDIT BY HAND.

/**
 * Office families that office-fonts.css already aliases to a bundled clone.
 * A document font in this set always renders locally, so it never needs to
 * be fetched and the font-consent prompt skips it.
 */
export const BUNDLED_OFFICE_FONTS: ReadonlySet<string> = new Set([
  "Calibri",
  "Cambria",
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Georgia",
  "Courier New",
  "Garamond",
  "Book Antiqua",
  "Palatino",
  "Palatino Linotype",
  "Verdana",
  "Tahoma",
  "Lucida Sans",
  "Segoe UI",
  "Trebuchet MS",
  "Century Gothic",
  "Franklin Gothic",
  "Impact",
  "Comic Sans MS",
  "Consolas",
  "Lucida Console",
  "Monaco",
]);
