import {useState,type ReactNode} from 'react';
import {ChevronLeft,ChevronRight,FileText,Paperclip,RefreshCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tooltip,TooltipContent,TooltipTrigger} from '@/components/ui/tooltip';
import {ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem} from '@/components/ui/context-menu';

export type MailWorkAction={label:string;disabled?:boolean;run:()=>void};
export type MailWorkRow={key:string;subject:string;recipient:string;preview:string;account:string;updatedAt:number;attachments:number;status:string;tone?:string};
export function mailWorkRecipients(summary?:{to:string[];recipientCount?:number}){const recipients=summary?.to.join(', ')??'',extra=(summary?.recipientCount??summary?.to.length??0)-(summary?.to.length??0);return recipients+(extra>0?` +${extra}`:'');}
export function MailWorkIcon({label,children,onClick,disabled=false}:{label:string;children:ReactNode;onClick:()=>void;disabled?:boolean}){
 return <Tooltip><TooltipTrigger render={<Button variant="ghost" size="icon-sm" aria-label={label} disabled={disabled} onClick={onClick}/>}>{children}</TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;
}
export function MailWorkList({title,subtitle,rows,selected,onSelect,onOpen,menuActions,onClose,onRefresh,loading,error,refreshDisabled=false,hasMore,onMore,children}:{title:string;subtitle:string;rows:MailWorkRow[];selected:string|null;onSelect:(key:string)=>void;onOpen?:(key:string)=>void;menuActions?:(key:string)=>MailWorkAction[];onClose:()=>void;onRefresh:()=>void;loading:boolean;error:string;refreshDisabled?:boolean;hasMore?:boolean;onMore?:()=>void;children:ReactNode}){
 const [query,setQuery]=useState(''),[page,setPage]=useState(0),[detail,setDetail]=useState(false);
 const matches=rows.filter(row=>[row.subject,row.recipient,row.account,row.preview,row.status].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const currentPage=Math.min(page,Math.max(0,Math.ceil(matches.length/50)-1)),visible=matches.slice(currentPage*50,(currentPage+1)*50);
 function select(key:string){onSelect(key);setDetail(true);}
 return <section className={`mail-work-view ${detail?'is-detail':''}`} aria-label={title} data-mail-shortcuts="off">
 <section className="mail-work-list" aria-label={`${title} list`}>
 <header><div><h2>{title}</h2><p>{subtitle}</p></div><MailWorkIcon label={`Refresh ${title.toLowerCase()}`} onClick={onRefresh} disabled={loading||refreshDisabled}><RefreshCw size={15}/></MailWorkIcon><MailWorkIcon label={`Close ${title.toLowerCase()}`} onClick={onClose}><X size={15}/></MailWorkIcon></header>
 <label className="mail-work-search"><Search size={14}/><input aria-label={`Filter ${title.toLowerCase()}`} placeholder={`Filter ${title.toLowerCase()}`} value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}}/></label>
 {error&&<div className="mail-work-notice" role="alert">{error}<Button variant="ghost" size="xs" onClick={onRefresh}>Retry</Button></div>}
 <div className="mail-work-scroll" onKeyDown={event=>{if(!['ArrowUp','ArrowDown','Home','End'].includes(event.key)||event.altKey||event.ctrlKey||event.metaKey)return;const buttons=[...event.currentTarget.querySelectorAll<HTMLButtonElement>('[data-work-row]')];const at=buttons.indexOf(event.target instanceof HTMLButtonElement?event.target:buttons[0]);const index=event.key==='Home'?0:event.key==='End'?buttons.length-1:Math.max(0,Math.min(buttons.length-1,at+(event.key==='ArrowDown'?1:-1)));event.preventDefault();buttons[index]?.focus();buttons[index]?.click();}}>
 {visible.map(row=><ContextMenu key={row.key}><ContextMenuTrigger onKeyDown={event=>{if(event.key==='ContextMenu'||event.key==='F10'&&event.shiftKey){event.preventDefault();event.stopPropagation();const box=event.currentTarget.getBoundingClientRect();event.currentTarget.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:box.left+24,clientY:box.top+20}));}}}><button data-work-row className={`mail-work-row ${selected===row.key?'is-selected':''}`} aria-pressed={selected===row.key} onClick={()=>select(row.key)} onDoubleClick={()=>onOpen?.(row.key)} onKeyDown={event=>{if(event.key==='Enter'&&onOpen){event.preventDefault();onOpen(row.key);}}}><span className="mail-work-row-top"><strong>{row.recipient||'No recipients'}</strong><time title={new Date(row.updatedAt).toLocaleString()}>{new Date(row.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time></span><span className="mail-work-subject">{row.subject||'(No subject)'}</span><span className="mail-work-preview">{row.preview||'No message text'}</span><span className="mail-work-row-bottom"><span className={`mail-work-status ${row.tone??''}`}>{row.status}</span><span className="mail-work-account">{row.account}</span>{row.attachments>0&&<span aria-label={`${row.attachments} attachments`}><Paperclip size={12}/>{row.attachments}</span>}</span></button></ContextMenuTrigger><ContextMenuContent><ContextMenuItem onClick={()=>select(row.key)}>View details</ContextMenuItem>{onOpen&&<ContextMenuItem onClick={()=>onOpen(row.key)}>Continue editing</ContextMenuItem>}{menuActions?.(row.key).map(action=><ContextMenuItem key={action.label} disabled={action.disabled} onClick={action.run}>{action.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>)}
 {loading&&<p className="mail-work-loading" role="status">Loading {title.toLowerCase()}…</p>}
 {!loading&&!error&&!visible.length&&<div className="mail-work-empty"><FileText size={26} strokeWidth={1.3}/><h3>{query?'No matching messages':title==='Drafts'?'No drafts yet':'Your outbox is clear'}</h3><p>{query?'Try another recipient, subject or account.':title==='Drafts'?'Messages you start are saved here as you write.':'Queued messages and recent sending activity appear here.'}</p></div>}
 </div><footer><MailWorkIcon label="Previous page" disabled={currentPage===0||loading} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={14}/></MailWorkIcon><span>{matches.length?`${currentPage*50+1}–${Math.min((currentPage+1)*50,matches.length)} of ${matches.length}`:'0 messages'}{hasMore?' loaded':''}</span><MailWorkIcon label={(currentPage+1)*50<matches.length?'Next page':hasMore?'Load more drafts':'Next page'} disabled={loading||((currentPage+1)*50>=matches.length&&!hasMore)} onClick={()=>{if((currentPage+1)*50<matches.length)setPage(currentPage+1);else{if(matches.length%50===0)setPage(currentPage+1);onMore?.();}}}><ChevronRight size={14}/></MailWorkIcon></footer>
 </section><section className="mail-work-detail" aria-label={`${title} details`}><button className="mail-work-back" onClick={()=>setDetail(false)}><ChevronLeft size={15}/>{title}</button>{children}</section></section>;
}
export function MailWorkEmpty({title,description}:{title:string;description:string}){return <div className="mail-work-empty"><FileText size={28} strokeWidth={1.2}/><h3>{title}</h3><p>{description}</p></div>;}
