/** @jsxImportSource react */
import {useEffect,useRef,useState} from 'react';
import {Folder,ChevronLeft,X,RefreshCw} from 'lucide-react';
import {z} from 'zod';
import {storageRootsViewSchema,storageFolderViewSchema,storageSaveSchema,type StorageSave} from '../../../../../server/src/mail/storage-save-view';
import {filingSnapshotSchema,type FilingSnapshot} from '../../../../../server/src/mail/filing-view';
import {safeFilename} from './mail-html';
import {MailClient,type MailMessageView} from './mail-client';
export function MailStorageSavePanel({client,accountIds,message,onClose,onMatter}:{client:MailClient;accountIds:string[];message?:MailMessageView;onClose:()=>void;onMatter:()=>void}){
 const [workspaces,setWorkspaces]=useState<Array<{id:string;name:string}>>([]),[workspace,setWorkspace]=useState(''),[roots,setRoots]=useState<z.infer<typeof storageRootsViewSchema>['roots']>([]),[rootId,setRootId]=useState(''),[path,setPath]=useState(''),[folders,setFolders]=useState<z.infer<typeof storageFolderViewSchema>['entries']>([]),[cursor,setCursor]=useState<string>(),[original,setOriginal]=useState(true),[attachments,setAttachments]=useState(true),[saves,setSaves]=useState<StorageSave[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pulse,setPulse]=useState(0);
 const [retained,setRetained]=useState<FilingSnapshot>();
 const active=useRef(new AbortController());
 useEffect(()=>{setRetained(undefined);const abort=new AbortController();active.current=abort;return()=>abort.abort();},[client,workspace,rootId]);
 useEffect(()=>{const abort=new AbortController();void client.request('/storage-save',z.object({items:z.array(z.object({id:z.string(),name:z.string()}))}),abort.signal,{action:'workspaces'}).then(result=>{if(!abort.signal.aborted){setWorkspaces(result.items);if(result.items.length===1)setWorkspace(result.items[0].id);}}).catch(()=>{if(!abort.signal.aborted)setError('Workspaces are unavailable. Retry.');});return()=>abort.abort();},[client]);
 useEffect(()=>{setRoots([]);setRootId('');setPath('');setError('');if(!workspace)return;const abort=new AbortController();void client.request('/storage-save',storageRootsViewSchema,abort.signal,{action:'roots',workspaceId:workspace}).then(result=>{if(!abort.signal.aborted){setRoots(result.roots);if(result.teamError)setError('Some team storage is unavailable. Refresh before saving.');}}).catch(()=>{if(!abort.signal.aborted)setError('Connected storage is unavailable. Configure File storage in Settings. This feature requires the shared storage integration.');});return()=>abort.abort();},[client,workspace,pulse]);
 useEffect(()=>{setFolders([]);setCursor(undefined);if(!workspace||!rootId)return;const abort=new AbortController();void client.request('/storage-save',storageFolderViewSchema,abort.signal,{action:'folders',workspaceId:workspace,storageId:rootId,path}).then(result=>{if(!abort.signal.aborted){setFolders(result.entries.filter(item=>item.kind==='folder'));setCursor(result.nextCursor);}}).catch(()=>{if(!abort.signal.aborted)setError('This folder is unavailable. Check access and retry.');});return()=>abort.abort();},[client,workspace,rootId,path]);
 useEffect(()=>{setSaves([]);if(!workspace||!accountIds.length)return;const abort=new AbortController();let loading=false;const load=async()=>{if(loading)return;loading=true;try{let after:string|undefined;const items:StorageSave[]=[];do{const page=await client.request('/storage-save',z.object({items:z.array(storageSaveSchema),nextCursor:z.string().nullable()}),abort.signal,{action:'list',workspaceId:workspace,accountIds,after});items.push(...page.items);after=page.nextCursor??undefined;if(items.length>2000)throw Error('Select one account to narrow retained saves.');}while(after);if(!abort.signal.aborted)setSaves(items);}catch{if(!abort.signal.aborted)setError('Save receipts are unavailable. Check account access and retry.');}finally{loading=false;}};void load();const timer=setInterval(()=>void load(),2000);return()=>{abort.abort();clearInterval(timer);};},[client,workspace,accountIds.join('\n'),pulse]);
 const save=async()=>{const root=roots.find(item=>item.id===rootId);if(!message||!root?.writable||!root.revision)return;const abort=active.current;setBusy(true);setError('');try{const snapshot=await client.request('/storage-save',z.object({snapshot:filingSnapshotSchema}),abort.signal,{action:'capture',workspaceId:workspace,accountId:message.accountId,locator:message.locator},false,60000);if(abort.signal.aborted)return;const selection=snapshot.snapshot.manifest.parts.flatMap((part,index)=>(part.kind==='original'?original:attachments)?[index]:[]);if(!selection.length)throw Error('No selected files');await client.request('/storage-save',z.object({save:storageSaveSchema}),abort.signal,{action:'save',workspaceId:workspace,accountId:message.accountId,snapshotId:snapshot.snapshot.id,storageId:rootId,rootRevision:root.revision,folderPath:path,selection},false,60000);if(!abort.signal.aborted)setPulse(value=>value+1);}catch{if(!abort.signal.aborted)setError('Save did not start. Download complete mail content, check the destination, and retry.');}finally{if(!abort.signal.aborted)setBusy(false);}};
 const retry=async(item:StorageSave)=>{const abort=active.current;setBusy(true);try{await client.request('/storage-save',z.object({save:storageSaveSchema}),abort.signal,{action:'save',workspaceId:item.workspaceId,accountId:item.accountId,snapshotId:item.snapshotId,storageId:item.storageId,rootRevision:item.rootRevision,folderPath:item.folderPath,selection:item.selection},false,60000);if(!abort.signal.aborted)setPulse(value=>value+1);}catch{if(!abort.signal.aborted)setError('Review files at the destination before retrying. Existing names are not overwritten; restored saves require a fresh destination selection.');}finally{if(!abort.signal.aborted)setBusy(false);}};
 const showRetained=async(item:StorageSave)=>{const abort=active.current;try{const result=await client.request('/storage-save',z.object({snapshot:filingSnapshotSchema}),abort.signal,{action:'snapshot',workspaceId:workspace,accountId:item.accountId,snapshotId:item.snapshotId});if(!abort.signal.aborted)setRetained(result.snapshot);}catch{if(!abort.signal.aborted)setError('Retained original is unavailable for this account.');}};
 const download=async(index:number)=>{if(!retained)return;const snapshot=retained,part=snapshot.manifest.parts[index],abort=active.current;setBusy(true);try{const bytes=new Uint8Array(part.size);let offset=0;do{const chunk=await client.request('/storage-save',z.object({data:z.string(),nextOffset:z.number(),done:z.boolean()}),abort.signal,{action:'chunk',workspaceId:workspace,accountId:snapshot.accountId,snapshotId:snapshot.id,part:index,offset,limit:24576});const data=Uint8Array.from(atob(chunk.data),char=>char.charCodeAt(0));if(chunk.nextOffset!==offset+data.length||chunk.nextOffset>part.size||!data.length&&!chunk.done)throw Error('Invalid retained range');bytes.set(data,offset);offset=chunk.nextOffset;}while(offset<part.size);const digest=await crypto.subtle.digest('SHA-256',bytes);if([...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('')!==part.sha256)throw Error('Retained hash differs');if(abort.signal.aborted)return;const url=URL.createObjectURL(new Blob([bytes],{type:part.mime_type})),link=document.createElement('a');link.href=url;link.download=safeFilename(part.filename);link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{if(!abort.signal.aborted)setError('Retained file verification failed.');}finally{if(!abort.signal.aborted)setBusy(false);}};
 const more=async()=>{const abort=active.current;try{const page=await client.request('/storage-save',storageFolderViewSchema,abort.signal,{action:'folders',workspaceId:workspace,storageId:rootId,path,cursor});if(!abort.signal.aborted){setFolders(current=>[...current,...page.entries.filter(item=>item.kind==='folder')]);setCursor(page.nextCursor);}}catch{if(!abort.signal.aborted)setError('Folder listing failed. Retry.');}};
 return <section className="mail-filing-panel" aria-label="Save mail to connected storage"><header><strong>Save to connected storage</strong><button aria-label="Refresh storage destinations" onClick={()=>setPulse(value=>value+1)}><RefreshCw size={14}/></button><button aria-label="Close storage save" onClick={onClose}><X size={15}/></button></header><label>Workspace<select aria-label="Storage save workspace" value={workspace} onChange={event=>{setBusy(false);setWorkspace(event.target.value);}}><option value="">Choose workspace</option>{workspaces.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
 {message&&<><label>Connection<select aria-label="Storage save connection" value={rootId} onChange={event=>{setBusy(false);setRootId(event.target.value);setPath('');}}><option value="">Choose writable storage</option>{roots.map(root=><option key={root.id} value={root.id} disabled={!root.writable||!root.revision}>{root.name}{root.writable?'':' · read only'}</option>)}</select></label>{rootId&&<><div><button aria-label="Parent storage folder" disabled={!path} onClick={()=>setPath(path.split('/').slice(0,-1).join('/'))}><ChevronLeft size={14}/></button><span>{path||'Connection root'}</span></div><div className="mail-filing-destinations">{folders.map(folder=><button key={folder.path} onClick={()=>setPath(folder.path)}><Folder size={13}/>{folder.name}</button>)}{cursor&&<button onClick={()=>void more()}>More folders</button>}</div></>}
 <label><input type="checkbox" checked={original} onChange={event=>setOriginal(event.target.checked)}/>Original email (.eml)</label><label><input type="checkbox" checked={attachments} onChange={event=>setAttachments(event.target.checked)}/>All attachments, including inline images</label><p>Save includes a provenance manifest. Original files remain retained on this computer. Unique names protect existing files.</p><button disabled={busy||!rootId||!original&&!attachments} onClick={()=>void save()}>Save to selected folder</button></>}
 {error&&<p role="alert">{error}</p>}<ul>{saves.map(item=><li key={item.id}><span>{roots.find(root=>root.id===item.storageId)?.name??item.storageId}<br/>{item.folderPath||'Connection root'}<small>{item.parts.filter(part=>part.state==='saved').length}/{item.parts.length} files verified</small></span><button onClick={()=>void showRetained(item)}>Retained files</button><span role="status">{item.quarantined?'Restored · review required':item.currentGeneration!==item.generation?'Account changed · select destination again':item.state==='complete'?'Saved':item.state==='uncertain'?'Review destination':item.state}</span>{!item.quarantined&&item.currentGeneration===item.generation&&item.state!=='complete'&&item.state!=='cancelled'&&<button disabled={busy} onClick={()=>void retry(item)}>Retry</button>}</li>)}</ul>{retained&&<div aria-label="Retained mail files"><strong>Verified local originals</strong>{retained.manifest.parts.map((part,index)=><button key={index} disabled={busy} onClick={()=>void download(index)}>{part.filename}</button>)}</div>}<p>File storage saves do not grant matter access or automatically index mail.</p><button onClick={onMatter}>File in a LegalMemory matter…</button></section>;
}
