import {useEffect,useRef,useState} from 'react';
import {FileText,Paperclip,SquarePen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {MailDraftSummary,MailDraftView} from '../../../../../server/src/mail/local-view';
import type {MailClient,MailAccountView} from './mail-client';
import type {ComposeSelection} from './mail-composer';
import {draftPage,draftRead} from './mail-compose-client';
import {recoveryDrafts,type DraftRecovery} from './mail-draft-recovery';
import {mailWorkRecipients,MailWorkList,MailWorkEmpty,type MailWorkRow} from './mail-work-list';
type Entry={key:string;account:string;name:string;draft:MailDraftSummary;recovery?:DraftRecovery};
export function MailDrafts({client,accounts,onOpen,onClose}:{client:MailClient;accounts:MailAccountView[];onOpen:(value:ComposeSelection)=>void;onClose:()=>void}){
 const accountScope=JSON.stringify(accounts.map(account=>[account.id,account.displayName]));
 const [items,setItems]=useState<Entry[]>([]),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<MailDraftView|null>(null),[error,setError]=useState(''),[detailError,setDetailError]=useState(''),[loading,setLoading]=useState(true),[reading,setReading]=useState(false),[revision,setRevision]=useState(0),[cursors,setCursors]=useState<Record<string,string|null>>({});
 const active=useRef<AbortController|null>(null),read=useRef<AbortController|null>(null),openLock=useRef(false);
 const entry=items.find(item=>item.key===selected);
 async function load(controller:AbortController,more=false){setLoading(true);setError('');try{const pages=await Promise.all(accounts.filter(account=>!more||cursors[account.id]).map(async account=>({account,page:await draftPage(client,account.id,more?cursors[account.id]??undefined:undefined,controller.signal)})));const recovery=more?[]:await recoveryDrafts();if(controller.signal.aborted)return;const next=pages.flatMap(({account,page})=>page.items.map(draft=>({key:account.id+':'+draft.id,account:account.id,name:account.displayName,draft})));const recovered:Entry[]=recovery.filter(value=>accounts.some(account=>account.id===value.accountId)).map(value=>({key:'recovery:'+value.id,account:value.accountId,name:accounts.find(account=>account.id===value.accountId)?.displayName??'',draft:{id:value.draftId,subject:value.content.subject,updatedAt:value.updatedAt,deleted:false,version:value.version??{generation:value.draftId,revision:1},summary:{to:value.content.to.slice(0,1),recipientCount:value.content.to.length+value.content.cc.length+value.content.bcc.length,preview:value.content.text.slice(0,160),attachmentCount:value.content.attachments.length}},recovery:value}));setItems(previous=>[...(more?previous:recovered),...next.sort((a,b)=>b.draft.updatedAt-a.draft.updatedAt)]);setCursors(previous=>({...more?previous:{},...Object.fromEntries(pages.map(({account,page})=>[account.id,page.nextCursor]))}));}catch{if(!controller.signal.aborted)setError('Drafts could not be loaded. Saved messages remain on this device.');}finally{if(!controller.signal.aborted)setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();active.current=controller;setItems([]);setSelected(null);void load(controller);return()=>{controller.abort();read.current?.abort();};},[client,accountScope,revision]);
 useEffect(()=>{const controller=new AbortController();read.current?.abort();read.current=controller;setDetail(null);setDetailError('');if(!entry){setReading(false);return()=>controller.abort();}if(entry.recovery){setDetail({...entry.draft,content:entry.recovery.content});setReading(false);return()=>controller.abort();}setReading(true);void draftRead(client,entry.account,entry.draft.id,controller.signal).then(value=>{if(!controller.signal.aborted)setDetail(value);}).catch(()=>{if(!controller.signal.aborted)setDetailError('This draft could not be opened. Refresh Drafts and try again.');}).finally(()=>{if(!controller.signal.aborted)setReading(false);});return()=>controller.abort();},[client,selected,entry?.draft.version.revision,entry?.draft.version.generation]);
 async function open(key:string){if(openLock.current)return;const value=items.find(item=>item.key===key);if(!value)return;openLock.current=true;const controller=active.current;try{if(!controller)return;if(value.recovery){onOpen({account:value.account,id:value.draft.id,content:value.recovery.content,version:value.recovery.version,recovery:{id:value.recovery.id,revision:value.recovery.revision}});return;}const draft=await draftRead(client,value.account,value.draft.id,controller.signal);if(!controller.signal.aborted)onOpen({account:value.account,id:draft.id,content:draft.content,version:draft.version});}catch{if(!controller?.signal.aborted)setError('This draft could not be opened. Refresh and try again.');}finally{openLock.current=false;}}
 const rows:MailWorkRow[]=items.map(item=>({key:item.key,subject:item.draft.subject,recipient:mailWorkRecipients(item.draft.summary),preview:item.draft.summary?.preview??'',account:item.name,updatedAt:item.draft.updatedAt,attachments:item.draft.summary?.attachmentCount??0,status:item.recovery?'Device recovery':'Draft',tone:item.recovery?'attention':''}));
 return <MailWorkList title="Drafts" subtitle="Saved on this device" rows={rows} selected={selected} onSelect={setSelected} onOpen={key=>void open(key)} onClose={()=>{active.current?.abort();onClose();}} onRefresh={()=>setRevision(value=>value+1)} loading={loading} error={error} hasMore={Object.values(cursors).some(Boolean)} onMore={()=>{if(active.current)void load(active.current,true);}}>
 {reading?<p className="mail-work-loading" role="status">Opening draft…</p>:detailError?<div className="mail-work-notice" role="alert">{detailError}</div>:detail&&entry?<article className="mail-work-message"><header><span className="mail-work-eyebrow"><FileText size={14}/>{entry.recovery?'Device recovery':'Saved draft'}</span><Button size="sm" onClick={()=>void open(entry.key)}><SquarePen size={14}/>{entry.recovery?'Recover draft':'Continue editing'}</Button></header><h2>{detail.subject||'(No subject)'}</h2><dl><dt>From</dt><dd>{detail.content.from||entry.name}</dd><dt>To</dt><dd>{detail.content.editor?.to||detail.content.to.join(', ')||'No recipients yet'}</dd>{detail.content.cc.length>0&&<><dt>Cc</dt><dd>{detail.content.cc.join(', ')}</dd></>}{detail.content.bcc.length>0&&<><dt>Bcc</dt><dd>{detail.content.bcc.join(', ')}</dd></>}<dt>Edited</dt><dd>{new Date(detail.updatedAt).toLocaleString()}</dd></dl>{entry.recovery&&<p className="mail-work-notice">Changes recovered from this device. Continue editing to save them back to Drafts.</p>}<div className="mail-work-body">{detail.content.text||'Your message is still blank.'}</div>{detail.content.attachments.length>0&&<div className="mail-work-attachments">{detail.content.attachments.map(part=><span key={part.partId}><Paperclip size={14}/>{part.filename}</span>)}</div>}</article>:<MailWorkEmpty title="Pick up where you left off" description="Select a draft to preview it, then continue editing. Double-click a draft to open it directly."/>}
 </MailWorkList>;
}
