/** @jsxImportSource react */
import {useEffect,useRef,useState} from 'react';
import {RefreshCw,Cloud,Trash2} from 'lucide-react';
import {draftSyncStatusSchema,type DraftSyncStatus,type DraftSyncRequest} from '../../../../../server/src/mail/draft-sync-view';
import type {MailDraftView} from '../../../../../server/src/mail/local-view';
import type {MailClient} from './mail-client';
const explanations:Record<NonNullable<DraftSyncStatus['error']>,string>={incomplete:'Complete valid addresses and keep the message within the compose limits before syncing. Your local draft is retained.',unsupported:'This account cannot safely store this draft remotely. IMAP requires a designated Drafts folder and UIDPLUS.',permission:'Draft access changed. Review account access before retrying.',remote_changed:'Another client changed the remote draft. Both versions are retained until you choose.',remote_missing:'The remote draft was removed elsewhere. Save a local copy before starting a new remote draft.',dispatch_unknown:'The provider outcome is uncertain. Retry checks for the existing draft; it will not create another copy.',retryable:'The provider is unavailable. Retry when connected.',local_changed:'The local draft changed during recovery. Reopen it to continue.',provider_rejected:'The provider did not accept or verify this draft. Your local content is retained.'};
export function MailDraftSync({client,account,id,version,saving,onReload,onRemoved,onCopy}:{client:MailClient;account:string;id:string;version:MailDraftView['version']|null;saving:boolean;onReload:()=>Promise<void>;onRemoved:()=>void;onCopy:()=>void}){
 const [status,setStatus]=useState<DraftSyncStatus|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const adopting=useRef(false),active=useRef<AbortController|null>(null);
 useEffect(()=>{const controller=new AbortController();active.current=controller;setStatus(null);async function read(){if(!version)return;try{const value=await client.request(`/accounts/${encodeURIComponent(account)}/drafts/sync/status`,draftSyncStatusSchema,controller.signal,{draftId:id});if(controller.signal.aborted)return;setStatus(value);if(value.state==='removed')onRemoved();if(adopting.current&&value.state==='synced'){adopting.current=false;await onReload();}}catch{/* Local saving remains usable while the worker restarts. */}}void read();const timer=setInterval(()=>void read(),2000);return()=>{controller.abort();clearInterval(timer);};},[client,account,id,version?.generation,version?.revision]);
 async function request(action:DraftSyncRequest['action']){if(!version||!active.current)return;const controller=active.current;setBusy(true);setError('');try{const value=await client.request(`/accounts/${encodeURIComponent(account)}/drafts/sync/request`,draftSyncStatusSchema,controller.signal,{draftId:id,expected:version,action,...(status?.remoteHash?{remoteHash:status.remoteHash}:{})});if(!controller.signal.aborted){adopting.current=action==='use_remote';setStatus(value);}}catch{if(!controller.signal.aborted)setError('Unable to update draft synchronization. Save or reopen the draft, then retry.');}finally{if(!controller.signal.aborted)setBusy(false);}}
 const disabled=busy||saving||!version||status?.state==='syncing'||status?.state==='queued';
 return <div className="mail-draft-sync"><small role="status">{status?.state==='synced'?(status.dirty?'Local changes waiting to sync':'Saved locally and with provider'):status?.state==='syncing'||status?.state==='queued'?'Synchronizing draft…':status?.state==='conflict'?'Draft conflict':status?.state==='uncertain'?'Remote outcome needs recovery':status?.enabled?'Provider draft needs attention':'Saved on this device'}</small>{status?.error&&<p role="alert">{explanations[status.error]}</p>}{error&&<p role="alert">{error}</p>}
 <div className="mail-compose-tools">{(status?.state==='conflict'||status?.state==='uncertain')&&<button disabled={saving} onClick={onCopy}>Save local copy</button>}<button disabled={disabled||status?.state==='conflict'} aria-label="Sync draft with provider" title="Enable provider draft synchronization" onClick={()=>void request(status?.state==='uncertain'||status?.state==='error'?'retry':'sync')}><Cloud size={15}/>Sync</button>{status?.state==='conflict'&&status.remoteHash&&<><button disabled={disabled} onClick={()=>void request('keep_local')}>Keep local</button><button disabled={disabled} onClick={()=>void request('use_remote')}>Use remote</button></>}{status?.enabled&&<button disabled={disabled} title="Stop automatic provider draft synchronization" onClick={()=>void request('disable')}><RefreshCw size={15}/>Pause sync</button>}<button disabled={disabled||status?.state==='conflict'||status?.state==='uncertain'} title="Delete local and linked provider draft after verification" onClick={()=>void request('delete')}><Trash2 size={15}/>Delete draft</button></div></div>;
}
