/** @jsxImportSource react */
import {useEffect,useRef,useState} from 'react';
import {FolderPlus,X,RefreshCw} from 'lucide-react';
import {z} from 'zod';
import {filingItemSchema,filingSnapshotSchema,type FilingItem} from '../../../../../server/src/mail/filing-view';
import {MailClient,type MailMessageView} from './mail-client';
const workspacesSchema=z.object({items:z.array(z.object({id:z.string(),name:z.string()}))});
const destinationsSchema=z.object({results:z.array(z.object({id:z.string(),title:z.string(),project_id:z.string()})),next_offset:z.number().nullable()});
const itemsSchema=z.object({items:z.array(filingItemSchema),nextCursor:z.string().nullable()});
export function MailFilingPanel({client,accountIds,message,onClose}:{client:MailClient;accountIds:string[];message?:MailMessageView;onClose:()=>void}){
 const [workspaces,setWorkspaces]=useState<Array<{id:string;name:string}>>([]),[workspace,setWorkspace]=useState(''),[destinations,setDestinations]=useState<Array<{id:string;title:string}>>([]),[selected,setSelected]=useState<string[]>([]),[items,setItems]=useState<FilingItem[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pulse,setPulse]=useState(0);
 const active=useRef(new AbortController());
 useEffect(()=>{const abort=new AbortController();active.current=abort;setBusy(false);return()=>abort.abort();},[client,workspace,JSON.stringify(message?[message.accountId,message.locator]:null)]);
 useEffect(()=>{const abort=new AbortController();void client.request('/filing',workspacesSchema,abort.signal,{action:'workspaces'}).then(value=>{if(abort.signal.aborted)return;setWorkspaces(value.items);if(value.items.length===1)setWorkspace(value.items[0].id);}).catch(()=>{if(!abort.signal.aborted)setError('Workspace settings are unavailable. Retry or review Settings.');});return()=>abort.abort();},[client]);
 useEffect(()=>{setItems([]);setDestinations([]);setSelected([]);setError('');if(!workspace)return;const abort=new AbortController();
  void(async()=>{try{let offset:number|null=0;const found:Array<{id:string;title:string}>=[];do{const page:z.infer<typeof destinationsSchema>=await client.request('/filing',destinationsSchema,abort.signal,{action:'destinations',workspaceId:workspace,offset});found.push(...page.results);offset=page.next_offset;if(found.length>10000)throw Error('Too many destinations. Narrow workspace access in Settings.');}while(offset!==null);if(!abort.signal.aborted)setDestinations(found);}catch{if(!abort.signal.aborted)setError('Writable matters are unavailable. Check LegalMemory sign-in and matter permissions in Settings.');}})();
  return()=>abort.abort();
 },[client,workspace,pulse]);
 useEffect(()=>{if(!workspace||!accountIds.length)return;const abort=new AbortController();const load=async()=>{try{let after:string|undefined;const found:FilingItem[]=[];do{const page:z.infer<typeof itemsSchema>=await client.request('/filing',itemsSchema,abort.signal,{action:'list',workspaceId:workspace,accountIds,after});found.push(...page.items);after=page.nextCursor??undefined;if(found.length>2000)throw Error('Too many retained filings. Select one account.');}while(after);if(!abort.signal.aborted)setItems(found);}catch{if(!abort.signal.aborted)setError('Retained filing status is unavailable. Check account access and retry.');}};void load();const timer=setInterval(()=>void load(),2000);return()=>{abort.abort();clearInterval(timer);};},[client,workspace,accountIds.join('\n'),pulse]);
 const file=async()=>{if(!message||!selected.length)return;setBusy(true);setError('');const abort=active.current;try{const captured=await client.request('/filing',z.object({snapshot:filingSnapshotSchema}),abort.signal,{action:'capture',workspaceId:workspace,accountId:message.accountId,locator:message.locator},false,60000);for(const matterId of selected){if(abort.signal.aborted)return;await client.request('/filing',z.object({item:filingItemSchema}),abort.signal,{action:'file',workspaceId:workspace,accountId:message.accountId,snapshotId:captured.snapshot.id,matterId},false,60000);}if(abort.signal.aborted)return;setSelected([]);setPulse(value=>value+1);}catch{if(!abort.signal.aborted)setError('Filing did not complete. Download the full message and attachments, check matter access, then retry. Retained work remains on this computer.');}finally{if(!abort.signal.aborted)setBusy(false);}};
 const retry=async(item:FilingItem)=>{const abort=active.current;setBusy(true);try{await client.request('/filing',z.object({item:filingItemSchema}),abort.signal,{action:'file',workspaceId:workspace,accountId:item.accountId,snapshotId:item.snapshotId,matterId:item.matterId},false,60000);if(abort.signal.aborted)return;setPulse(value=>value+1);}catch{if(!abort.signal.aborted)setError('Retry requires current account and filing permission. Restored filings require a fresh destination selection.');}finally{if(!abort.signal.aborted)setBusy(false);}};
 return <section className="mail-filing-panel" aria-label="Matter filing"><header><strong><FolderPlus size={15}/> Matter filing</strong><button aria-label="Refresh filing" onClick={()=>setPulse(value=>value+1)}><RefreshCw size={14}/></button><button aria-label="Close matter filing" onClick={onClose}><X size={15}/></button></header>
 <label>Workspace<select aria-label="Filing workspace" value={workspace} onChange={event=>setWorkspace(event.target.value)}><option value="">Choose workspace</option>{workspaces.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
 {message&&<><p>Retain the exact original and all attachments in each selected matter. Filing starts ingestion and keeps a separate local original.</p><div className="mail-filing-destinations">{destinations.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} disabled={busy||selected.length>=10&&!selected.includes(item.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/>{item.title}</label>)}</div><button disabled={busy||!selected.length} onClick={()=>void file()}>File in {selected.length||'selected'} {selected.length===1?'matter':'matters'}</button></>}
 {error&&<p role="alert">{error}</p>}<p>Provider deletion does not remove retained originals or LegalMemory copies. Uploads interrupted by restart need an explicit retry.</p>
 <ul>{items.map(item=><li key={item.id}><span>{destinations.find(matter=>matter.id===item.matterId)?.title??item.matterId}</span><span role="status">{item.quarantined?'Restored — select destination again':item.state==='filed'?'Filed · ingestion queued':item.state==='uncertain'?'Needs review / retry':item.state}</span>{!item.quarantined&&['uncertain','error','queued','uploading'].includes(item.state)&&<button disabled={busy} onClick={()=>void retry(item)}>Retry</button>}</li>)}</ul>
 </section>;
}

export function MailMatterFilter({client,accountIds,value,onChange}:{client:MailClient;accountIds:string[];value:{workspaceId:string;matterId:string};onChange:(value:{workspaceId:string;matterId:string})=>void}){
 const [workspaces,setWorkspaces]=useState<Array<{id:string;name:string}>>([]),[matters,setMatters]=useState<string[]>([]),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();void client.request('/filing',workspacesSchema,abort.signal,{action:'workspaces'}).then(result=>{if(!abort.signal.aborted)setWorkspaces(result.items);}).catch(()=>{if(!abort.signal.aborted)setError('Filing workspaces unavailable.');});return()=>abort.abort();},[client]);
 useEffect(()=>{setMatters([]);setError('');if(!value.workspaceId||!accountIds.length)return;const abort=new AbortController();void(async()=>{try{let after:string|undefined;const found=new Set<string>();do{const page:z.infer<typeof itemsSchema>=await client.request('/filing',itemsSchema,abort.signal,{action:'list',workspaceId:value.workspaceId,accountIds,after});for(const item of page.items)if(item.state==='filed')found.add(item.matterId);after=page.nextCursor??undefined;if(found.size>10000)throw Error('Too many matters.');}while(after);if(!abort.signal.aborted)setMatters([...found]);}catch{if(!abort.signal.aborted)setError('Filed matters unavailable. Retry after checking account access.');}})();return()=>abort.abort();},[client,value.workspaceId,accountIds.join('\n')]);
 return <div><label>Filing workspace<select aria-label="Matter filter workspace" value={value.workspaceId} onChange={event=>onChange({workspaceId:event.target.value,matterId:''})}><option value="">All local mail</option>{workspaces.map(workspace=><option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></label>{value.workspaceId&&<label>Actually filed in matter<select aria-label="Actually filed in matter" value={value.matterId} onChange={event=>onChange({...value,matterId:event.target.value})}><option value="">Choose a filed matter</option>{matters.map(id=><option key={id} value={id}>{id}</option>)}</select></label>}{error&&<p role="alert">{error}</p>}</div>;
}
