import {outboxErrors} from './mail-outbox-errors';
/** @jsxImportSource react */
import {useEffect,useState} from 'react';
import {X} from 'lucide-react';
import {outboxItemSchema,smtpStatusSchema,type OutboxItem,type SmtpConfigure} from '../../../../../server/src/mail/outbox-view';
import type {MailSubmission} from '../../../../../server/src/mail/local-view';
import {MailClient,type MailAccountView} from './mail-client';

const base=(account:string)=>`/accounts/${encodeURIComponent(account)}`;
export const queueOutbox=(client:MailClient,account:string,input:MailSubmission)=>client.request(base(account)+'/outbox/queue',outboxItemSchema,new AbortController().signal,input,false,90000);
export const smtpStatus=(client:MailClient,account:string,signal:AbortSignal)=>client.request(base(account)+'/smtp',smtpStatusSchema,signal);
export const configureSmtp=(client:MailClient,account:string,input:SmtpConfigure)=>client.request(base(account)+'/smtp/configure',smtpStatusSchema,new AbortController().signal,input);
export const removeSmtp=(client:MailClient,account:string)=>client.request(base(account)+'/smtp/remove',smtpStatusSchema,new AbortController().signal,undefined,true);
export function MailOutbox({client,accounts,onClose}:{client:MailClient;accounts:MailAccountView[];onClose:()=>void}){
 const [items,setItems]=useState<OutboxItem[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();let running=false;async function load(){if(running)return;running=true;try{const pages=await Promise.all(accounts.map(account=>client.request(base(account.id)+'/outbox',outboxItemSchema.array().max(100),controller.signal)));if(!controller.signal.aborted){setItems(pages.flat().sort((a,b)=>b.createdAt-a.createdAt));setError('');}}catch{if(!controller.signal.aborted)setError('Outbox could not be refreshed. Queued messages remain on this device.');}finally{running=false;}}void load();const timer=setInterval(()=>void load(),2000);return()=>{controller.abort();clearInterval(timer);};},[client,accounts,revision]);
 async function action(item:OutboxItem,action:'cancel'|'retry'|'reconcile'){setBusy(item.id);setError('');try{await client.request(base(item.accountId)+'/outbox/action',outboxItemSchema,new AbortController().signal,{actionId:item.id,action},false,90000);setRevision(value=>value+1);}catch(error){setError(error instanceof Error?error.message:'Outbox action failed.');}finally{setBusy('');}}
 return <section className="mail-composer" aria-label="Outbox"><header><h2>Outbox</h2><button aria-label="Close outbox" onClick={onClose}><X size={16}/></button></header><p className="mail-compose-hint">Accepted means the outgoing server accepted submission. Delivery and later bounces are not confirmed here. Queued messages send while LegalWork is running.</p>{error&&<p role="alert">{error}</p>}{items.map(item=><article className="mail-draft-row" key={item.accountId+item.id}><strong>{item.subject||'(No subject)'}</strong><small>{item.from} · {item.state} · {item.attempts} attempt{item.attempts===1?'':'s'}</small>{item.error&&<p>{outboxErrors[item.error]}</p>}{item.result?.reconciled&&<p>A matching Sent copy was found. Delivery and individual recipient outcomes remain unconfirmed.</p>}{item.result&&<p>Sent copy: {item.result.sentCopy}. {item.result.rejected.length?`Partial acceptance: ${item.result.rejected.map(value=>value.address).join(', ')} rejected. The draft is retained; retry only rejected recipients in a new draft.`:'Delivery status unknown.'}</p>}{item.state==='accepted'&&item.result?.sentCopy==='unavailable'&&<p>{outboxErrors.sent_copy_unavailable}</p>}<div>{['queued','sending','uncertain'].includes(item.state)&&<button disabled={busy===item.id} onClick={()=>void action(item,'cancel')}>{item.cancellationGuaranteed?'Cancel queued send':'Stop further attempts'}</button>}{!item.cancellationGuaranteed&&['sending','uncertain'].includes(item.state)&&<small> Remote submission may already have happened; cancellation cannot retract mail.</small>}{item.state==='failed'&&item.error!=='preparation_unknown'&&<button disabled={busy===item.id} onClick={()=>void action(item,'retry')}>Retry rejected submission</button>}{item.state==='uncertain'&&<button disabled={busy===item.id} onClick={()=>void action(item,'reconcile')}>Check Sent for acceptance</button>}</div></article>)}{!items.length&&!error&&<p>No outgoing messages.</p>}</section>;
}
