/** @jsxImportSource react */
import { useEffect, useRef, useState } from 'react';
import { Bold, Italic, Paperclip, Image, Save, X, Send, Pencil, FileText } from 'lucide-react';
import { mailAddressSchema, mailDraftContentSchema, type MailDraftView, type MailDraftSummary } from '../../../../../server/src/mail/local-view';
import { MailClient, type MailAccountView } from './mail-client';
import { addresses, emptyCompose, safeComposeHtml, type ComposeContent } from './mail-compose-model';
import { ComposeSaveQueue, draftPage, draftRead, uploadComposeFile, composeAttachmentBytes } from './mail-compose-client';
function editorHtml(element:HTMLDivElement){const copy=element.cloneNode(true);if(!(copy instanceof HTMLDivElement))return '';for(const image of copy.querySelectorAll('img[data-mail-cid]')){image.setAttribute('src','cid:'+image.getAttribute('data-mail-cid'));image.removeAttribute('data-mail-cid');}return copy.innerHTML;}
const recipientFields:('to'|'cc'|'bcc')[]=['to','cc','bcc'];
export type ComposeSelection={account:string;id:string;content:ComposeContent;version:MailDraftView['version']|null};
export function MailDrafts({client,accounts,onOpen,onClose}:{client:MailClient;accounts:MailAccountView[];onOpen:(value:ComposeSelection)=>void;onClose:()=>void}){
 const [items,setItems]=useState<{account:string;name:string;draft:MailDraftSummary}[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;void(async()=>{const result:typeof items=[];for(const account of accounts){let after:string|undefined;do{const page=await draftPage(client,account.id,after);for(const draft of page.items)result.push({account:account.id,name:account.displayName,draft});after=page.nextCursor??undefined;if(result.length>5000)throw Error('Too many drafts to list.');}while(after);}if(active)setItems(result.sort((a,b)=>b.draft.updatedAt-a.draft.updatedAt));})().catch(error=>{if(active)setError(String(error));});return()=>{active=false;};},[client,accounts]);
 return <section className="mail-composer" aria-label="Saved drafts"><header><h2>Drafts</h2><button aria-label="Close drafts" onClick={onClose}><X size={16}/></button></header>{error&&<p role="alert">{error}</p>}{items.map(item=><button className="mail-draft-row" key={item.account+item.draft.id} onClick={()=>void draftRead(client,item.account,item.draft.id).then(draft=>onOpen({account:item.account,id:draft.id,content:draft.content,version:draft.version})).catch(error=>setError(String(error)))}><strong>{item.draft.subject||'(No subject)'}</strong><small>{item.name} · {new Date(item.draft.updatedAt).toLocaleString()}</small></button>)}{!items.length&&!error&&<p>No saved drafts.</p>}</section>;
}
export function MailComposer({client,accounts,initial,onClose,onSwitch}:{client:MailClient;accounts:MailAccountView[];initial:ComposeSelection;onClose:()=>void;onSwitch:(value:ComposeSelection)=>void}){
 const [content,setContent]=useState(initial.content),[,redraw]=useState(0),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[history,setHistory]=useState<string[]>([]);
 const [previews,setPreviews]=useState<Record<string,string>>({});
 const editor=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),imageInput=useRef<HTMLInputElement>(null),mounted=useRef(true);
 const queue=useRef<ComposeSaveQueue|null>(null);if(!queue.current)queue.current=new ComposeSaveQueue(client,initial.account,initial.id,initial.version,()=>{if(mounted.current)redraw(value=>value+1);});
 const saver=queue.current;
 const current=useRef(content);current.current=content;
 const fields=content.editor??{to:content.to.join(', '),cc:content.cc.join(', '),bcc:content.bcc.join(', '),from:content.from??''};
 function update(value:ComposeContent){const checked=mailDraftContentSchema.safeParse(value);if(!checked.success){setError('This draft exceeds the 24 KiB text and address limit. Shorten it before saving.');return;}setContent(value);setError('');void saver.save(checked.data);}
 useEffect(()=>{mounted.current=true;if(!initial.version)void saver.save(initial.content);return()=>{mounted.current=false;};},[saver]);
 useEffect(()=>{const unload=(event:BeforeUnloadEvent)=>{if(saver.running||saver.pending||error||uploading){event.preventDefault();event.returnValue='Draft changes are still saving.';}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[saver,error,uploading]);
 useEffect(()=>{let active=true;void(async()=>{const page=await draftPage(client,initial.account);const previous=await Promise.all(page.items.map(item=>draftRead(client,initial.account,item.id)));if(active)setHistory([...new Set(previous.flatMap(item=>[...item.content.to,...item.content.cc,...item.content.bcc]))]);})().catch(()=>{});return()=>{active=false;};},[client,initial.account]);
 useEffect(()=>{if(!editor.current||content.html===null)return;if(editorHtml(editor.current)!==content.html)editor.current.innerHTML=safeComposeHtml(content.html);for(const image of editor.current.querySelectorAll('img')){const cid=image.getAttribute('data-mail-cid')??image.getAttribute('src')?.replace(/^cid:/,'');if(cid&&previews[cid]){image.setAttribute('data-mail-cid',cid);image.src=previews[cid];}}},[content.html,previews]);
 useEffect(()=>{if(!saver.version||saver.running)return;let active=true;const urls:string[]=[];const version=saver.version;void(async()=>{const next:Record<string,string>={};for(const [index,part] of content.attachments.entries()){if(part.disposition!=='inline'||!part.contentId)continue;const bytes=await composeAttachmentBytes(client,initial.account,initial.id,version,index,part.referenceId);if(!active)return;const url=URL.createObjectURL(new Blob([bytes],{type:part.contentType}));urls.push(url);next[part.contentId]=url;}if(active)setPreviews(next);})().catch(()=>{});return()=>{active=false;for(const url of urls)URL.revokeObjectURL(url);};},[client,initial.account,initial.id,saver.version,saver.running,content.attachments]);
 async function close(){await saver.running;if(saver.pending||saver.error||error||uploading){setError('Keep this draft open until all changes have saved. Retry Save when mail is available.');return;}onClose();}
 function field(name:'to'|'cc'|'bcc'|'from',value:string){const next={...fields,[name]:value};update({...content,editor:next,to:addresses(next.to),cc:addresses(next.cc),bcc:addresses(next.bcc),from:mailAddressSchema.safeParse(next.from).success?next.from:null});}
 function rich(){if(content.html===null){const div=document.createElement('div');div.textContent=content.text;update({...content,html:div.innerHTML.replace(/\n/g,'<br>')});}else update({...content,html:null});}
 function richChange(){if(!editor.current)return;const html=safeComposeHtml(editor.current.innerHTML);update({...current.current,html,text:editor.current.innerText});}
 async function attach(files:FileList|null,inline:boolean){if(!files?.length)return;setUploading(true);setError('');try{let next=current.current;for(const file of Array.from(files)){if(next.attachments.reduce((total,part)=>total+(part.bytes??0),0)+file.size>20*1024*1024)throw Error('Attachments must total 20 MiB or less.');if(next.attachments.length>=20)throw Error('A draft can contain at most 20 attachments.');if(inline&&!/^image\/(png|jpeg|gif|webp)$/.test(file.type))throw Error('Use PNG, JPEG, GIF or WebP for inline images.');const part=await uploadComposeFile(client,initial.account,file);next=current.current;if(inline){part.disposition='inline';part.contentId=crypto.randomUUID()+'@legalwork';const div=document.createElement('div');div.textContent=next.text;next={...next,html:(next.html??div.innerHTML.replace(/\n/g,'<br>'))+`<p><img src="cid:${part.contentId}"></p>`};}next={...next,attachments:[...next.attachments,part]};update(next);}}catch(error){setError(error instanceof Error?error.message:'Attachment could not be added.');}finally{setUploading(false);if(fileInput.current)fileInput.current.value='';if(imageInput.current)imageInput.current.value='';}}
 const invalid=['to','cc','bcc'].some(name=>{const value=name==='to'?fields.to:name==='cc'?fields.cc:fields.bcc;return value.split(/[,;]/).some(part=>part.trim()&&!addresses(part).length);})||!mailAddressSchema.safeParse(fields.from).success;
 return <section className="mail-composer" aria-label="Compose message"><header><h2>{content.inReplyTo?'Reply':'New message'}</h2><span role="status">{saver.error?'Not saved':saver.running?'Saving…':saver.version?'Saved locally':'New draft'}</span><button title="Save draft" aria-label="Save draft" onClick={()=>update(content)}><Save size={16}/></button><button title="Save and close" aria-label="Close composer" onClick={()=>void close()}><X size={16}/></button></header>
 <label>Account<select aria-label="Sending account" value={initial.account} disabled={uploading||!!content.attachments.length} onChange={async event=>{const account=event.target.value;await saver.running;if(saver.error||saver.pending){setError('Save this draft before changing accounts.');return;}const from=addresses(accounts.find(item=>item.id===account)?.displayName??'')[0]??'';onSwitch({account,id:crypto.randomUUID(),version:null,content:{...content,from:emptyCompose(from).from,editor:{...fields,from}}});}}>{accounts.map(account=><option key={account.id} value={account.id}>{account.displayName} ({account.provider==='graph'?'Microsoft':account.provider==='gmail'?'Google':'IMAP'})</option>)}</select></label>
 <label>From<input aria-label="Sender email" value={fields.from} onChange={event=>field('from',event.target.value)} placeholder="sender@example.com"/></label>
 {recipientFields.map(name=><label key={name}>{name==='to'?'To':name==='cc'?'Cc':'Bcc'}<input aria-label={name==='to'?'To':name==='cc'?'Cc':'Bcc'} list="mail-recipient-history" value={fields[name]} onChange={event=>field(name,event.target.value)} placeholder="name@example.com"/></label>)}
 <datalist id="mail-recipient-history">{history.map(value=><option key={value} value={value}/>)}</datalist>
 <label>Subject<input aria-label="Subject" value={content.subject} onChange={event=>update({...content,subject:event.target.value.replace(/[\r\n]/g,' ')})}/></label>
 <div className="mail-compose-tools"><button title={content.html===null?'Use rich text':'Use plain text'} aria-label="Toggle rich text" aria-pressed={content.html!==null} onClick={rich}><Pencil size={15}/></button>{content.html!==null&&<><button aria-label="Bold" onMouseDown={event=>event.preventDefault()} onClick={()=>{document.execCommand('bold');richChange();}}><Bold size={15}/></button><button aria-label="Italic" onMouseDown={event=>event.preventDefault()} onClick={()=>{document.execCommand('italic');richChange();}}><Italic size={15}/></button></>}<button aria-label="Attach files" disabled={uploading} onClick={()=>fileInput.current?.click()}><Paperclip size={15}/></button><button aria-label="Insert inline image" disabled={uploading} onClick={()=>imageInput.current?.click()}><Image size={15}/></button><input hidden ref={fileInput} type="file" multiple onChange={event=>void attach(event.target.files,false)}/><input hidden ref={imageInput} type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={event=>void attach(event.target.files,true)}/></div>
 {content.html===null?<textarea aria-label="Message body" className="mail-compose-body" value={content.text} onChange={event=>update({...content,text:event.target.value})}/>:<div ref={editor} role="textbox" aria-label="Rich message body" aria-multiline="true" contentEditable suppressContentEditableWarning className="mail-compose-body" onInput={richChange} onDrop={event=>{event.preventDefault();if(event.dataTransfer.files.length)void attach(event.dataTransfer.files,false);else{document.execCommand('insertText',false,event.dataTransfer.getData('text/plain'));richChange();}}} onPaste={event=>{event.preventDefault();document.execCommand('insertText',false,event.clipboardData.getData('text/plain'));richChange();}}/>}
 {content.attachments.map((part,index)=><div className="mail-compose-attachment" key={part.partId}><FileText size={15}/><span>{part.filename}{part.disposition==='inline'?' (inline image)':''}</span><button aria-label={`Remove ${part.filename}`} onClick={()=>update({...content,attachments:content.attachments.filter((_,at)=>at!==index),html:content.html?.replaceAll(`<img src="cid:${part.contentId}">`,'')??null})}><X size={14}/></button></div>)}
 {(error||saver.error)&&<p role="alert">{error||saver.error}</p>}{saver.error&&<button onClick={()=>onSwitch({...initial,id:crypto.randomUUID(),version:null,content})}>Save as new draft</button>}{invalid&&<p className="mail-compose-hint">Complete the sender and recipient addresses. Your draft is still saved.</p>}
 <footer><button disabled title="Sending will be available when the outbox is connected"><Send size={15}/>Send</button><small>{uploading?'Adding attachment…':'Draft only · Sending is not available yet.'}</small></footer></section>;
}
