/** @jsxImportSource react */
import {useEffect,useRef,useState} from 'react';
import {MessagesSquare} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {attachMailToChat,type MailChatBridge,type MailChatDestination} from './mail-chat';
import type {MailClient,MailMessageView,MailPartView} from './mail-client';
export function MailAttachmentChat({bridge,client,item,part,account}:{bridge:MailChatBridge;client:MailClient;item:MailMessageView;part:MailPartView;account:string}) {
 const [open,setOpen]=useState(false),[workspace,setWorkspace]=useState(''),[session,setSession]=useState(''),[sessions,setSessions]=useState<Array<{id:string;title:string}>>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const active=useRef(new AbortController()),prepared=useRef<MailChatDestination|null>(null),inFlight=useRef(false);
 useEffect(()=>()=>active.current.abort(),[]);
 useEffect(()=>{prepared.current=null;setSession('');setSessions([]);setError('');if(!workspace)return;let current=true;setLoading(true);void bridge.sessions(workspace).then(values=>{if(current)setSessions(values);}).catch(()=>{if(current)setError('Chats are unavailable. Reconnect the workspace and retry.');}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[workspace,bridge]);
 const close=()=>{active.current.abort();setOpen(false);setBusy(false);inFlight.current=false;};
 const copy=async()=>{if(inFlight.current)return;inFlight.current=true;const abort=new AbortController();active.current=abort;setBusy(true);setError('');try{
   const validate=async()=>{const current=await client.check(item,abort.signal);if(current.removed||current.rawReferenceId!==item.rawReferenceId)throw Error('The source email changed or is unavailable. Reopen it before copying.');let after:string|undefined;for(let page=0;page<20;page++){const values=await client.parts(item,abort.signal,after);if(values.items.some(value=>value.kind==='attachment'&&value.partId===part.partId&&value.referenceId===part.referenceId&&value.sha256===part.sha256&&value.bytesAvailable))return;after=values.nextCursor??undefined;if(!after)break;}throw Error('This attachment changed or is unavailable.');};
   await validate();const bytes=await client.bytes(item,part,abort.signal,32*1024*1024);abort.signal.throwIfAborted();
   const destination=prepared.current??await bridge.prepare(workspace,session||null);abort.signal.throwIfAborted();prepared.current=destination;
   if(!part.referenceId||!part.sha256)throw Error('Attachment details are unavailable.');
   await attachMailToChat(destination,new File([bytes],part.filename||'attachment',{type:part.contentType||'application/octet-stream'}),{serverOrigin:client.serverOrigin,accountId:item.accountId,locator:item.locator,accountLabel:account.slice(0,512),subject:item.subject.slice(0,512),filename:(part.filename||'attachment').slice(0,512),referenceId:part.referenceId,sha256:part.sha256},abort.signal,validate);if(!abort.signal.aborted)setOpen(false);
 }catch(cause){if(!abort.signal.aborted)setError((cause instanceof Error?cause.message:'Copy failed.')+' Any completed copy remains in the chosen workspace. Nothing was sent to chat.');}finally{if(!abort.signal.aborted){setBusy(false);inFlight.current=false;}}};
 return <><button aria-label={`Add ${part.filename||'attachment'} to chat`} title="Add attachment to workspace chat" disabled={!part.bytesAvailable} onClick={()=>setOpen(true)}><MessagesSquare size={15}/></button><Dialog open={open} onOpenChange={value=>value?setOpen(true):close()}><DialogContent><DialogHeader><DialogTitle>Add attachment to chat</DialogTitle><DialogDescription>Copy {part.filename||'this attachment'} and its source details to a chosen workspace. The original email stays in Mail.</DialogDescription></DialogHeader><label className="grid gap-2 text-sm">Workspace<select className="lw-field rounded-md border border-input bg-background px-3 py-2" aria-label="Attachment workspace" disabled={busy} value={workspace} onChange={event=>setWorkspace(event.target.value)}><option value="">Choose a workspace</option>{bridge.workspaces.map(value=><option key={value.id} value={value.id}>{value.name}{value.remote?' (remote)':''}</option>)}</select></label><label className="grid gap-2 text-sm">Chat<select className="lw-field rounded-md border border-input bg-background px-3 py-2" aria-label="Attachment chat" disabled={busy||loading||!workspace} value={session} onChange={event=>{prepared.current=null;setSession(event.target.value);}}><option value="">New chat</option>{sessions.map(value=><option key={value.id} value={value.id}>{value.title}</option>)}</select></label><p className="text-xs text-muted-foreground">{bridge.workspaces.find(value=>value.id===workspace)?.remote?'This uploads a copy to the selected remote workspace. ':'This creates a separate workspace file. '}Source account and email details accompany the file. You can review the chat draft before sending it to the configured model. Up to 32 MB per attachment.</p>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Copying attachment…</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={close}>Cancel</Button><Button disabled={!workspace||loading||busy} onClick={()=>void copy()}>Copy and add to draft</Button></div><p className="text-xs text-muted-foreground">Cancelling stops the handoff. A copy already being written may remain in the workspace.</p></DialogContent></Dialog></>;
}
