import {queueOutbox} from './mail-outbox';
import type {SenderIdentity} from '../../../../../server/src/mail/sender-view';
/** @jsxImportSource react */
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { Bold, Italic, Paperclip, Image, Save, X, Send, Pencil, FileText } from 'lucide-react';
import { mailAddressSchema, mailDraftContentSchema, type MailDraftView, type MailDraftSummary } from '../../../../../server/src/mail/local-view';
import { MailClient, type MailAccountView } from './mail-client';
import { addresses, emptyCompose, safeComposeHtml, selectComposeSender, defaultComposeSender, composeTextHtml, type ComposeContent } from './mail-compose-model';
import {recoveryDrafts,type DraftRecovery} from './mail-draft-recovery';
import {MailDraftSync} from './mail-draft-sync';
import { ComposeSaveQueue, draftPage, draftRead, uploadComposeFile, composeAttachmentBytes } from './mail-compose-client';
function editorHtml(element:HTMLDivElement){const copy=element.cloneNode(true);if(!(copy instanceof HTMLDivElement))return '';for(const image of copy.querySelectorAll('img[data-mail-cid]')){image.setAttribute('src','cid:'+image.getAttribute('data-mail-cid'));image.removeAttribute('data-mail-cid');}return copy.innerHTML;}
const recipientFields:('to'|'cc'|'bcc')[]=['to','cc','bcc'];
export type ComposeSelection={account:string;id:string;content:ComposeContent;version:MailDraftView['version']|null;recovery?:Pick<DraftRecovery,'id'|'revision'>};
export function MailDrafts({client,accounts,onOpen,onClose}:{client:MailClient;accounts:MailAccountView[];onOpen:(value:ComposeSelection)=>void;onClose:()=>void}){
 const [recoveries,setRecoveries]=useState<DraftRecovery[]>([]);
 useEffect(()=>{let active=true;void recoveryDrafts().then(values=>{if(active)setRecoveries(values.filter(value=>accounts.some(account=>account.id===value.accountId)));}).catch(()=>{if(active)setError('Device recovery is unavailable. Retry Drafts, or review the account connection in Settings.');});return()=>{active=false;};},[client,accounts]);
 const openRequest=useRef<AbortController|null>(null);
 useLayoutEffect(()=>{const controller=new AbortController();openRequest.current=controller;setItems([]);setError('');return()=>controller.abort();},[client,accounts]);
 async function openDraft(account:string,id:string){const controller=openRequest.current;if(!controller||controller.signal.aborted)return;try{const draft=await draftRead(client,account,id,controller.signal);if(!controller.signal.aborted&&openRequest.current===controller)onOpen({account,id:draft.id,content:draft.content,version:draft.version});}catch(error){if(!controller.signal.aborted&&openRequest.current===controller)setError(String(error));}}
 const [items,setItems]=useState<{account:string;name:string;draft:MailDraftSummary}[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;void(async()=>{const result:typeof items=[];for(const account of accounts){let after:string|undefined;do{const page=await draftPage(client,account.id,after);for(const draft of page.items)result.push({account:account.id,name:account.displayName,draft});after=page.nextCursor??undefined;if(result.length>5000)throw Error('Too many drafts to list.');}while(after);}if(active)setItems(result.sort((a,b)=>b.draft.updatedAt-a.draft.updatedAt));})().catch(error=>{if(active)setError(String(error));});return()=>{active=false;};},[client,accounts]);
 return <section className="mail-composer" aria-label="Saved drafts"><header><h2>Drafts</h2><button aria-label="Close drafts" onClick={()=>{openRequest.current?.abort();onClose();}}><X size={16}/></button></header>{error&&<p role="alert">{error}</p>}{recoveries.map(item=><button className="mail-draft-row" key={'recovery'+item.id} onClick={()=>onOpen({account:item.accountId,id:item.draftId,content:item.content,version:item.version,recovery:{id:item.id,revision:item.revision}})}><strong>Recover: {item.content.subject||'(No subject)'}</strong><small>Unsaved device recovery · {new Date(item.updatedAt).toLocaleString()}</small></button>)}{items.map(item=><button className="mail-draft-row" key={item.account+item.draft.id} onClick={()=>void openDraft(item.account,item.draft.id)}><strong>{item.draft.subject||'(No subject)'}</strong><small>{item.name} · {new Date(item.draft.updatedAt).toLocaleString()}</small></button>)}{!items.length&&!recoveries.length&&!error&&<p>No saved drafts.</p>}</section>;
}
export function MailComposer({client,accounts,initial,onClose,onSwitch,onQueued}:{client:MailClient;accounts:MailAccountView[];initial:ComposeSelection;onClose:()=>void;onSwitch:(value:ComposeSelection)=>void;onQueued?:()=>void}){
 const [content,setContent]=useState(initial.content),[,redraw]=useState(0),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[history,setHistory]=useState<string[]>([]);
 const [sending,setSending]=useState(false);const sendLock=useRef(false);
 const [senders,setSenders]=useState<SenderIdentity[]>([]),[senderError,setSenderError]=useState('');

 const [previews,setPreviews]=useState<Record<string,string>>({});
 const editor=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),imageInput=useRef<HTMLInputElement>(null),mounted=useRef(true);
 const queue=useRef<ComposeSaveQueue|null>(null);if(!queue.current)queue.current=new ComposeSaveQueue(client,initial.account,initial.id,initial.version,()=>{if(mounted.current)redraw(value=>value+1);},initial.recovery);
 const saver=queue.current;
 const current=useRef(content);current.current=content;
 const identity=accounts.find(account=>account.id===initial.account)?.identity;
 const fields=content.editor??{to:content.to.join(', '),cc:content.cc.join(', '),bcc:content.bcc.join(', '),from:content.from??''};
 function update(value:ComposeContent){if(sendLock.current)return;const checked=mailDraftContentSchema.safeParse(value);if(!checked.success){setError('This draft exceeds the 24 KiB text and address limit. Shorten it before saving.');return;}setContent(value);setError('');void saver.save(checked.data);}
 useEffect(()=>{const controller=new AbortController();setSenders([]);setSenderError('');void client.senders(initial.account,controller.signal).then(values=>{if(controller.signal.aborted)return;setSenders(values);if(!initial.version&&!current.current.senderIdentityId){const selected=defaultComposeSender(values,!!current.current.inReplyTo);if(selected){update(selectComposeSender(current.current,selected));}}}).catch(()=>{if(!controller.signal.aborted)setSenderError('Sender identities could not be loaded. Open Mail accounts in Settings to refresh them.');});return()=>controller.abort();},[client,initial.account]);
 useEffect(()=>{mounted.current=true;if(!initial.version||initial.recovery)void saver.save(initial.content);return()=>{mounted.current=false;};},[saver]);
 useEffect(()=>{const unload=(event:BeforeUnloadEvent)=>{if(saver.running||saver.pending||error||uploading){event.preventDefault();event.returnValue='Draft changes are still saving.';}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[saver,error,uploading]);
 useEffect(()=>{let active=true;void(async()=>{const page=await draftPage(client,initial.account);const previous=await Promise.all(page.items.map(item=>draftRead(client,initial.account,item.id)));if(active)setHistory([...new Set(previous.flatMap(item=>[...item.content.to,...item.content.cc,...item.content.bcc]))]);})().catch(()=>{});return()=>{active=false;};},[client,initial.account]);
 useEffect(()=>{if(!editor.current||content.html===null)return;if(editorHtml(editor.current)!==content.html)editor.current.innerHTML=safeComposeHtml(content.html);for(const image of editor.current.querySelectorAll('img')){const cid=image.getAttribute('data-mail-cid')??image.getAttribute('src')?.replace(/^cid:/,'');if(cid&&previews[cid]){image.setAttribute('data-mail-cid',cid);image.src=previews[cid];}}},[content.html,previews]);
 useEffect(()=>{if(!saver.version||saver.running)return;let active=true;const urls:string[]=[];const version=saver.version;void(async()=>{const next:Record<string,string>={};for(const [index,part] of content.attachments.entries()){if(part.disposition!=='inline'||!part.contentId)continue;const bytes=await composeAttachmentBytes(client,initial.account,initial.id,version,index,part.referenceId);if(!active)return;const url=URL.createObjectURL(new Blob([bytes],{type:part.contentType}));urls.push(url);next[part.contentId]=url;}if(active)setPreviews(next);})().catch(()=>{});return()=>{active=false;for(const url of urls)URL.revokeObjectURL(url);};},[client,initial.account,initial.id,saver.version,saver.running,content.attachments]);
 async function close(){await saver.running;if(((saver.pending||saver.error)&&!saver.recovered)||error||uploading){setError('Keep this draft open until all changes have saved. Retry Save when mail is available.');return;}onClose();}
 function field(name:'to'|'cc'|'bcc'|'from',value:string){const next={...fields,[name]:value};update({...content,editor:next,to:addresses(next.to),cc:addresses(next.cc),bcc:addresses(next.bcc),from:mailAddressSchema.safeParse(next.from).success?next.from:null});}
 function rich(){if(content.html===null){update({...content,html:composeTextHtml(content)});}else update({...content,html:null});}
 function richChange(){if(!editor.current)return;const html=safeComposeHtml(editor.current.innerHTML);update({...current.current,html,text:editor.current.innerText});}
 async function attach(files:FileList|null,inline:boolean){if(!files?.length)return;setUploading(true);setError('');try{let next=current.current;for(const file of Array.from(files)){if(next.attachments.reduce((total,part)=>total+(part.bytes??0),0)+file.size>20*1024*1024)throw Error('Attachments must total 20 MiB or less.');if(next.attachments.length>=20)throw Error('A draft can contain at most 20 attachments.');if(inline&&!/^image\/(png|jpeg|gif|webp)$/.test(file.type))throw Error('Use PNG, JPEG, GIF or WebP for inline images.');const part=await uploadComposeFile(client,initial.account,file);next=current.current;if(inline){part.disposition='inline';part.contentId=crypto.randomUUID()+'@legalwork';const div=document.createElement('div');div.textContent=next.text;next={...next,html:(next.html??div.innerHTML.replace(/\n/g,'<br>'))+`<p><img src="cid:${part.contentId}"></p>`};}next={...next,attachments:[...next.attachments,part]};update(next);}}catch(error){setError(error instanceof Error?error.message:'Attachment could not be added.');}finally{setUploading(false);if(fileInput.current)fileInput.current.value='';if(imageInput.current)imageInput.current.value='';}}
 async function send(){if(sendLock.current)return;sendLock.current=true;setSending(true);setError('');try{await saver.running;if(saver.pending||saver.error||!saver.version||error||uploading)throw Error('Save all changes before sending.');await queueOutbox(client,initial.account,{draftId:initial.id,version:saver.version,replayKey:initial.id+':'+saver.version.generation+':'+saver.version.revision});onQueued?onQueued():onClose();}catch(error){setError(error instanceof Error?error.message:'Submission could not be queued. Check Outbox before retrying.');}finally{sendLock.current=false;setSending(false);}}
 const invalid=['to','cc','bcc'].some(name=>{const value=name==='to'?fields.to:name==='cc'?fields.cc:fields.bcc;return value.split(/[,;]/).some(part=>part.trim()&&!addresses(part).length);})||!mailAddressSchema.safeParse(fields.from).success;
 return <section className="mail-composer" aria-label="Compose message"><header><h2>{content.inReplyTo?'Reply':'New message'}</h2><span role="status">{saver.error?(saver.recovered?'Device recovery saved':'Not saved'):saver.running?'Saving…':saver.version?'Saved locally':'New draft'}</span><button title="Save draft" aria-label="Save draft" onClick={()=>update(content)}><Save size={16}/></button><button title="Save and close" aria-label="Close composer" onClick={()=>void close()}><X size={16}/></button></header>
 <fieldset disabled={sending} style={{border:0,padding:0,margin:0,minWidth:0}}>
 <label>Account<select aria-label="Sending account" value={initial.account} disabled={uploading||!!content.attachments.length} onChange={async event=>{const account=event.target.value;await saver.running;if(saver.error||saver.pending){setError('Save this draft before changing accounts.');return;}const selected=accounts.find(item=>item.id===account);const from=selected?.identity?.address??addresses(selected?.displayName??'')[0]??'';onSwitch({account,id:crypto.randomUUID(),version:null,content:{...content,senderIdentityId:null,from:emptyCompose(from).from,editor:{...fields,from}}});}}>{accounts.filter(account=>['gmail','graph','imap'].includes(account.provider)).map(account=><option key={account.id} value={account.id}>{account.displayName} ({account.provider==='graph'?'Microsoft':account.provider==='gmail'?'Google':'IMAP'})</option>)}</select></label>
 <label>From<select aria-label="Sender identity" value={content.senderIdentityId??''} onChange={event=>{const selected=senders.find(value=>value.id===event.target.value&&value.available);if(selected){update(selectComposeSender(content,selected));}}}><option value="">Choose a permitted sender</option>{senders.map(value=><option key={value.id} value={value.id} disabled={!value.available}>{value.address}{!value.available?' (unavailable)':''}</option>)}{content.senderIdentityId&&!senders.some(value=>value.id===content.senderIdentityId)&&<option value={content.senderIdentityId} disabled>{content.from} (unavailable)</option>}</select></label>
 {(senderError||!senders.some(value=>value.available&&value.id===content.senderIdentityId&&value.address===content.from?.toLowerCase()))&&<p role="alert">{senderError||'Choose a permitted sender before publishing or sending this draft. Your saved message is retained.'}</p>}
 {identity&&<p className="mail-compose-hint" role="status">{identity.sendAllowed?`Administrator-confirmed ${identity.sendMode==='send_as'?'Send as':'Send on behalf'} identity. Exchange verifies the actual sender rights when sending.`:'Sending from this mailbox is not authorized in LegalWork. Ask your administrator about Mail.Send.Shared and Exchange sender permission, then review access in Settings.'} Sent Items are saved in the signed-in Microsoft account; Exchange may retain an additional copy.</p>}
 {recipientFields.map(name=><label key={name}>{name==='to'?'To':name==='cc'?'Cc':'Bcc'}<input aria-label={name==='to'?'To':name==='cc'?'Cc':'Bcc'} list="mail-recipient-history" value={fields[name]} onChange={event=>field(name,event.target.value)} placeholder="name@example.com"/></label>)}
 <datalist id="mail-recipient-history">{history.map(value=><option key={value} value={value}/>)}</datalist>
 <label>Subject<input aria-label="Subject" value={content.subject} onChange={event=>update({...content,subject:event.target.value.replace(/[\r\n]/g,' ')})}/></label>
 <div className="mail-compose-tools"><button title={content.html===null?'Use rich text':'Use plain text'} aria-label="Toggle rich text" aria-pressed={content.html!==null} onClick={rich}><Pencil size={15}/></button>{content.html!==null&&<><button aria-label="Bold" onMouseDown={event=>event.preventDefault()} onClick={()=>{document.execCommand('bold');richChange();}}><Bold size={15}/></button><button aria-label="Italic" onMouseDown={event=>event.preventDefault()} onClick={()=>{document.execCommand('italic');richChange();}}><Italic size={15}/></button></>}<button aria-label="Attach files" disabled={uploading} onClick={()=>fileInput.current?.click()}><Paperclip size={15}/></button><button aria-label="Insert inline image" disabled={uploading} onClick={()=>imageInput.current?.click()}><Image size={15}/></button><input hidden ref={fileInput} type="file" multiple onChange={event=>void attach(event.target.files,false)}/><input hidden ref={imageInput} type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={event=>void attach(event.target.files,true)}/></div>
 {content.html===null?<textarea aria-label="Message body" className="mail-compose-body" value={content.text} onChange={event=>update({...content,text:event.target.value})}/>:<div ref={editor} role="textbox" aria-label="Rich message body" aria-multiline="true" contentEditable={!sending} suppressContentEditableWarning className="mail-compose-body" onInput={richChange} onDrop={event=>{event.preventDefault();if(event.dataTransfer.files.length)void attach(event.dataTransfer.files,false);else{document.execCommand('insertText',false,event.dataTransfer.getData('text/plain'));richChange();}}} onPaste={event=>{event.preventDefault();document.execCommand('insertText',false,event.clipboardData.getData('text/plain'));richChange();}}/>}
 {content.attachments.map((part,index)=><div className="mail-compose-attachment" key={part.partId}><FileText size={15}/><span>{part.filename}{part.disposition==='inline'?' (inline image)':''}</span><button aria-label={`Remove ${part.filename}`} onClick={()=>update({...content,attachments:content.attachments.filter((_,at)=>at!==index),html:content.html?.replaceAll(`<img src="cid:${part.contentId}">`,'')??null})}><X size={14}/></button></div>)}
 {saver.recoveryError&&<p role="alert">{saver.recoveryError}</p>}{(error||saver.error)&&<p role="alert">{error||saver.error}</p>}{saver.error&&<button onClick={()=>onSwitch({...initial,id:crypto.randomUUID(),version:null,content})}>Save as new draft</button>}{invalid&&<p className="mail-compose-hint">Complete the sender and recipient addresses. Your draft is still saved.</p>}
 <MailDraftSync client={client} account={initial.account} id={initial.id} version={saver.version} saving={!!saver.running||!!saver.pending} onReload={async()=>{const draft=await draftRead(client,initial.account,initial.id);if(mounted.current&&!saver.pending&&!saver.running){saver.version=draft.version;setContent(draft.content);redraw(value=>value+1);}}} onRemoved={onClose} onCopy={()=>onSwitch({...initial,id:crypto.randomUUID(),version:null,recovery:undefined,content})}/>
 <footer><button disabled={sending||uploading||invalid||!!saver.error||!!error||!content.to.length&&!content.cc.length&&!content.bcc.length||!senders.some(value=>value.available&&value.id===content.senderIdentityId&&value.address===content.from?.toLowerCase())} onClick={()=>void send()}><Send size={15}/>{sending?'Queuing…':'Send'}</button><small>{uploading?'Adding attachment…':'Queues a durable copy on this device. Review status in Outbox.'}</small></footer></fieldset></section>;
}
