import {test} from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {createMailDesktopController} from './mail-desktop.mjs';
const target={accountId:'synthetic',locator:{provider:'gmail',messageId:'new'}};
const item={id:'synthetic',target,title:'Sender',body:'Subject'};
const flush=()=>new Promise(resolve=>setImmediate(resolve));
async function fixture(run){const notices=[],power=new EventEmitter(),calls=[],opened=[];let batch={items:[],suppressed:0},read={removed:false,isRead:false},state='ready';class FakeNotice extends EventEmitter{static isSupported(){return true;}constructor(options){super();this.options=options;notices.push(this);}show(){this.shown=true;}close(){this.closed=true;this.emit('close');}}
const service={status:()=>({state}),setLifecycleSuspended:async value=>{calls.push(value);},pollNotifications:async input=>{calls.push(input);const value=batch;batch={items:[],suppressed:0};return value;},readMessage:async()=>read};const controller=createMailDesktopController({service,Notification:FakeNotice,powerMonitor:power,onOpen:value=>opened.push(value),preferences:{enabled:true,preview:'none',sound:false,paused:false},intervalMs:100000});await flush();try{await run({controller,service,power,notices,calls,opened,batch(value){batch=value;},read(value){read=value;},state(value){state=value;}});}finally{controller.stop();}}
test('private defaults, bounded burst and account recheck before click',()=>fixture(async f=>{f.batch({items:[item,item],suppressed:10});await f.controller.refresh();assert.equal(f.notices.length,1);assert.deepEqual(f.notices[0].options,{title:'12 new mail messages',body:'Open the newest message in LegalWork.',silent:true});f.notices[0].emit('click');await flush();assert.deepEqual(f.opened,[target]);f.read({removed:true});f.notices[0].emit('click');await flush();assert.equal(f.opened.length,1);assert.ok(f.calls.some(call=>call?.preview==='none'));}));
test('late polls cannot expose preview after privacy change, lock, or quit',()=>fixture(async f=>{let resolve;f.service.pollNotifications=()=>new Promise(done=>{resolve=done;});const pending=f.controller.refresh();await flush();f.power.emit('lock-screen');resolve({items:[item],suppressed:0});await pending;assert.equal(f.notices.length,0);f.power.emit('unlock-screen');await flush();f.controller.stop();resolve({items:[item],suppressed:0});await flush();assert.equal(f.notices.length,0);assert.equal(f.power.listenerCount('suspend'),0);}));
test('suspend and persistent user pause fence resume; new epoch on reconnect',()=>fixture(async f=>{const before=f.calls.find(call=>call?.sessionId).sessionId;f.power.emit('suspend');await flush();assert.equal(f.controller.status().state,'suspended');assert.equal(f.calls.at(-1),true);await f.controller.configure({enabled:true,preview:'subject',sound:true,paused:true});f.power.emit('resume');await flush();assert.equal(f.controller.status().state,'paused');assert.equal(f.calls.filter(call=>typeof call==='boolean').at(-1),true);await f.controller.configure({enabled:true,preview:'subject',sound:true,paused:false});await flush();assert.equal(f.calls.filter(call=>typeof call==='boolean').at(-1),false);assert.notEqual(f.calls.filter(call=>call?.sessionId).at(-1).sessionId,before);}));
test('unavailable accounts and read messages never show native previews',()=>fixture(async f=>{f.batch({items:[item],suppressed:0});f.read({removed:false,isRead:true});await f.controller.refresh();assert.equal(f.notices.length,0);f.service.readMessage=async()=>{throw Error('revoked');};f.batch({items:[item],suppressed:0});await f.controller.refresh();assert.equal(f.notices.length,0);f.state('locked');f.batch({items:[item],suppressed:0});await f.controller.refresh();assert.equal(f.notices.length,0);}));
