import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm,writeFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {createMailArtifacts} from './mail-artifacts.mjs';
async function fixture(body){const root=await mkdtemp(join(tmpdir(),'mail-artifact-test-')),bytes=Buffer.alloc(65000,97),sha=createHash('sha256').update(bytes).digest('hex');let bad=false,locked=false,opened='',dialogGate=null,cancelled=false,onContent=null,filename='../file.txt',suggested='';const server=createServer(async(req,res)=>{assert.equal(req.headers['x-legalwork-host-token'],'synthetic');let text='';for await(const chunk of req)text+=chunk;const input=JSON.parse(text);if(locked){res.writeHead(423);res.end();return;}res.setHeader('Content-Type','application/json');if(req.url.endsWith('/parts'))res.end(JSON.stringify({items:[{kind:'attachment',partId:'a',referenceId:'sha256:'+sha,sha256:sha,bytes:bytes.length,bytesAvailable:true,filename}],nextCursor:null}));else{if(onContent)await onContent();const offset=input.request.offset,end=Math.min(bytes.length,offset+input.request.limit);res.end(JSON.stringify({accountId:'a',offset,totalBytes:bytes.length,referenceId:'sha256:'+sha,sha256:sha,data:(bad?Buffer.alloc(end-offset,98):bytes.subarray(offset,end)).toString('base64'),nextOffset:end===bytes.length?null:end}));}});await new Promise(resolve=>server.listen(0,'127.0.0.1',()=>resolve(undefined)));const address=server.address();assert(address && typeof address!=='string');const api=createMailArtifacts({connection:async()=>({running:true,hostToken:'synthetic',baseUrl:`http://127.0.0.1:${address.port}`}),dialog:{showSaveDialog:async options=>{suggested=options.defaultPath;if(dialogGate)await dialogGate;return {canceled:cancelled,filePath:join(root,'selected.txt')};}},shell:{openPath:async path=>{opened=path;return '';}},privateDirectory:async()=>{}});const input={accountId:'a',locator:{provider:'gmail',messageId:'one'},kind:'attachment',partId:'a',referenceId:'sha256:'+sha,operation:'save'};try{await body({api,input,bytes,root,get opened(){return opened;},bad:()=>{bad=true;},lock:()=>{locked=true;},gate:value=>{dialogGate=value;},filename:value=>{filename=value;},get suggested(){return suggested;},cancelDialog:()=>{cancelled=true;},onContent:value=>{onContent=value;}});}finally{await api.close();await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true});}}
test('save and open re-read stored references, verify chunks and confine filenames to a generated path',()=>fixture(async f=>{assert.deepEqual(await f.api.perform(f.input),{saved:true});assert.deepEqual(await readFile(join(f.root,'selected.txt')),f.bytes);await f.api.perform({...f.input,operation:'open'});assert.match(f.opened,/legalwork-mail-export-/);assert.equal(f.opened.endsWith('.._file.txt'),true);assert.deepEqual(await readFile(f.opened),f.bytes);await f.api.close();await assert.rejects(readFile(f.opened));}));
test('corrupt bytes and locked accounts cannot publish attachments',()=>fixture(async f=>{f.bad();await assert.rejects(f.api.perform(f.input));await assert.rejects(readFile(join(f.root,'selected.txt')));f.lock();await assert.rejects(f.api.perform({...f.input,operation:'open'}));assert.equal(f.opened,'');}));
test('account-switch cancellation fences a late save dialog, and message-supplied destination is rejected',()=>fixture(async f=>{let release=()=>{};f.gate(new Promise(resolve=>{release=()=>resolve(undefined);}));const pending=f.api.perform(f.input);await new Promise(resolve=>setTimeout(resolve,30));f.api.cancel();release();await assert.rejects(pending);await assert.rejects(readFile(join(f.root,'selected.txt')));await assert.rejects(f.api.perform({...f.input,destination:'/untrusted'}));}));

test('offline archive locators save verified originals and attachments without provider credentials',()=>fixture(async f=>{assert.deepEqual(await f.api.perform({...f.input,locator:{provider:'archive',namespace:'import',entryId:'one'}}),{saved:true});assert.deepEqual(await readFile(join(f.root,'selected.txt')),f.bytes);}));

test('native cancellation preserves an existing selected file and creates no publication',()=>fixture(async f=>{await writeFile(join(f.root,'selected.txt'),'existing');f.cancelDialog();assert.deepEqual(await f.api.perform(f.input),{cancelled:true});assert.equal(await readFile(join(f.root,'selected.txt'),'utf8'),'existing');assert.deepEqual(await readdir(f.root),['selected.txt']);}));
test('native replacement publishes verified bytes only after download and rejects a changed destination',()=>fixture(async f=>{const target=join(f.root,'selected.txt');await writeFile(target,'existing');f.onContent(async()=>{assert.equal(await readFile(target,'utf8'),'existing');});await f.api.perform(f.input);assert.deepEqual(await readFile(target),f.bytes);let first=true;f.onContent(async()=>{if(first){first=false;await writeFile(target,'newer user file');}});await assert.rejects(f.api.perform(f.input));assert.equal(await readFile(target,'utf8'),'newer user file');assert.deepEqual(await readdir(f.root),['selected.txt']);}));

test('native Unicode names retain their extension within portable filesystem byte limits',()=>fixture(async f=>{f.filename('秘密😀'.repeat(100)+'.pdf');await f.api.perform(f.input);assert(Buffer.byteLength(f.suggested)<=160);assert(f.suggested.endsWith('.pdf'));assert.deepEqual(await readFile(join(f.root,'selected.txt')),f.bytes);}));
