/** @jsxImportSource react */
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {MailClient,type MailAccountView} from '../../mail/mail-client';
import {smtpStatus,configureSmtp,removeSmtp} from '../../mail/mail-outbox';
import {smtpConfigureSchema,type SmtpStatus} from '../../../../../../server/src/mail/outbox-view';
export function MailSmtpView({client,accounts}:{client:MailClient;accounts:MailAccountView[]}){return <section className="space-y-3" aria-label="Outgoing SMTP"><h3 className="text-sm font-medium">Outgoing SMTP</h3><p className="text-xs text-muted-foreground">Google and Microsoft use their connected accounts. IMAP accounts need separate outgoing settings. Passwords are saved in encrypted mail storage on this device.</p>{accounts.filter(account=>account.provider==='imap').map(account=><SmtpAccount key={account.id} client={client} account={account}/>)}</section>;}
function SmtpAccount({client,account}:{client:MailClient;account:MailAccountView}){
 const [status,setStatus]=useState<SmtpStatus>(),[host,setHost]=useState(''),[port,setPort]=useState('465'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[security,setSecurity]=useState<'tls'|'starttls'>('tls'),[sentCopy,setSentCopy]=useState<'provider'|'append'>('append'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();void smtpStatus(client,account.id,controller.signal).then(value=>{if(controller.signal.aborted)return;setStatus(value);if(value.settings){setHost(value.settings.host);setPort(String(value.settings.port));setUsername(value.settings.username);setSecurity(value.settings.security);setSentCopy(value.settings.sentCopy);}}).catch(()=>{if(!controller.signal.aborted)setError('Outgoing settings could not be loaded.');});return()=>controller.abort();},[client,account.id]);
 async function save(){const input=smtpConfigureSchema.safeParse({host,port:Number(port),username,password,security,sentCopy});if(!input.success){setError('Enter the outgoing host, port, username and password.');return;}setBusy(true);setError('');try{setStatus(await configureSmtp(client,account.id,input.data));setPassword('');}catch{setError('Outgoing settings could not be saved. Check the account connection.');}finally{setBusy(false);}}
 return <fieldset disabled={busy} className="space-y-2 rounded border p-3"><legend className="px-1 text-sm">{account.displayName}</legend><p className="text-xs text-muted-foreground">{status?.configured?(status.current?'Saved. Authentication is checked when sending.':'Reconnect changed this account. Enter outgoing credentials again.'):'Not configured.'}</p><label className="block text-xs">SMTP host<input aria-label={`SMTP host for ${account.id}`} className="w-full rounded border bg-background p-2" value={host} onChange={event=>setHost(event.target.value)}/></label><label className="block text-xs">Port<input aria-label={`SMTP port for ${account.id}`} type="number" min="1" max="65535" className="w-full rounded border bg-background p-2" value={port} onChange={event=>setPort(event.target.value)}/></label><label className="block text-xs">Encryption<select aria-label={`SMTP encryption for ${account.id}`} className="w-full rounded border bg-background p-2" value={security} onChange={event=>{const value=event.target.value==='tls'?'tls':'starttls';setSecurity(value);setPort(value==='tls'?'465':'587');}}><option value="tls">TLS from connection (usually 465)</option><option value="starttls">Required STARTTLS (usually 587)</option></select></label><label className="block text-xs">Username<input autoComplete="username" className="w-full rounded border bg-background p-2" value={username} onChange={event=>setUsername(event.target.value)}/></label><label className="block text-xs">Password or app password<input type="password" autoComplete="new-password" className="w-full rounded border bg-background p-2" value={password} onChange={event=>setPassword(event.target.value)}/></label><label className="block text-xs">Sent copy<select className="w-full rounded border bg-background p-2" value={sentCopy} onChange={event=>setSentCopy(event.target.value==='provider'?'provider':'append')}><option value="append">LegalWork appends to the IMAP Sent folder</option><option value="provider">My outgoing provider automatically saves Sent mail</option></select></label><p className="text-xs text-muted-foreground">Choose provider copies only when your provider documents this behavior. SMTP acceptance does not confirm delivery; rejected recipients and uncertain outcomes remain in Outbox.</p><Button variant="outline" onClick={()=>void save()}>Save outgoing settings</Button>{status?.configured&&<Button variant="outline" onClick={()=>{setBusy(true);void removeSmtp(client,account.id).then(value=>{setStatus(value);setPassword('');}).catch(()=>setError('Outgoing settings could not be removed.')).finally(()=>setBusy(false));}}>Remove outgoing credentials</Button>}{error&&<p role="alert">{error}</p>}</fieldset>;
}
