import {Input} from '@/components/ui/input';
import {MailSettingsSelect,MailSettingsSection} from './mail-settings-controls';
/** @jsxImportSource react */
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {Button} from '@/components/ui/button';
import {portabilityStatusSchema,type PortabilityStatus} from '../../../../../../server/src/mail/portability-view';
import type {MailAccountView} from '../../mail/mail-client';
export function MailPortabilityView({accounts,onChanged}:{accounts:MailAccountView[];onChanged:()=>void}){
 const native=window.__LEGALWORK_ELECTRON__?.mailPortability;
 const [jobs,setJobs]=useState<PortabilityStatus[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[format,setFormat]=useState<'eml'|'mboxrd'|'bundle'>('eml'),[exportFormat,setExportFormat]=useState<'eml'|'mboxrd'>('eml'),[account,setAccount]=useState('');
 useEffect(()=>{if(!native)return;let active=true,pending=false;const poll=async()=>{if(pending)return;pending=true;try{const value=z.array(portabilityStatusSchema).max(100).parse(await native({operation:'list'}));if(active)setJobs(value);}catch{if(active)setError('Import and export status is unavailable. Retry when mail is open.');}finally{pending=false;}};void poll();const timer=setInterval(()=>void poll(),1000);return()=>{active=false;clearInterval(timer);};},[native]);
 async function run(operation:Parameters<NonNullable<typeof native>>[0]){if(!native)return;setBusy(true);setError('');try{setJobs(z.array(portabilityStatusSchema).max(100).parse(await native(operation)));onChanged();}catch{setError('The operation could not start. Check the selected archive and available disk space, then retry.');}finally{setBusy(false);}}
 const [abandon,setAbandon]=useState(''),[confirmation,setConfirmation]=useState('');
 if(!native)return <p className="text-sm text-muted-foreground">Mail import and export are available in the desktop app.</p>;
 const running=jobs.some(job=>job.state==='running');
 return <MailSettingsSection title="Import and export mail">
  <p className="text-sm text-muted-foreground">Imported mail stays in a separate local archive. Read and search it offline; it is never uploaded to a connected account.</p>
  <div className="flex flex-wrap items-center gap-2"><label>Import format <MailSettingsSelect aria-label="Import format" value={format} onChange={value =>setFormat(z.enum(['eml','mboxrd','bundle']).parse(value))}><option value="eml">Folder of EML files</option><option value="mboxrd">MBOX (mboxrd)</option><option value="bundle">LegalWork portable archive</option></MailSettingsSelect></label><Button variant="outline" disabled={busy||running} onClick={()=>void run({operation:'import',format})}>Choose import…</Button></div>
  <div className="flex flex-wrap items-center gap-2"><label>Export account <MailSettingsSelect aria-label="Export account" value={account||accounts[0]?.id||''} onChange={value =>setAccount(value)}>{accounts.map(value=><option key={value.id} value={value.id}>{value.displayName}</option>)}</MailSettingsSelect></label><label>Export format <MailSettingsSelect aria-label="Export format" value={exportFormat} onChange={value =>setExportFormat(z.enum(['eml','mboxrd']).parse(value))}><option value="eml">EML with manifest</option><option value="mboxrd">MBOX with manifest</option></MailSettingsSelect></label><Button variant="outline" disabled={busy||running||!accounts.length} onClick={()=>void run({operation:'export',format:exportFormat,accountId:account||accounts[0].id})}>Choose export folder…</Button></div>
  <p className="text-xs text-muted-foreground">Portable exports contain readable mail and attachments. Choose a protected destination. Keep the manifest with the exported files to preserve original bytes, dates, folders and labels.</p>
  {error&&<p role="alert">{error}</p>}
  {jobs.map(job=><div key={job.id} role="status" className="rounded border p-3 text-sm"><strong>{job.label}</strong><p>{job.direction==='import'?'Import':'Export'}: {job.state} · {job.completed.toLocaleString()} messages · {(job.bytes/1048576).toFixed(1)} MiB{job.failed?` · ${job.failed} need attention`:''}</p>{job.restored&&<p>This restored checkpoint is quarantined. Start a new import or export with a fresh file selection; existing archive messages remain available.</p>}{job.error&&<p>{job.error==='source_changed'?'The source changed. Restore the original source before resuming, or start a separate import.':job.error==='content_unavailable'?'Some originals or readable projections are unavailable. Stored originals remain accessible; this archive is incomplete.':job.error==='interrupted'?'The app stopped before this operation finished. Resume from its saved checkpoint.':'The archive could not be processed. Check its format, integrity and available disk space.'}</p>}{job.state==='running'?<Button variant="outline" disabled={busy} onClick={()=>void run({operation:'pause',id:job.id})}>Pause</Button>:['paused','interrupted','attention','ready'].includes(job.state)&&<Button variant="outline" disabled={busy||running||job.restored} onClick={()=>void run({operation:'resume',id:job.id})}>Resume</Button>}{job.state!=='running'&&<Button variant="ghost" disabled={busy||running} onClick={()=>{setAbandon(job.id);setConfirmation('');}}>Abandon checkpoint…</Button>}{abandon===job.id&&<div><p>This removes the saved checkpoint only. Imported messages and exported files remain. Type ABANDON CHECKPOINT to confirm.</p><Input aria-label="Abandon checkpoint confirmation" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/><Button disabled={busy||running||confirmation!=='ABANDON CHECKPOINT'} onClick={()=>void run({operation:'abandon',id:job.id,confirmation:'ABANDON CHECKPOINT'})}>Confirm abandonment</Button></div>}{job.direction==='import'&&job.completed>0&&<Button variant="ghost" onClick={()=>{window.location.hash='/mail';}}>Open mail</Button>}</div>)}
  <details className="text-sm"><summary>Outlook PST and Microsoft archive mail</summary><p>Convert PST files to a folder of EML messages using a supported local converter before importing. A PST is not an EML or MBOX file. Outlook must be installed for Thunderbird’s Outlook import; the PST alone is insufficient.</p><p>For Microsoft 365 archive mail, an authorized administrator can export the mailbox through Microsoft Purview eDiscovery, keeping source folders and the items report. Primary and associated archive mailboxes can be combined in the exported PST. Convert locally and compare counts and attachments before importing.</p><p><a href="https://support.mozilla.org/en-US/kb/thunderbird-import" target="_blank" rel="noreferrer">Thunderbird prerequisites</a> · <a href="https://www.five-ten-sg.com/libpst/rn01re01.html" target="_blank" rel="noreferrer">PST to EML converter</a> · <a href="https://learn.microsoft.com/en-us/purview/edisc-search-export" target="_blank" rel="noreferrer">Microsoft export procedure</a></p></details>
 </MailSettingsSection>;
}
