import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {MailSettingsSelect,MailSettingsSection} from './mail-settings-controls';
/** @jsxImportSource react */
import {useEffect,useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {retentionPreviewSchema,retentionResultSchema,retentionSettingsSchema,type RetentionPreview,type RetentionScope} from '../../../../../../server/src/mail/retention-view';
import {mailMaintenanceResponseSchema,type MailMaintenanceReport} from '../../../../../../server/src/mail/maintenance-view';
import {MailClient,type MailAccountView} from '../../mail/mail-client';
import {mailDesktopSettingsSchema} from '../../mail/mail-desktop';
export function MailRetentionView({client,accounts,onChanged}:{client:MailClient;accounts:MailAccountView[];onChanged:()=>void}){return <MailSettingsSection title="Retention and encrypted recovery"><p className="text-xs text-muted-foreground">Provider deletion and disconnect keep local copies. Disconnect removes this device’s sign-in credentials and locks its stored mail; it does not delete provider mail or revoke every provider session. Local deletion is a separate action below.</p>{accounts.map(account=><AccountRetention key={account.id} account={account} client={client} onChanged={onChanged}/>)}<MailBackupRecovery client={client}/></MailSettingsSection>;}
const blockers:Record<RetentionPreview['blockers'][number],string>={connected:'Disconnect this account before removing all local records.',active_work:'Stop or cancel active sends, draft synchronization, extraction, or file jobs first.',retained_records:'Retained originals protect this account and its saved bytes.',shared_children:'Remove or retain the linked shared mailboxes before removing this account.',unfinished_import:'Abandon the stopped import/export checkpoint explicitly before removing this account.',archive_not_selected:'Select the archive explicitly to include its messages.'};
function AccountRetention({client,account,onChanged}:{client:MailClient;account:MailAccountView;onChanged:()=>void}){
 const [days,setDays]=useState(''),[scope,setScope]=useState<RetentionScope['scope']>('removed'),[includeArchive,setIncludeArchive]=useState(false),[preview,setPreview]=useState<RetentionPreview|null>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const base=`/accounts/${encodeURIComponent(account.id)}/retention`;
 useEffect(()=>{const c=new AbortController();void client.request(base+'/settings',retentionSettingsSchema,c.signal).then(value=>{if(!c.signal.aborted)setDays(value.removedDays===null?'':String(value.removedDays));}).catch(()=>{});return()=>c.abort();},[client,base]);
 async function review(){setBusy(true);setMessage('');setPreview(null);setConfirmation('');try{const removedDays=days===''?null:Number(days);retentionSettingsSchema.parse({removedDays});await client.request(base+'/settings',retentionSettingsSchema,new AbortController().signal,{removedDays});if(scope==='removed'&&removedDays===null){setMessage('Copies are retained indefinitely. Set an age before reviewing provider-deleted copies.');return;}setPreview(await client.request(base+'/preview',retentionPreviewSchema,new AbortController().signal,{scope,before:scope==='removed'?new Date(Date.now()-Number(removedDays)*86400000).toISOString():null,includeArchive},false,90000));}catch{setMessage('Unable to prepare deletion. Enter a whole number of days from 1 to 36500 and retry.');}finally{setBusy(false);}}
 async function apply(){if(!preview)return;setBusy(true);setMessage('');try{const bridge=window.__LEGALWORK_ELECTRON__;if(!bridge?.mailDesktopSettings||!bridge.mailDesktopSettingsSave)throw Error('desktop_required');const current=mailDesktopSettingsSchema.parse(await bridge.mailDesktopSettings());await bridge.mailDesktopSettingsSave({...current.preferences,paused:true});const result=await client.request(base+'/apply',retentionResultSchema,new AbortController().signal,{token:preview.token,confirmation},false,90000);setPreview(null);setConfirmation('');setMessage(`Removed ${result.messages} local messages and ${result.references} content references. Mail remains paused; resume it in background settings when ready.`);onChanged();}catch{setPreview(null);setMessage('Nothing was confirmed deleted. Mail may remain paused. Resolve blockers and review a fresh preview before retrying.');}finally{setBusy(false);}}
 return <div className="space-y-4 rounded-xl border border-subtle p-4"><strong className="text-sm">{account.displayName}</strong><label className="grid grid-cols-[1fr_130px] items-center gap-4 text-sm">Keep provider-deleted copies for days<Input aria-label={`Retention days for ${account.displayName}`} type="number" min="1" max="36500" placeholder="Indefinitely" value={days} onChange={e=>{setDays(e.target.value);setPreview(null);}}/></label><p className="text-xs text-muted-foreground">Blank keeps copies indefinitely. This sets the age used by manual cleanup; no automatic deletion runs.</p><label className="block space-y-2 text-sm">Deletion scope <MailSettingsSelect aria-label={`Deletion scope for ${account.displayName}`} value={scope} onChange={value=>{setScope(retentionPreviewSchema.shape.scope.shape.scope.parse(value));setPreview(null);}}><option value="removed">Provider-deleted copies past this age</option><option value="mirror">All local mirror messages</option><option value="account">Disconnected account and local history</option></MailSettingsSelect></label>{account.provider==='archive'&&<label className="block text-xs"><Checkbox  checked={includeArchive} onCheckedChange={checked =>{setIncludeArchive(checked);setPreview(null);}}/>Include this offline archive explicitly</label>}<Button variant="outline" size="sm" disabled={busy} onClick={()=>void review()}>Save retention and review deletion</Button>{preview&&<div className="space-y-2 text-xs" role="status"><p>{preview.messages} messages selected · {preview.references} deletable references · {(preview.bytes/1048576).toFixed(2)} MiB · {preview.protectedReferences} protected references · {preview.retainedRecords} retained originals.</p>{scope==='account'?<p>This removes {preview.drafts} local draft records and {preview.submissions} submission-history records, including accepted or uncertain evidence. Provider mail and external files in connected storage are unaffected.</p>:<p>Drafts, submission history and independently retained originals remain. Connected mail may download again after sync resumes.</p>}{preview.blockers.map(value=><p key={value}>{blockers[value]}</p>)}{!preview.blockers.length&&<><p>Applying pauses background mail. Type DELETE LOCAL COPIES to confirm this exact preview.</p><Input aria-label={`Deletion confirmation for ${account.displayName}`} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><Button variant="destructive" size="sm" disabled={busy||confirmation!=='DELETE LOCAL COPIES'} onClick={()=>void apply()}>Delete selected local copies</Button></>}</div>}{message&&<p className="text-xs" role="alert">{message}</p>}</div>;
}
export function MailBackupRecovery({client}:{client:MailClient}){
 const active=useRef<AbortController|null>(null);useEffect(()=>()=>active.current?.abort(),[]);
 const [passphrase,setPassphrase]=useState(''),[repeat,setRepeat]=useState(''),[restoreConfirmed,setRestoreConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[report,setReport]=useState<MailMaintenanceReport|null>(null);
 async function perform(operation:'backup'|'restore'){setBusy(true);setMessage('');setReport(null);const controller=new AbortController();active.current=controller;const secret=passphrase;setPassphrase('');setRepeat('');setRestoreConfirmed(false);try{const value=await client.request('/security/'+operation,mailMaintenanceResponseSchema,controller.signal,{passphrase:secret},false,null);setReport(value.report);setMessage(operation==='backup'?'Encrypted backup verified. Mail is closed; reopen Mail when ready.':'Restored and verified offline. Provider credentials were removed. Old sends, draft mappings and file/filing jobs are quarantined. Reconnect explicitly before creating fresh provider actions.');}catch{setMessage('Recovery operation failed or was cancelled. The active generation was not replaced unless verification completed. Keep the source backup and recovery passphrase; reopen Mail to check its state.');}finally{if(active.current===controller)active.current=null;setBusy(false);}}
 return <div className="space-y-2"><h4 className="text-sm font-medium">Encrypted backup and restore</h4><p className="text-xs text-muted-foreground">A backup covers this device’s stored mail, drafts, submission history and locally retained originals and save receipts. It does not back up external files in any connected storage system or mail that has not downloaded. Keep the recovery passphrase separately; LegalWork cannot reset it. Backup and restore close Mail while a consistent encrypted copy is verified.</p><label className="block text-xs">Recovery passphrase<Input aria-label="Mail recovery passphrase" type="password" autoComplete="new-password" value={passphrase} onChange={e=>setPassphrase(e.target.value)} maxLength={1024}/></label><label className="block text-xs">Confirm passphrase for new backup<Input aria-label="Confirm mail recovery passphrase" type="password" autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)} maxLength={1024}/></label><Button variant="outline" disabled={busy||passphrase.length<16||passphrase!==repeat} onClick={()=>void perform('backup')}>Choose backup destination…</Button><label className="block text-xs"><Checkbox  checked={restoreConfirmed} onCheckedChange={checked =>setRestoreConfirmed(checked)}/>Replace the active local mail generation with the selected backup. The previous generation remains on this device; restore does not merge messages or erase older copies.</label><Button variant="outline" disabled={busy||passphrase.length<16||!restoreConfirmed} onClick={()=>void perform('restore')}>Choose backup to restore…</Button>{busy&&<div><p role="status">Verifying encrypted mail. Large stores can take up to 20 minutes; keep this page open.</p><Button variant="outline" onClick={()=>active.current?.abort()}>Cancel recovery operation</Button></div>}{message&&<p className="text-xs" role="status">{message}</p>}{report&&<p className="text-xs">Verified {report.accounts} accounts, {report.messages} messages, {report.references} content references ({(report.bytes/1048576).toFixed(2)} MiB), {report.retainedRecords} retained originals and {report.retainedParts} retained parts. {report.incompleteParts} parts were not stored in this backup. Schema {report.schemaVersion}.</p>}</div>;
}
