import {Checkbox} from '@/components/ui/checkbox';
import {MailSettingsSelect,MailSettingsSection} from './mail-settings-controls';
/** @jsxImportSource react */
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {Button} from '@/components/ui/button';
import {agentGrantSchema,agentProposalSchema,agentPermissionSchema,type AgentGrant} from '../../../../../../server/src/mail/agent-view';
import {mailDraftViewSchema} from '../../../../../../server/src/mail/local-view';
import {mailMessageViewSchema} from '../../../../../../server/src/mail/read-view';
import {MailClient,type MailAccountView} from '../../mail/mail-client';
const listing=z.object({grants:z.array(agentGrantSchema),proposals:z.array(agentProposalSchema),workspaces:z.array(z.object({id:z.string(),name:z.string()}))});
const matterPage=z.object({results:z.array(z.object({id:z.string(),title:z.string()})),next_offset:z.number().nullable()});
const review=z.object({proposal:agentProposalSchema,grant:agentGrantSchema,detail:z.unknown()});
const labels={search:'Search',read:'Read messages',attachments:'Read attachments',export:'Export original bytes',draft:'Create drafts',propose_send:'Propose sending',propose_delete:'Propose moving to Trash'};
export function MailAgentAccessView({client,accounts}:{client:MailClient;accounts:MailAccountView[]}){
 const [data,setData]=useState<z.infer<typeof listing>>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[account,setAccount]=useState(''),[workspace,setWorkspace]=useState(''),[matter,setMatter]=useState(''),[matters,setMatters]=useState<Array<{id:string;title:string}>>([]),[nextMatter,setNextMatter]=useState<number|null>(null),[permissions,setPermissions]=useState<AgentGrant['permissions']>(['search','read']),[confirmed,setConfirmed]=useState(false),[selected,setSelected]=useState<z.infer<typeof review>>();
 useEffect(()=>{const controller=new AbortController();void client.request('/agent-access',listing,controller.signal,{action:'list'}).then(setData).catch(()=>{if(!controller.signal.aborted)setError('Agent access could not be loaded.');});return()=>controller.abort();},[client,revision]);
 useEffect(()=>{setMatters([]);setNextMatter(null);if(!workspace)return;const controller=new AbortController();void client.request('/agent-access',matterPage,controller.signal,{action:'matters',workspaceId:workspace,offset:0}).then(page=>{if(!controller.signal.aborted){setMatters(page.results);setNextMatter(page.next_offset);}}).catch(()=>{});return()=>controller.abort();},[client,workspace]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();setRevision(value=>value+1);}catch{setError('Access changed or the proposal is stale. Refresh and review again.');}finally{setBusy(false);}}
 const selectedAccount=accounts.find(value=>value.id===account),available=agentPermissionSchema.options.filter(value=>selectedAccount?.provider!=='archive'||['search','read','attachments','export'].includes(value));
 return <MailSettingsSection title="Agent mail access"><p className="text-xs text-muted-foreground">Accounts are private until you grant a workspace access. Mail returned to an agent enters that task and may be processed by its configured remote model. Email content cannot grant access. Sending and moving messages to Trash always require your separate review below.</p>
 <fieldset disabled={busy} className="space-y-4"><MailSettingsSelect aria-label="Agent mail account" value={account} onChange={value =>{setAccount(value);setPermissions(['search','read']);setConfirmed(false);}}><option value="">Choose account</option>{accounts.map(value=><option key={value.id} value={value.id}>{value.displayName}</option>)}</MailSettingsSelect><MailSettingsSelect aria-label="Agent workspace" value={workspace} onChange={value =>{setWorkspace(value);setMatter('');setConfirmed(false);}}><option value="">Choose workspace</option>{data?.workspaces.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</MailSettingsSelect><label className="block text-xs">Mail scope<MailSettingsSelect aria-label="Agent matter" value={matter} onChange={value =>{setMatter(value);setConfirmed(false);}} className="block w-full rounded border bg-background p-2"><option value="">Whole account in this workspace</option>{matters.map(value=><option key={value.id} value={value.id}>{value.title}</option>)}</MailSettingsSelect></label>{nextMatter!==null&&<Button variant="outline" onClick={()=>void run(async()=>{const page=await client.request('/agent-access',matterPage,new AbortController().signal,{action:'matters',workspaceId:workspace,offset:nextMatter});setMatters(values=>[...values,...page.results]);setNextMatter(page.next_offset);})}>Load more matters</Button>}<p className="text-xs">Matter scope includes only matching originals with current backend matter permission. Saving a file to connected storage does not grant matter access.</p><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{available.map(permission=><label className="flex items-center gap-2 text-sm" key={permission}><Checkbox  disabled={permission==='propose_send'&&!permissions.includes('draft')} checked={permissions.includes(permission)} onCheckedChange={checked =>{setPermissions(values=>checked?[...values,permission]:values.filter(value=>value!==permission&&(permission!=='draft'||value!=='propose_send')));setConfirmed(false);}}/> {labels[permission]}</label>)}</div><p className="text-xs text-muted-foreground">Proposing a send requires draft access. Select draft access explicitly to enable it.</p><label className="flex items-start gap-2 rounded-xl bg-sunken p-3 text-xs leading-relaxed"><Checkbox  checked={confirmed} onCheckedChange={checked =>setConfirmed(checked)}/> I authorize this workspace to process the selected mail scope for 30 days, including with its configured model.</label><Button variant="outline" disabled={!confirmed||!account||!workspace||!permissions.length} onClick={()=>void run(async()=>{await client.request('/agent-access',z.unknown(),new AbortController().signal,{action:'create',input:{accountId:account,workspaceId:workspace,matterId:matter.trim()||null,permissions,expiresAt:Date.now()+30*86400000}});setConfirmed(false);})}>Grant access</Button></fieldset>
 <Button variant="outline" disabled={busy} onClick={()=>setRevision(value=>value+1)}>Refresh access and requests</Button>
 {data?.grants.map(grant=><div className="flex items-center justify-between gap-2 text-xs" key={grant.id}><span>{accounts.find(value=>value.id===grant.accountId)?.displayName??grant.accountId} · {data.workspaces.find(value=>value.id===grant.workspaceId)?.name??grant.workspaceId} · {grant.matterId??'Whole account'} · {grant.state==='active'&&grant.expiresAt<=Date.now()?'expired':grant.state} · {grant.permissions.map(value=>labels[value]).join(', ')} · Until {new Date(grant.expiresAt).toLocaleDateString()}</span>{grant.state==='active'&&<Button variant="outline" disabled={busy} onClick={()=>void run(()=>client.request('/agent-access',z.unknown(),new AbortController().signal,{action:'revoke',id:grant.id}))}>Revoke</Button>}</div>)}
 {data?.proposals.filter(value=>value.state==='pending').map(proposal=><div className="flex items-center justify-between text-xs" key={proposal.id}><span>{proposal.payload.kind==='send'?'Send request':'Move to Trash request'} · Task {proposal.sessionId}</span><Button variant="outline" disabled={busy} onClick={()=>void run(async()=>setSelected(await client.request('/agent-access',review,new AbortController().signal,{action:'review',id:proposal.id})))}>Review request</Button><Button variant="outline" aria-label={`Reject request from ${proposal.sessionId}`} disabled={busy} onClick={()=>void run(()=>client.request('/agent-access',z.unknown(),new AbortController().signal,{action:'decide',id:proposal.id,approve:false}))}>Reject</Button></div>)}
 {selected&&<ApprovalReview key={selected.proposal.id} value={selected} busy={busy} decide={approve=>void run(async()=>{await client.request('/agent-access',z.unknown(),new AbortController().signal,{action:'decide',id:selected.proposal.id,approve});setSelected(undefined);})}/>}
 {error&&<p role="alert" className="text-xs">{error}</p>}</MailSettingsSection>;
}
function ApprovalReview({value,busy,decide}:{value:z.infer<typeof review>;busy:boolean;decide:(approve:boolean)=>void}){
 const [confirmed,setConfirmed]=useState(false);
 const draft=mailDraftViewSchema.safeParse(value.detail),message=mailMessageViewSchema.safeParse(value.detail);
 return <fieldset className="space-y-3 rounded-xl border border-subtle bg-background p-4" disabled={busy}><legend>Review exact {value.proposal.payload.kind==='send'?'send':'Trash'} request</legend><p className="text-xs">Workspace {value.grant.workspaceId} · Account {value.grant.accountId} · Task {value.proposal.sessionId} · Expires {new Date(value.proposal.expiresAt).toLocaleString()}</p>{draft.success?<div className="space-y-2 text-xs"><p><strong>From:</strong> {draft.data.content.from}</p><p><strong>To:</strong> {draft.data.content.to.join(', ')}</p><p><strong>Cc:</strong> {draft.data.content.cc.join(', ')||'None'}</p><p><strong>Bcc:</strong> {draft.data.content.bcc.join(', ')||'None'}</p><p><strong>Subject:</strong> {draft.data.content.subject}</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap">{draft.data.content.text}</pre><p><strong>Attachments:</strong> {draft.data.content.attachments.map(part=>part.filename+' ('+(part.bytes??'unknown')+' bytes)').join(', ')||'None'}</p></div>:message.success?<div className="text-xs"><p><strong>Message:</strong> {message.data.subject}</p><p><strong>Message ID:</strong> {message.data.rfcMessageId??message.data.key}</p><p>This message will move to the provider’s Trash. No permanent deletion is requested.</p></div>:<p role="alert">Request details are unavailable.</p>}<label className="flex items-start gap-2 rounded-xl bg-sunken p-3 text-xs leading-relaxed"><Checkbox  checked={confirmed} onCheckedChange={checked =>setConfirmed(checked)}/> I reviewed the exact contents and authorize this action.</label><Button disabled={!confirmed||!draft.success&&!message.success} onClick={()=>decide(true)}>{value.proposal.payload.kind==='send'?'Approve send':'Approve move to Trash'}</Button><Button variant="outline" onClick={()=>decide(false)}>Reject</Button></fieldset>;
}
