#!/usr/bin/env bash
# Dedicated E2B host only. Secrets are generated by Embed on its data disk.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
runtime_commit=79fcdf59b093eddda444a76932a4d140850b71c6
base_url="https://raw.githubusercontent.com/e2b-dev/runtime/$runtime_commit/embed/compose"
device=/dev/disk/by-id/google-e2b-data
for attempt in $(seq 1 60); do
  [ -b "$device" ] && break
  sleep 2
done
[ -b "$device" ]
if ! blkid "$device" >/dev/null; then
  mkfs.ext4 -F -L e2b-data "$device"
fi
install -d /data
if ! mountpoint -q /data; then mount "$device" /data; fi
if ! grep -q '^LABEL=e2b-data ' /etc/fstab; then
  echo 'LABEL=e2b-data /data ext4 defaults 0 2' >> /etc/fstab
fi

# Keep databases, generated keys, templates, snapshots and controller state
# together. A MIG repair replaces the boot disk and reattaches this disk.
for path in /opt/e2b /var/lib/docker /var/lib/containerd /var/lib/e2b \
            /fc-versions /fc-kernels /fc-busybox /fc-envd /fc-vm /orchestrator; do
  source="/data/host$path"
  install -d "$source" "$path"
  if ! mountpoint -q "$path"; then mount --bind "$source" "$path"; fi
  if ! grep -Fq "$source $path " /etc/fstab; then
    echo "$source $path none bind,x-systemd.requires-mounts-for=/data 0 0" >> /etc/fstab
  fi
done

apt-get -o DPkg::Lock::Timeout=300 update -qq
apt-get -o DPkg::Lock::Timeout=300 install -y -qq \
  ca-certificates curl iptables rsync e2fsprogs iproute2 unzip
if ! command -v docker >/dev/null; then
  # The data disk can contain containers from the replaced host. Prevent the
  # package installer starting them before KVM/NBD/hugepages are restored.
  systemctl mask --runtime docker.service docker.socket containerd.service
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable' > /etc/apt/sources.list.d/docker.list
  apt-get -o DPkg::Lock::Timeout=300 update -qq
  apt-get -o DPkg::Lock::Timeout=300 install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
fi

# A repaired boot disk lacks the module/sysctl files installed by host-setup.
# Reinstall them before dockerd can restart the persistent containers.
printf 'nbd\ntun\nkvm\n' > /etc/modules-load.d/e2b.conf
echo 'options nbd nbds_max=64 max_part=16' > /etc/modprobe.d/e2b-nbd.conf
modprobe nbd nbds_max=64 max_part=16
modprobe tun
modprobe kvm
sysctl -q -w vm.nr_hugepages=8192
install -d /var/run/netns
install -d /etc/systemd/system/docker.service.d /etc/systemd/system/containerd.service.d
for service in docker containerd; do
  printf '[Unit]\nRequiresMountsFor=/data /var/lib/%s\n' "$service" > "/etc/systemd/system/$service.service.d/storage.conf"
done
systemctl daemon-reload
systemctl unmask --runtime docker.service docker.socket containerd.service
systemctl enable --now docker
cd /opt/e2b
if [ ! -f compose.yaml ]; then
  curl -fsSL "$base_url/compose.yaml" -o compose.yaml.download
  echo '658429e02665fa9e1cc23411e0897b1e2db1867e6fa9c47fb551ac5a313b6b74  compose.yaml.download' | sha256sum -c -
  mv compose.yaml.download compose.yaml
fi
if [ ! -f .env ]; then
  curl -fsSL "$base_url/.env" -o .env.download
  echo '484510816c685a4d6d24bff34d00b05c46306146c0be397507dc215390a182fa  .env.download' | sha256sum -c -
  mv .env.download .env
  printf '\nHUGEPAGES=8192\nE2B_DASHBOARD_HOST=localhost\n' >> .env
  chmod 600 .env
fi
docker compose up -d --wait --wait-timeout 900
if [ -f /opt/e2b/controller.service ]; then
  install -m 0644 /opt/e2b/controller.service /etc/systemd/system/legalwork-vm-controller.service
  systemctl daemon-reload
  systemctl enable legalwork-vm-controller
  # The controller orders after this startup unit; queue its start so the
  # startup script can finish instead of waiting on itself.
  systemctl start --no-block legalwork-vm-controller
fi
echo 'LegalWork E2B host ready. API/dashboard access requires an IAP tunnel.'
# Never print ready/seed logs: they contain the install's API key.
