cmake_minimum_required(VERSION 3.15)
project(LegalWorkNotifications LANGUAGES CXX OBJCXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0")
add_library(LegalWorkNotifications SHARED notification-macos.mm ${CMAKE_JS_SRC})
set_target_properties(LegalWorkNotifications PROPERTIES PREFIX "" SUFFIX ".node")
target_include_directories(LegalWorkNotifications PRIVATE ${CMAKE_JS_INC} ${NODE_ADDON_API_DIR})
target_compile_options(LegalWorkNotifications PRIVATE -fobjc-arc)
target_compile_definitions(LegalWorkNotifications PRIVATE NAPI_CPP_EXCEPTIONS)
target_link_libraries(LegalWorkNotifications ${CMAKE_JS_LIB} "-framework Foundation" "-framework UserNotifications" "-framework Intents" "-framework Security")
