[global]
    server role = standalone server
    workgroup = WORKGROUP
    server min protocol = SMB2_10
    server max protocol = SMB3
    server signing = mandatory
    map to guest = never
    load printers = no
    disable spoolss = yes
    log level = 1
[documents]
    path = /share
    read only = no
    valid users = legalwork
    follow symlinks = no
    wide links = no
    smb encrypt = required
