/** Additional real Google Drive edge cases; uses synthetic files only. Run after oauth-live.ts google-drive. */
import { strict as assert } from "node:assert";
import { storageInputSchema } from "../../apps/server/src/file-storage/schema.js";
import { StorageOAuth, tokenBindings } from "../../apps/server/src/file-storage/oauth/session.js";
import { googleDriveAdapter } from "../../apps/server/src/file-storage/oauth/google-drive.js";
import { authorizedFetch } from "../../apps/server/src/file-storage/oauth/http.js";
const directory = process.env.LEGALWORK_OAUTH_TEST_DIR;
if (!directory) throw new Error("Set LEGALWORK_OAUTH_TEST_DIR.");
const input = storageInputSchema.parse({ name: "OAuth verification", config: { kind: "oauth", provider: "google-drive" } });
const auth = new StorageOAuth(`${directory}/test.vault`); auth.bind("verification", "google-drive", input);
const token = tokenBindings.get(input)!;
if (input.config.kind !== "oauth") throw new Error("Missing configuration");
const adapter = await googleDriveAdapter(input.config, token);
const name = `LegalWork OAuth Edge Cases ${Date.now()}`;
await adapter.mkdir(name);
const folder = (await adapter.list("")).entries.find((item) => item.name === name)!;
const folderId = folder.path.split("~")[0];
const create = (name: string, mimeType: string) => authorizedFetch(token, "https://www.googleapis.com/drive/v3/files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, mimeType, parents: [folderId] }) });
await (await create("Duplicate.txt", "text/plain")).body?.cancel();
await (await create("Duplicate.txt", "text/plain")).body?.cancel();
const native: unknown = await (await create("Synthetic Google document", "application/vnd.google-apps.document")).json();
if (!native || typeof native !== "object" || !("id" in native) || typeof native.id !== "string") throw new Error("Invalid native document");
const entries = (await adapter.list(folder.path)).entries;
const duplicates = entries.filter((item) => item.name === "Duplicate.txt");
assert.equal(duplicates.length, 2); assert.notEqual(duplicates[0].path, duplicates[1].path);
await assert.rejects(() => adapter.read(`${folder.path}/Duplicate.txt`), /Several files/);
const document = entries.find((item) => item.path.includes(native.id))!;
const exported = await adapter.read(document.path);
assert.equal(exported.data.subarray(0, 2).toString(), "PK");
assert.equal(exported.writable, false);
await assert.rejects(() => adapter.write(document.path, Buffer.from("not a native document"), "text/plain", { version: exported.version }), /exports locally/);
await adapter.write(`${folder.path}/empty.txt`, Buffer.alloc(0), "text/plain", { createOnly: true });
assert.equal((await adapter.read(`${folder.path}/empty.txt`)).data.length, 0);
const nested = await googleDriveAdapter({ kind: "oauth", provider: "google-drive", root: folderId }, token);
await assert.rejects(() => nested.list(`root~outside`), /outside the selected folder/);
console.log(JSON.stringify({ provider: "google-drive", duplicateNames: true, nativeExport: true, exportReadOnly: true, emptyUpload: true, rootBoundary: true }));
