export const usageCopy = {
  "en": {
  "limits.invitation_pending": "Invitation pending",
  "limits.retry_change": "Finish change",
  "limits.pending_change_hint": "Retry to complete the confirmed change. The same payment will not be collected twice.",
  "limits.member_change_error": "We could not complete the change. Retry to finish without paying twice. If payment was declined or the price changed, review the price again.",
  "limits.quote_hint": "Includes the prorated change today. The recurring total is before taxes and discounts. Your billing date stays the same.",
  "limits.organization_total": "New organization total",
  "limits.due_today": "Due today",
  "limits.confirm_change": "Confirm change",
  "limits.confirm_invite": "Confirm & send invitation",
  "limits.email": "Email address",
  "limits.invite_hint": "Choose a plan for this person. Review the prorated charge, then confirm to send their invitation. Billing starts when you invite them.",
  "limits.invite_member": "Invite member",
    "limits.payment_tab": "Payment method",
    "limits.payment_description": "Manage the card used for your subscription and top-ups.",
    "limits.card_expires": "Expires",
    "limits.payment_load_error": "Payment details could not be loaded. Please retry.",
    "limits.payment_loading": "Loading payment details…",
    "limits.no_saved_card": "No saved card",
    "limits.default_payment": "Default",
    "limits.payment_update_hint": "Card details are updated securely through Stripe.",
    "limits.change_card": "Change card",
    "limits.add_card": "Add payment method",
    "limits.card_security": "Card details are stored securely by Stripe.",
    "limits.saved_card_charge_hint": "Confirm to charge this card once. Your subscription stays unchanged.",
    "limits.no_card_checkout": "Add credits using Stripe Checkout. You can save a card for future top-ups in Payment method.",
    "limits.confirm_topup": "Pay & add credits",
    "limits.continue_checkout": "Continue to payment",
    "limits.other_payment": "Use another payment method",
    "limits.invalid_topup": "Enter an amount between €20 and €50,000 with at most two decimal places.",
    "limits.pending_topup_hint": "A previous top-up is unfinished. Resume it to check payment before starting another.",
    "limits.resume_topup": "Resume top-up",
    "limits.cancel_topup": "Cancel top-up",
    "limits.cancel_topup_hint": "Canceling stops this unpaid top-up. A completed payment cannot be canceled here.",
    "limits.check_payment": "Check payment status",
    "limits.complete_payment": "Complete payment",
    "limits.cancel_failed": "Could not cancel. Check the payment status and try again.",
    "limits.card_declined": "This card could not be charged. Cancel this top-up to choose another payment method.",
    "limits.payment_processing": "Your payment is still processing. Check its status before starting another top-up.",
    "limits.payment_changed": "The saved card changed. Refresh payment details or use another payment method.",
    "limits.topup_verify_hint": "Your payment needs attention. Complete bank verification on the secure payment page. This continues the same top-up.",
    "limits.topup_paid": "Payment received",
    "limits.topup_paid_hint": "Your balance updates automatically once payment confirmation is processed.",
    "limits.topup_retry_hint": "We could not confirm the result. Resume this top-up to check its status without creating another payment.",
    "limits.topup_hint": "Add prepaid funds to the shared organization balance.",
    "limits.title": "Usage & limits",
    "limits.refresh": "Refresh",
    "limits.loading": "Loading usage…",
    "limits.load_error": "Usage is unavailable. Please retry.",
    "limits.action_error": "Could not apply this change. Refresh and try again.",
    "limits.buy_seat_first": "Purchase an available seat of this tier first.",
    "limits.request_expired": "This request is from a previous month. Ask the member to submit a new request.",
    "limits.invalid_amount": "Enter an amount between €0 and €50,000 with at most two decimal places.",
    "limits.not_enabled": "Your organization is awaiting activation of member budgets. These controls become effective after activation.",
    "limits.your_usage": "Included this week",
    "limits.remaining": "remaining",
    "limits.resets": "Resets",
    "limits.extra": "Extra usage this month",
  "limits.no_seat": "No paid plan",
    "limits.blocked": "Your usage limit has been reached. Request more usage from an admin.",
    "limits.request": "Request more usage",
    "limits.request_hint": "Your admin can approve extra usage or assign a higher seat tier. Sending a request does not charge your organization.",
    "limits.kind": "Request type",
    "limits.temporary": "Additional amount for this month",
    "limits.recurring": "New recurring monthly extra limit",
    "limits.upgrade": "Upgrade to Pro",
    "limits.amount": "Amount (€)",
    "limits.reason": "Reason (optional)",
    "limits.note": "Decision note",
    "limits.send": "Send request",
    "limits.requests": "Usage requests",
    "limits.no_requests": "No requests yet.",
    "limits.pending": "Waiting for admin",
    "limits.approved": "Approved",
    "limits.declined": "Declined",
    "limits.approve": "Approve",
    "limits.decline": "Decline",
    "limits.awaiting_funds": "Approved. An organization budget or available balance may still prevent extra usage.",
    "limits.wallet": "Organization balance",
    "limits.wallet_hint": "Shared prepaid funds, less current reservations. Assigning a member limit does not reserve funds.",
    "limits.topup_amount": "Top-up (€20–€50,000)",
    "limits.topup": "Add credits",
    "limits.checkout_hint": "Secure payment opens in Stripe. Credits appear after payment confirmation; this view refreshes automatically.",
    "limits.enable_extra": "Allow extra usage from prepaid credits",
    "limits.org_limit": "Organization monthly extra limit (€)",
    "limits.default_limit": "Default extra limit per member (€)",
    "limits.month_used": "Extra used this month:",
    "limits.unlimited_hint": "An empty organization limit means unlimited; €0 blocks extra usage.",
    "limits.save": "Save",
  "limits.members": "Members & plans",
  "limits.seat": "Plan",
    "limits.member_limit": "Recurring extra limit (€)",
    "limits.inherit": "Use default",
    "limits.buy_seats": "Purchase seats",
    "limits.quantity": "Number of seats",
    "limits.confirm_purchase": "Confirm purchase:",
    "limits.preview_purchase": "Review price",
    "limits.purchase_hint": "Adds recurring seats on the organization’s billing interval. Review the amount due now before confirming. Assign purchased seats above.",
    "limits.purchase_error": "Purchase was not completed. Review the price again or update your payment method in Billing.",
    "limits.open": "Usage & admin requests",
    "limits.recurring_price": "Added recurring price, before tax and discounts",
    "limits.per_month": "per month",
    "limits.per_year": "per year"
  },
  "de": {
  "limits.invitation_pending": "Einladung ausstehend",
  "limits.retry_change": "Änderung abschließen",
  "limits.pending_change_hint": "Wiederholen Sie die bestätigte Änderung. Die Zahlung wird nicht doppelt eingezogen.",
  "limits.member_change_error": "Die Änderung konnte nicht abgeschlossen werden. Versuchen Sie es ohne doppelte Zahlung erneut. Prüfen Sie bei abgelehnter Zahlung oder Preisänderung den Preis erneut.",
  "limits.quote_hint": "Der heutige Betrag berücksichtigt die anteilige Änderung. Der wiederkehrende Gesamtpreis versteht sich vor Steuern und Rabatten. Ihr Abrechnungstag bleibt unverändert.",
  "limits.organization_total": "Neuer Gesamtpreis",
  "limits.due_today": "Heute fällig",
  "limits.confirm_change": "Änderung bestätigen",
  "limits.confirm_invite": "Bestätigen & Einladung senden",
  "limits.email": "E-Mail-Adresse",
  "limits.invite_hint": "Wählen Sie eine Stufe für diese Person. Prüfen Sie die anteiligen Kosten und bestätigen Sie die Einladung. Die Abrechnung beginnt mit der Einladung.",
  "limits.invite_member": "Mitglied einladen",
    "limits.payment_tab": "Zahlungsmethode",
    "limits.payment_description": "Verwalten Sie die Karte für Ihr Abonnement und Ihre Guthabenaufladungen.",
    "limits.card_expires": "Gültig bis",
    "limits.payment_load_error": "Zahlungsdaten konnten nicht geladen werden. Bitte versuchen Sie es erneut.",
    "limits.payment_loading": "Zahlungsdaten werden geladen…",
    "limits.no_saved_card": "Keine Karte hinterlegt",
    "limits.default_payment": "Standard",
    "limits.payment_update_hint": "Kartendaten werden sicher über Stripe aktualisiert.",
    "limits.change_card": "Karte ändern",
    "limits.add_card": "Zahlungsmethode hinzufügen",
    "limits.card_security": "Kartendaten werden sicher bei Stripe gespeichert.",
    "limits.saved_card_charge_hint": "Mit Ihrer Bestätigung wird diese Karte einmalig belastet. Ihr Abonnement bleibt unverändert.",
    "limits.no_card_checkout": "Laden Sie Guthaben über Stripe Checkout auf. Unter Zahlungsmethode können Sie eine Karte für künftige Aufladungen speichern.",
    "limits.confirm_topup": "Bezahlen und Guthaben aufladen",
    "limits.continue_checkout": "Weiter zur Zahlung",
    "limits.other_payment": "Andere Zahlungsmethode verwenden",
    "limits.invalid_topup": "Geben Sie einen Betrag zwischen 20 € und 50.000 € mit höchstens zwei Nachkommastellen ein.",
    "limits.pending_topup_hint": "Eine frühere Aufladung ist noch offen. Prüfen Sie zuerst deren Zahlungsstatus.",
    "limits.resume_topup": "Aufladung fortsetzen",
    "limits.cancel_topup": "Aufladung abbrechen",
    "limits.cancel_topup_hint": "Der Abbruch beendet diese unbezahlte Aufladung. Eine abgeschlossene Zahlung kann hier nicht abgebrochen werden.",
    "limits.check_payment": "Zahlungsstatus prüfen",
    "limits.complete_payment": "Zahlung abschließen",
    "limits.cancel_failed": "Abbruch fehlgeschlagen. Prüfen Sie den Zahlungsstatus und versuchen Sie es erneut.",
    "limits.card_declined": "Diese Karte konnte nicht belastet werden. Brechen Sie die Aufladung ab, um eine andere Zahlungsmethode zu wählen.",
    "limits.payment_processing": "Die Zahlung wird noch verarbeitet. Prüfen Sie den Status, bevor Sie eine weitere Aufladung starten.",
    "limits.payment_changed": "Die gespeicherte Karte hat sich geändert. Aktualisieren Sie die Zahlungsdaten oder verwenden Sie eine andere Zahlungsmethode.",
    "limits.topup_verify_hint": "Ihre Zahlung erfordert einen weiteren Schritt. Bestätigen Sie die Zahlung auf der sicheren Zahlungsseite Ihrer Bank. Sie setzen damit dieselbe Aufladung fort.",
    "limits.topup_paid": "Zahlung eingegangen",
    "limits.topup_paid_hint": "Ihr Guthaben wird automatisch aktualisiert, sobald die Zahlungsbestätigung verarbeitet wurde.",
    "limits.topup_retry_hint": "Das Ergebnis konnte nicht bestätigt werden. Setzen Sie diese Aufladung fort, um den Status zu prüfen, ohne eine neue Zahlung anzulegen.",
    "limits.topup_hint": "Laden Sie das gemeinsame Guthaben Ihrer Organisation auf.",
    "limits.title": "Nutzung & Limits",
    "limits.refresh": "Aktualisieren",
    "limits.loading": "Nutzung wird geladen…",
    "limits.load_error": "Nutzung ist nicht verfügbar. Bitte erneut versuchen.",
    "limits.action_error": "Die Änderung konnte nicht übernommen werden. Bitte aktualisieren und erneut versuchen.",
    "limits.buy_seat_first": "Kaufen Sie zuerst einen verfügbaren Platz dieser Stufe.",
    "limits.request_expired": "Diese Anfrage stammt aus einem früheren Monat. Bitten Sie das Mitglied um eine neue Anfrage.",
    "limits.invalid_amount": "Geben Sie einen Betrag zwischen 0 € und 50.000 € mit höchstens zwei Nachkommastellen ein.",
    "limits.not_enabled": "Für Ihre Organisation müssen die Mitgliederbudgets noch aktiviert werden. Die Einstellungen werden danach wirksam.",
    "limits.your_usage": "Diese Woche enthalten",
    "limits.remaining": "verbleibend",
    "limits.resets": "Wird zurückgesetzt am",
    "limits.extra": "Zusätzliche Nutzung diesen Monat",
  "limits.no_seat": "Keine bezahlte Stufe",
    "limits.blocked": "Ihr Nutzungslimit ist erreicht. Fordern Sie zusätzliche Nutzung bei einem Admin an.",
    "limits.request": "Mehr Nutzung anfragen",
    "limits.request_hint": "Ihr Admin kann zusätzliche Nutzung genehmigen oder eine höhere Stufe zuweisen. Die Anfrage verursacht keine Kosten.",
    "limits.kind": "Art der Anfrage",
    "limits.temporary": "Zusätzlicher Betrag für diesen Monat",
    "limits.recurring": "Neues monatliches Limit für zusätzliche Nutzung",
    "limits.upgrade": "Auf Pro upgraden",
    "limits.amount": "Betrag (€)",
    "limits.reason": "Begründung (optional)",
    "limits.note": "Anmerkung zur Entscheidung",
    "limits.send": "Anfrage senden",
    "limits.requests": "Nutzungsanfragen",
    "limits.no_requests": "Noch keine Anfragen.",
    "limits.pending": "Wartet auf Admin",
    "limits.approved": "Genehmigt",
    "limits.declined": "Abgelehnt",
    "limits.approve": "Genehmigen",
    "limits.decline": "Ablehnen",
    "limits.awaiting_funds": "Genehmigt. Ein Organisationslimit oder das verfügbare Guthaben kann zusätzliche Nutzung weiterhin begrenzen.",
    "limits.wallet": "Organisationsguthaben",
    "limits.wallet_hint": "Gemeinsames Guthaben abzüglich laufender Reservierungen. Ein Mitgliederlimit reserviert kein Guthaben.",
    "limits.topup_amount": "Aufladung (20 €–50.000 €)",
    "limits.topup": "Guthaben aufladen",
    "limits.checkout_hint": "Die sichere Zahlung öffnet sich in Stripe. Guthaben erscheint nach der Zahlungsbestätigung; diese Ansicht wird automatisch aktualisiert.",
    "limits.enable_extra": "Zusätzliche Nutzung aus Guthaben erlauben",
    "limits.org_limit": "Monatliches Organisationslimit für zusätzliche Nutzung (€)",
    "limits.default_limit": "Standardlimit pro Mitglied (€)",
    "limits.month_used": "Zusätzliche Nutzung diesen Monat:",
    "limits.unlimited_hint": "Ein leeres Organisationslimit bedeutet unbegrenzt; 0 € sperrt zusätzliche Nutzung.",
    "limits.save": "Speichern",
  "limits.members": "Mitglieder & Stufen",
  "limits.seat": "Stufe",
    "limits.member_limit": "Monatliches Zusatzlimit (€)",
    "limits.inherit": "Standard verwenden",
    "limits.buy_seats": "Plätze kaufen",
    "limits.quantity": "Anzahl der Plätze",
    "limits.confirm_purchase": "Kauf bestätigen:",
    "limits.preview_purchase": "Preis prüfen",
    "limits.purchase_hint": "Fügt wiederkehrend berechnete Plätze im Abrechnungsintervall der Organisation hinzu. Prüfen Sie den sofort fälligen Betrag. Gekaufte Plätze können Sie oben zuweisen.",
    "limits.purchase_error": "Kauf nicht abgeschlossen. Prüfen Sie den Preis erneut oder aktualisieren Sie Ihr Zahlungsmittel unter Abrechnung.",
    "limits.open": "Nutzung & Admin-Anfragen",
    "limits.recurring_price": "Zusätzlicher wiederkehrender Preis vor Steuern und Rabatten",
    "limits.per_month": "pro Monat",
    "limits.per_year": "pro Jahr"
  }
};
