import {test,expect} from 'bun:test';
import {emptyCompose,selectComposeSender,defaultComposeSender,composeTextHtml} from '../src/react-app/domains/mail/mail-compose-model';
import {mailDraftContentSchema} from '../../server/src/mail/local-view';
import type {SenderIdentity} from '../../server/src/mail/sender-view';
const self:SenderIdentity={id:'self',accountId:'account',address:'self@example.com',displayName:'',source:'provider_verified',available:true,signature:'Self',defaultNew:true,defaultReply:false,sendMode:'self'};
const alias:SenderIdentity={...self,id:'alias',address:'alias@example.com',signature:'Alias',defaultNew:false,defaultReply:true};
test('new/reply defaults are independent and unavailable identities are excluded',()=>{expect(defaultComposeSender([self,alias],false)?.id).toBe('self');expect(defaultComposeSender([self,alias],true)?.id).toBe('alias');expect(defaultComposeSender([{...self,available:false}],false)).toBeUndefined();});
test('selected identity and signature survive draft recovery and switching replaces exact inserted signature',()=>{const first=selectComposeSender({...emptyCompose(''),text:'Body'},self);const recovered=mailDraftContentSchema.parse(JSON.parse(JSON.stringify(first)));expect(recovered.senderIdentityId).toBe('self');const second=selectComposeSender(recovered,alias);expect(second.text).toBe('Body\n\n-- \nAlias');expect(second.from).toBe(alias.address);const edited=selectComposeSender({...first,text:first.text+' edited'},alias);expect(edited.text).toContain('Self edited');});
test('signatures are escaped in rich compose and sender switching preserves recipient/body data',()=>{const before={...emptyCompose(''),to:['recipient@example.com'],text:'Body',html:'<p>Body</p>'};const after=selectComposeSender(before,{...self,signature:'<script>bad</script>'});expect(after.html).toContain('&lt;script&gt;');expect(after.html).not.toContain('<script>');expect(after.to).toEqual(before.to);expect(selectComposeSender(after,alias).html).not.toContain('&lt;script&gt;');});

 test('plain-to-rich conversion retains replaceable unchanged signatures but does not mark edited text',()=>{const first=selectComposeSender({...emptyCompose(''),text:'Body'},self);const rich={...first,html:composeTextHtml(first)};expect(selectComposeSender(rich,alias).html).not.toContain('Self');expect(selectComposeSender(rich,alias).html).toContain('Alias');expect(composeTextHtml({...first,text:first.text+' edited'})).not.toContain('data-mail-signature');});

test('text-node signature quotes remain literal while ampersands and markup stay escaped',()=>{const quoted={...self,signature:'Alice "A" & Partners'};const first=selectComposeSender({...emptyCompose(''),text:'Body',html:'Body'},quoted);expect(first.html).toContain('Alice "A" &amp; Partners');expect(first.html).not.toContain('&quot;');expect(composeTextHtml(first)).toContain('Alice "A" &amp; Partners');expect(selectComposeSender(first,alias).html).not.toContain('Alice');});
