import {test,expect} from 'bun:test';
import {mkdtemp,writeFile,readFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createRequire} from 'node:module';
import {spawn,execFileSync} from 'node:child_process';
test('isolated mail preserves responsive layout, blocks active content and resizes long threads',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-html-render-')),appRoot=resolve(import.meta.dir,'..'),fixtures=resolve(appRoot,'../server/src/mail/testing/html-fixtures');
 const evidence=process.env.LEGALWORK_MAIL_HTML_EVIDENCE;if(evidence)await mkdir(evidence,{recursive:true});
 try{
 const values:Record<string,string>={};for(const name of ['newsletter','outlook-receipt','gmail-thread','malformed'])values[name]=await readFile(join(fixtures,name+'.html'),'utf8');
 values['height-overflow']='<html><body style="height:100%;min-height:100vh"><div style="height:90px"><p>Start</p>'+('<p style="line-height:40px">Visible content</p>'.repeat(30))+'<p id="footer">Visible footer</p></div></body></html>';
 const image='data:image/png;base64,'+(await readFile(join(fixtures,'brand.png'))).toString('base64');
 // Frozen pre-change renderer for an honest same-fixture comparison.
 await writeFile(join(appRoot,'tests/.mail-html-before.ts'),execFileSync('git',['show','a4118bcca:apps/app/src/react-app/domains/mail/mail-html.ts'],{cwd:appRoot}));
 const entry=join(appRoot,'tests/.mail-html-entry.tsx');await writeFile(entry,`import React from 'react';import {createRoot} from 'react-dom/client';import '../src/react-app/domains/mail/mail-reader.css';import {MailHtmlFrame,MailHtmlParts} from '../src/react-app/domains/mail/mail-html-frame';import {mailDocument,boundedMailRaster} from '../src/react-app/domains/mail/mail-html';import {mailHtml as before} from './.mail-html-before';window.fixtures=${JSON.stringify(values)};window.image=${JSON.stringify(image)};window.checkBudget=()=>mailDocument('<img src="cid:brand"><img src="cid:brand">',new Map([['brand',window.image]]),new Map(),undefined,window.image.length).html;window.checkRaster=()=>{const bytes=Uint8Array.from(atob(window.image.split(',')[1]),c=>c.charCodeAt(0));const normal=boundedMailRaster(bytes);new DataView(bytes.buffer).setUint32(16,100000);return {normal,bomb:boundedMailRaster(bytes)};};window.imageCalls=0;window.externalLinks=[];window.__LEGALWORK_ELECTRON__={mailImages:async input=>{if('url' in input)throw Error('arbitrary URL');window.imageCalls++;return {items:[{url:'https://images.example.test/hero.png',data:window.image}],failed:0};},mailImagesCancel:async()=>{},shell:{openExternal:async url=>window.externalLinks.push(url)}};window.renderMail=(name,old=false)=>{const html=window.fixtures[name];const inline=new Map([['brand',window.image]]);window.rendered=mailDocument(html,inline);window.reactMailRoot??=createRoot(document.getElementById('root'));window.reactMailRoot.render(old?<iframe title="Before" sandbox="" srcDoc={before(html,inline)} style={{width:'100%',height:850,border:0}}/>:<MailHtmlFrame key={name} html={html} inline={inline} item={{accountId:'a',key:name}} bodyPart={{partId:'',referenceId:'sha256:synthetic'}} signal={new AbortController().signal}/>);};window.renderMany=()=>window.reactMailRoot.render(<MailHtmlParts key='many' bodies={Array.from({length:11},(_,index)=>({text:'<p>Section '+index+'</p>'}))} inline={new Map()} item={{accountId:'a',key:'many'}} signal={new AbortController().signal}/>);window.renderLegacy=()=>window.reactMailRoot.render(<MailHtmlParts bodies={[{text:'<p>Primary text</p>'},{text:'<p>Substantive appendix</p>'}]} inline={new Map()} item={{accountId:'a',key:'legacy'}} signal={new AbortController().signal}/>);window.renderMail('newsletter');`);
 const build=await Bun.build({entrypoints:[entry],target:'browser',outdir:root,minify:false});if(!build.success)throw Error(build.logs.map(String).join('\n'));
 await writeFile(join(root,'index.html'),'<html><head><meta charset="utf-8"><link rel="stylesheet" href=".mail-html-entry.css"><style>body{margin:0;background:#f6f7f8;font:13px Arial}.mail-html-view iframe{width:100%;border:0;display:block;background:white}#root{max-width:760px;margin:0 auto}*{box-sizing:border-box}</style></head><body><div id="root" class="mail-message-body"></div><script src=".mail-html-entry.js"></script></body></html>');
 const probe=join(root,'probe.cjs');await writeFile(probe,`const {app,BrowserWindow,nativeTheme}=require('electron');const assert=require('node:assert/strict');const fs=require('node:fs/promises');app.setPath('userData',${JSON.stringify(join(root,'profile'))});app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:780,height:1100,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true}});win.webContents.on('console-message',(_e,_l,m)=>console.log(m));let network=[];win.webContents.session.webRequest.onBeforeRequest((details,done)=>{if(/^https?:/.test(details.url))network.push(details.url);done({cancel:/^https?:/.test(details.url)});});await win.loadFile(${JSON.stringify(join(root,'index.html'))});const run=async s=>{try{return await win.webContents.executeJavaScript(s);}catch(e){throw Error(s+' '+e.message);}};const wait=ms=>new Promise(r=>setTimeout(r,ms));await wait(300);const until=async s=>{for(let i=0;i<100;i++){if(await run(s))return;await wait(25);}throw Error('deadline '+s)};await until("document.querySelector('iframe')?.style.height !== '160px'");
 const screenshot=async name=>{${evidence?`await fs.writeFile(${JSON.stringify(evidence)}+'/'+name+'.png',(await win.webContents.capturePage()).toPNG());`:''}};
 for(const name of ['newsletter','outlook-receipt','gmail-thread','malformed']){for(const width of [780,390]){win.setContentSize(width,1100);await run('window.renderMail('+JSON.stringify(name)+',true)');await wait(150);await screenshot(name+'-'+width+'-before');await run('window.renderMail('+JSON.stringify(name)+',false)');await wait(250);await screenshot(name+'-'+width+'-after');const currentFrame=win.webContents.mainFrame.frames.find(f=>f.url==='about:srcdoc');assert.ok(currentFrame);const metrics=await currentFrame.executeJavaScript('({width:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.clientHeight,scrollHeight:document.documentElement.scrollHeight})');assert.ok(metrics.scrollHeight<=metrics.height+1,JSON.stringify({name,width,metrics}));if(name==='newsletter')assert.ok(metrics.scrollWidth<=metrics.width+1,JSON.stringify({name,width,metrics}));assert.equal(await run("document.querySelector('iframe').sandbox.value"),'allow-scripts');assert.equal(await run("document.querySelector('iframe').contentDocument===null"),true);if(name==='gmail-thread')assert.ok(await run("parseInt(document.querySelector('iframe').style.height)>700"));}}
 await run("window.renderMail('height-overflow')");await wait(300);const stableHeight=await run("document.querySelector('iframe').style.height");await wait(400);assert.equal(await run("document.querySelector('iframe').style.height"),stableHeight);const overflow=win.webContents.mainFrame.frames.find(f=>f.url==='about:srcdoc');assert.ok(await overflow.executeJavaScript("document.querySelector('#footer').getBoundingClientRect().bottom<=innerHeight"));assert.equal((await run('window.checkBudget()')).split('data:image/png;base64,').length-1,1);assert.deepEqual(await run('window.checkRaster()'),{normal:'image/png',bomb:null});assert.deepEqual(network,[]);assert.equal(await run('window.imageCalls'),0);await run("window.renderMail('newsletter')");await wait(200);const doc=await run('window.rendered.html');assert.ok(doc.includes('@media'));assert.ok(doc.includes('cellpadding="0"'));assert.ok(doc.includes('width="72"'));assert.ok(doc.includes('data:image/png;base64'));assert.ok(doc.includes('padding:32px'));assert.ok(!doc.includes('src="https:'));assert.ok(!doc.includes('href="https:'));
 assert.equal(await run('window.externalLinks.length'),0);
 await run("[...document.querySelectorAll('button')].find(b=>b.textContent==='Load images').click()");await wait(200);assert.equal(await run('window.imageCalls'),1);assert.equal(await run("document.body.textContent.includes('External images loaded')"),true);await screenshot('newsletter-images-loaded');
 const iframe=win.webContents.mainFrame.frames.find(f=>f.url==='about:srcdoc');assert.ok(iframe);const rect=await iframe.executeJavaScript("(()=>{const r=document.querySelector('[data-mail-link]').getBoundingClientRect();return {x:r.x+5,y:r.y+5}})()");const frameRect=await run("(()=>{const r=document.querySelector('iframe').getBoundingClientRect();return {x:r.x,y:r.y}})()");win.webContents.debugger.attach('1.3');await win.webContents.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mousePressed',x:rect.x+frameRect.x,y:rect.y+frameRect.y,button:'left',clickCount:1});await win.webContents.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mouseReleased',x:rect.x+frameRect.x,y:rect.y+frameRect.y,button:'left',clickCount:1});win.webContents.debugger.detach();await wait(100);assert.equal(await run("document.querySelector('[aria-label=\\"Open message link\\"]')!==null"),true);assert.equal(await run('window.externalLinks.length'),0);await run("[...document.querySelectorAll('button')].find(b=>b.textContent==='Open link').click()");assert.deepEqual(await run('window.externalLinks'),['https://example.test/briefing']);
 nativeTheme.themeSource='dark';await run("window.renderMail('outlook-receipt')");await wait(150);await screenshot('outlook-receipt-dark-shell');nativeTheme.themeSource='light';
 await run("window.renderMail('malformed')");await wait(150);const unsafe=await run('window.rendered.html');assert.ok(!unsafe.includes('<form'));assert.ok(!unsafe.includes('parent.document'));assert.ok(!unsafe.includes('@import'));assert.ok(!unsafe.includes('url(https:'));assert.ok(!unsafe.includes('javascript:'));assert.ok(!unsafe.includes('<input'));
 await run('window.renderLegacy()');await wait(150);assert.equal(await run("document.querySelectorAll('iframe').length"),2);assert.ok(await run("document.body.textContent.includes('Message part 2 of 2')"));const sectionFrames=win.webContents.mainFrame.frames.filter(f=>f.url==='about:srcdoc');assert.ok((await Promise.all(sectionFrames.map(f=>f.executeJavaScript('document.body.textContent')))).join(' ').includes('Substantive appendix'));await run('window.renderMany()');await wait(150);assert.equal(await run("document.querySelectorAll('iframe').length"),10);await run("[...document.querySelectorAll('button')].find(b=>b.textContent==='Next parts').click()");await wait(150);assert.equal(await run("document.querySelectorAll('iframe').length"),1);assert.ok(await run("document.body.textContent.includes('Message part 11 of 11')"));await run("window.renderMail('malformed')");await wait(150);const oldHeight=await run("document.querySelector('iframe').style.height");await run("window.postMessage({type:'mail-size',token:'fake',height:19999},'*')");await wait(50);assert.equal(await run("document.querySelector('iframe').style.height"),oldHeight);console.log('MAIL_HTML_RENDER_PASS');win.destroy();app.quit();}).catch(e=>{console.error(e);app.exit(1)});`);
 // Existing installed Electron; no application build or live development profile.
 const electron=process.env.LEGALWORK_TEST_ELECTRON??createRequire(resolve(appRoot,'../desktop/package.json'))('electron');
 const result=await new Promise<{code:number|null;output:string}>((done,reject)=>{const child=spawn(electron,[probe],{env:{HOME:process.env.HOME,PATH:process.env.PATH,...(process.platform==='win32'?{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR}:{})},stdio:['ignore','pipe','pipe']});let output='';const timer=setTimeout(()=>{child.kill();reject(Error(output+' deadline'));},45000);child.stdout.on('data',v=>output+=v);child.stderr.on('data',v=>output+=v);child.on('error',reject);child.on('close',code=>{clearTimeout(timer);done({code,output});});});if(result.code!==0)throw Error(result.output);expect(result.output).toContain('MAIL_HTML_RENDER_PASS');
 }finally{await rm(join(appRoot,'tests/.mail-html-entry.tsx'),{force:true});await rm(join(appRoot,'tests/.mail-html-before.ts'),{force:true});await rm(root,{recursive:true,force:true});}
},60000);
