import {test,expect} from 'bun:test';
import {mkdtemp,writeFile,rm,symlink,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {createRequire} from 'node:module';import {spawn} from 'node:child_process';
test('actual isolated search renderer applies filters, navigates sections/pages, saves privately and cancels stale requests',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-search-render-')),appRoot=resolve(import.meta.dir,'..');const seen:unknown[]=[];let saved:unknown[]=[];let revoked=false;
 const hit={accountId:'a',locator:{provider:'gmail',messageId:'m'},subject:'Kündigung AZ-12/34.5',snippet:'Exact local attachment excerpt',date:null,hasAttachment:true,attachmentSources:[{partId:'p',referenceId:'r'}],attachmentMatches:[{partId:'p',referenceId:'r',section:2,offset:40,source:'page:3'}]};
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:async request=>{const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'X-LegalWork-Host-Token,Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};if(request.method==='OPTIONS')return new Response(null,{headers});if(request.headers.get('X-LegalWork-Host-Token')!=='synthetic')return new Response(null,{status:401,headers});const path=new URL(request.url).pathname,input=request.method==='POST'?await request.json():{};let value:unknown;
 if(path.endsWith('/revoke')){revoked=true;value={};}else if(path.endsWith('/restore')){revoked=false;value={};}else if(path.endsWith('/search/saved')){if(input.action==='save'){const item={id:input.id,name:input.name,revision:1,query:input.query};saved=[item];value={action:'save',item};}else if(input.action==='delete'){saved=[];value={action:'delete',id:input.id,deleted:true};}else value={action:'list',items:saved,nextCursor:null};}
 else if(path.endsWith('/search')){seen.push(input);if(input.literal==='slow')await new Promise(resolve=>setTimeout(resolve,250));value={items:revoked||input.literal==='empty'?[]:[{...hit,subject:input.literal==='slow'?'STALE RESULT':input.offset?'Second page source':hit.subject},...(input.offset||input.literal==='empty'?[]:[{...hit,locator:{provider:'gmail',messageId:'m2'},subject:'Second keyboard result'}])],total:revoked||input.literal==='empty'?0:21,pending:3,incomplete:2,nextOffset:revoked||input.offset||input.literal==='empty'?null:20};}
 else if(path.includes('/extraction/read'))value={status:{accountId:'a',locator:hit.locator,partId:'p',referenceId:'r',extractor:'local-text-v1',downloaded:true,state:'complete',attempts:1,error:null,sections:3},section:input.section,offset:input.offset,source:'page:3',method:'ocr',text:'Kündigung attachment page three',nextOffset:null,nextSection:null};
 else if(path.endsWith('/messages/read'))value={accountId:'a',key:'m',locator:hit.locator,subject:'Opened source message',threadId:null,rfcMessageId:null,removed:false,memberships:['INBOX'],contentState:'complete',metadata:null};
 else value={items:[],nextCursor:null};return Response.json(value,{headers});}});
 try{
  await symlink(join(appRoot,'node_modules'),join(root,'node_modules'),process.platform==='win32'?'junction':'dir');const entry=join(root,'entry.tsx');await writeFile(entry,`import React,{useState} from ${JSON.stringify(join(appRoot,'node_modules/react/index.js'))};import{createRoot}from${JSON.stringify(join(appRoot,'node_modules/react-dom/client.js'))};import{MailSearch}from${JSON.stringify(join(appRoot,'src/react-app/domains/mail/mail-search.tsx'))};import{MailClient}from${JSON.stringify(join(appRoot,'src/react-app/domains/mail/mail-client.ts'))};const client=new MailClient('http://127.0.0.1:${server.port}','synthetic');function App(){const [message,setMessage]=useState();return <><MailSearch client={client} accounts={[{id:'a',provider:'gmail',displayName:'Firm account'}]} onOpen={setMessage}/><p id="opened">{message?.subject}</p></>}createRoot(document.getElementById('root')).render(<App/>);`);
  const build=await Bun.build({entrypoints:[entry],target:'browser',outdir:root,alias:{'@':join(appRoot,'src')},minify:true,plugins:[{name:'fixture-zod',setup(build){build.onResolve({filter:/^zod$/},()=>({path:join(appRoot,'node_modules/zod/index.js')}));}}]});if(!build.success)throw Error(build.logs.map(String).join('\n'));await writeFile(join(root,'index.html'),'<meta charset="utf-8"><style>body{font:14px system-ui}input,select,button{padding:8px;margin:4px}article{border-bottom:1px solid #ccc}label{display:inline-block}</style><div id="root"></div><script src="entry.js"></script>');
  const probe=join(root,'probe.cjs');await writeFile(probe,await readFile(new URL('./mail-search-render-probe.cjs',import.meta.url)));
  const require=createRequire(resolve(appRoot,'../desktop/package.json'));const executable=process.env.LEGALWORK_MAIL_TEST_ELECTRON??require('electron');const result=await new Promise<{code:number|null;output:string}>((resolveResult,reject)=>{const child=spawn(executable,[probe,join(root,'index.html'),`http://127.0.0.1:${server.port}`],{env:{...(process.platform==='win32'?{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR}:{})},stdio:['ignore','pipe','pipe']});let output='';const timer=setTimeout(()=>{child.kill();reject(Error('Renderer timed out '+output));},20000);child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>output+=chunk);child.once('error',reject);child.once('close',code=>{clearTimeout(timer);resolveResult({code,output});});});if(result.code!==0)throw Error(result.output);expect(result.output).toContain('MAIL_SEARCH_RENDER_PASS');expect(seen).toContainEqual({literal:'AZ-12/34.5',keywords:['two','words'],sender:'sender@example.test',recipient:'recipient@example.test',filename:'Änderung.pdf',afterDate:'2026-01-01T00:00:00.000Z',accountIds:['a'],unread:true,hasAttachment:true,limit:20,offset:20});expect(saved).toHaveLength(1);
 }finally{server.stop(true);await rm(root,{recursive:true,force:true});}
},30000);
