import {createHash} from 'node:crypto';
import {test,expect,beforeEach} from 'bun:test';
import {attachMailToChat,type MailChatDestination} from '../src/react-app/domains/mail/mail-chat';
import {mailSourceHref,parseMailSourceHref,type MailChatSource} from '../src/react-app/domains/mail/mail-chat-source';
import {useComposerStateStore,getComposerDraft,getComposerMentions} from '../src/react-app/domains/session/surface/composer-state-store';
const source:MailChatSource={serverOrigin:'http://127.0.0.1:4321',accountId:'personal',locator:{provider:'gmail',messageId:'message'},accountLabel:'Personal',subject:'Synthetic contract',filename:'contract.pdf',referenceId:'ref',sha256:createHash('sha256').update('original').digest('hex')};
beforeEach(()=>useComposerStateStore.setState({sessions:{}}));
function fixture(){const writes:Array<{workspaceId:string;path:string;data:ArrayBuffer}>=[];let opened=0;const destination:MailChatDestination={workspaceId:'server-workspace',sessionId:'chosen-chat',client:{writeWorkspaceBinaryFile:async(workspaceId,input)=>{writes.push({workspaceId,...input});return{ok:true,path:input.path,updatedAt:1};}},assertCurrent:async()=>{},open:()=>{opened++;}};return{destination,writes,get opened(){return opened;}};}
test('chosen chat preserves existing draft, copies original plus provenance without submitting',async()=>{const f=fixture(),state=useComposerStateStore.getState();state.setDraft('chosen-chat','Existing instructions');state.setMentions('chosen-chat',{'existing':'file'});await attachMailToChat(f.destination,new File(['original'],'contract.pdf'),source,new AbortController().signal,async()=>{});expect(f.writes.length).toBe(2);expect(f.writes.every(value=>value.workspaceId==='server-workspace')).toBe(true);expect(new TextDecoder().decode(f.writes[0].data)).toBe('original');const provenance=JSON.parse(new TextDecoder().decode(f.writes[1].data));expect(provenance.source).toEqual(source);expect(provenance.copyPath).toBe(f.writes[0].path);expect(getComposerDraft(useComposerStateStore.getState(),'chosen-chat')).toContain('Existing instructions\n\n@');expect(getComposerDraft(useComposerStateStore.getState(),'chosen-chat')).toContain('[Source email](/mail?source=');expect(getComposerMentions(useComposerStateStore.getState(),'chosen-chat').existing).toBe('file');expect(f.opened).toBe(1);});
test('repeat filenames use distinct bounded Windows-safe paths without overwrite flags',async()=>{const f=fixture();for(const name of ['CON.pdf','x'.repeat(300)+'.pdf','same.pdf','same.pdf'])await attachMailToChat(f.destination,new File(['original'],name),source,new AbortController().signal,async()=>{});const paths=f.writes.filter((_,index)=>index%2===0).map(value=>value.path);expect(new Set(paths).size).toBe(4);expect(paths[0]).toEndWith('/file-CON.pdf');expect(paths[1].split('/').at(-1)!.length).toBeLessThanOrEqual(160);expect(paths[1]).toEndWith('.pdf');expect(f.writes.every(value=>!('force' in value))).toBe(true);});
test('cancelled in-flight copy never adds provenance, draft or navigation',async()=>{const f=fixture(),abort=new AbortController();f.destination.client.writeWorkspaceBinaryFile=async(_,input)=>{abort.abort();return{ok:true,path:input.path,updatedAt:1};};await expect(attachMailToChat(f.destination,new File(['original'],'file.txt'),source,abort.signal,async()=>{})).rejects.toThrow();expect(getComposerDraft(useComposerStateStore.getState(),'chosen-chat')).toBe('');expect(f.opened).toBe(0);});
test('changed source, foreign chat and failed provenance prevent staging',async()=>{for(const mode of ['source','target','provenance']){const f=fixture();let checks=0;if(mode==='target')f.destination.assertCurrent=async()=>{throw Error('Wrong workspace');};if(mode==='provenance')f.destination.client.writeWorkspaceBinaryFile=async(_,input)=>({ok:!input.path.endsWith('.json'),path:input.path,updatedAt:1});await expect(attachMailToChat(f.destination,new File(['original'],'f.txt'),source,new AbortController().signal,async()=>{if(mode==='source'&&++checks===2)throw Error('Removed source');})).rejects.toThrow();expect(f.opened).toBe(0);expect(getComposerDraft(useComposerStateStore.getState(),'chosen-chat')).toBe('');}});
test('return links contain only source scope and reject extra authority',()=>{expect(parseMailSourceHref(mailSourceHref(source))).toEqual({accountId:source.accountId,locator:source.locator,referenceId:source.referenceId,sha256:source.sha256});expect(parseMailSourceHref('/mail?source='+encodeURIComponent(JSON.stringify({...source,serverOrigin:'https://attacker.example'})))).toBeNull();expect(parseMailSourceHref('/mail?source='+encodeURIComponent(JSON.stringify({serverOrigin:source.serverOrigin,accountId:source.accountId,locator:source.locator,token:'forged'})))).toBeNull();});

test('hash mismatch is rejected before any workspace write',async()=>{const f=fixture();await expect(attachMailToChat(f.destination,new File(['tampered'],'f.txt'),source,new AbortController().signal,async()=>{})).rejects.toThrow('verified source');expect(f.writes).toHaveLength(0);});
test('IMAP mailbox Unicode and parentheses survive a Markdown-safe return link',()=>{const original:MailChatSource={...source,locator:{provider:'imap',mailboxId:'Clients (2026)/Müller',uidValidity:1,uid:2}};const href=mailSourceHref(original);expect(href).not.toContain('(');expect(href).not.toContain(')');expect(parseMailSourceHref(href)?.locator).toEqual(original.locator);});

test('durable source link is unchanged when the trusted local server restarts on another port',()=>{expect(mailSourceHref({...source,serverOrigin:'http://127.0.0.1:9876'})).toBe(mailSourceHref(source));});
