import {createHash,randomUUID} from 'node:crypto';
import {test,expect} from 'bun:test';
import {mkdtemp,writeFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';

test('conversation open queues read once and preserves first HTML layout across idle polls',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-conversation-render-')),appRoot=resolve(import.meta.dir,'..');let polls=0;const mutations:unknown[]=[];
 const bytes=Buffer.from(JSON.stringify({version:1,bodies:[{partId:'html',contentType:'text/html',text:'<p>VISIBLE FIRST OPEN</p><div style="height:430px"></div><p>VISIBLE FOOTER</p>'}]})),hash=createHash('sha256').update(bytes).digest('hex');
 const messages=['older','latest'].map((key,index)=>({accountId:'a',key,locator:{provider:'gmail',messageId:key},subject:'Conversation fixture',threadId:'thread',rfcMessageId:null,removed:false,memberships:['INBOX','UNREAD'],contentState:'complete',metadata:null,receivedAt:1000+index,rawReferenceId:'raw-'+key,isRead:false,mutationPrecondition:'v1'}));
 const actions:unknown[]=[];
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:async request=>{
  const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'X-LegalWork-Host-Token,Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
  if(request.method==='OPTIONS')return new Response(null,{headers});
  const path=new URL(request.url).pathname,input=request.method==='POST'?await request.json():null;let value:unknown;
  if(path.endsWith('/status'))value={state:'ready'};
  else if(path.endsWith('/accounts'))value={items:[{id:'a',provider:'gmail',displayName:'Synthetic account'}],nextCursor:null};
  else if(path.endsWith('/folders'))value={items:[{id:'INBOX',name:'Inbox',kind:'label',parentId:null,role:'inbox'}],nextCursor:null};
  else if(path.endsWith('/sync')){polls++;value={state:'complete',enumerated:2,downloaded:2,projected:2,failed:0,pending:0,error:null};}
  else if(path.endsWith('/events/query'))value={stream:'fixture',nextCursor:mutations.length};
  else if(path.endsWith('/messages/query'))value={items:input?.threadId?[...messages].reverse():[{...messages[1],conversation:{count:2,unreadCount:messages.filter(m=>!m.isRead).length}}],nextCursor:null};
  else if(path.endsWith('/messages/read'))value=messages.find(m=>m.key===input.locator.messageId);
  else if(path.endsWith('/messages/parts'))value={items:[{key:'body',kind:'body',partId:'body',state:'stored',referenceId:'body-ref',bytes:bytes.length,sha256:hash,bytesAvailable:true,filename:null,contentType:'application/json',contentId:null}],nextCursor:null};
  else if(path.endsWith('/messages/content'))value={accountId:'a',referenceId:'body-ref',offset:0,totalBytes:bytes.length,sha256:hash,data:bytes.toString('base64'),nextOffset:null};
  else if(path.endsWith('/actions/mutation')){mutations.push(input);const message=messages.find(m=>m.key===input.locator.messageId)!;message.isRead=input.change.read;value={id:randomUUID(),kind:'mutation',state:'queued',version:{generation:randomUUID(),revision:1},attempts:0,maxAttempts:3,availableAt:0,cancelRequested:false,lastError:null,conflictPolicy:'manual',executionSupported:true,credentialCurrent:true,mutation:input};actions.push(value);}
  else if(path.endsWith('/actions/query'))value={items:actions,nextCursor:null};
  else value={};
  return Response.json(value,{headers});
 }});
 try{
  await symlink(join(appRoot,'node_modules'),join(root,'node_modules'),process.platform==='win32'?'junction':'dir');
  const entry=join(root,'entry.tsx');await writeFile(entry,`import React from ${JSON.stringify(join(appRoot,'node_modules/react/index.js'))};import {createRoot} from ${JSON.stringify(join(appRoot,'node_modules/react-dom/client.js'))};import {MemoryRouter} from ${JSON.stringify(join(appRoot,'node_modules/react-router-dom/dist/index.mjs'))};import {MailRoute} from ${JSON.stringify(join(appRoot,'src/react-app/domains/mail/mail-route.tsx'))};localStorage.setItem('legalwork.server.urlOverride','http://127.0.0.1:${server.port}');localStorage.setItem('legalwork.server.token','synthetic');localStorage.setItem('legalwork.server.hostToken','synthetic');window.fixtureLoads=0;window.fixtureMessages=[];document.addEventListener('load',e=>{if(e.target instanceof HTMLIFrameElement)window.fixtureLoads++},true);window.addEventListener('message',e=>{if(e.data?.type==='mail-size')window.fixtureMessages.push({origin:e.origin,height:e.data.height,source:[...document.querySelectorAll('iframe')].some(f=>f.contentWindow===e.source),nonce:[...document.querySelectorAll('iframe')].some(f=>f.srcdoc.includes(e.data.token))})});createRoot(document.getElementById('root')).render(<MemoryRouter><MailRoute/></MemoryRouter>);`);
  const build=await Bun.build({entrypoints:[entry],target:'browser',outdir:root,alias:{'@':join(appRoot,'src'),'../session/surface/composer-state-store':join(appRoot,'src/react-app/domains/session/surface/composer-state-store.ts')},minify:true,plugins:[{name:'fixture-zod',setup(build){build.onResolve({filter:/composer-state-store$/},()=>({path:join(appRoot,'src/react-app/domains/session/surface/composer-state-store.ts')}));build.onResolve({filter:/^zod$/},()=>({path:join(appRoot,'node_modules/zod/index.js')}));}}]});if(!build.success)throw Error(build.logs.map(String).join('\n'));
  if(process.env.MAIL_FIXTURE_BUILD_ONLY==='1')return;
  await writeFile(join(root,'index.html'),'<html><head><meta charset="utf-8"><link rel="stylesheet" href="entry.css"><style>html,body,#root{height:100%;margin:0}</style></head><body><div id="root"></div><script src="entry.js"></script></body></html>');
  const probe=join(root,'probe.cjs');await writeFile(probe,`const {app,BrowserWindow}=require('electron');const assert=require('node:assert/strict');app.setPath('userData',${JSON.stringify(join(root,'profile'))});app.whenReady().then(async()=>{const win=new BrowserWindow({width:1200,height:850,show:false,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true}});win.webContents.on('console-message',(_event,_level,message)=>console.log(message));await win.loadFile(${JSON.stringify(join(root,'index.html'))});const run=s=>win.webContents.executeJavaScript(s);const until=async s=>{for(let i=0;i<300;i++){if(await run(s))return;await new Promise(r=>setTimeout(r,50));}require('node:fs').writeFileSync(${JSON.stringify(join(appRoot,'../../docs/mail/evidence/eig-139-conversation-first-open.png'))},(await win.webContents.capturePage()).toPNG());console.log('BRIDGE_METRICS',await run('JSON.stringify({loads:window.fixtureLoads,messages:window.fixtureMessages})'));console.log('FRAME_METRICS',JSON.stringify(await run("[...document.querySelectorAll('iframe')].map(f=>({height:f.getBoundingClientRect().height,style:f.style.height,html:f.srcdoc}))")));for(const child of win.webContents.mainFrame.frames)console.log('CHILD_METRICS',JSON.stringify(await child.executeJavaScript("({body:document.body?.getBoundingClientRect().toJSON(),scrollHeight:document.body?.scrollHeight,text:document.body?.textContent,spacer:document.querySelector('div')?.outerHTML})").catch(()=>null)));throw Error('renderer deadline '+s+' BODY '+await run('document.body.textContent'))};await until("document.querySelectorAll('.mail-message-row').length===1");await run("document.querySelector('.mail-message-select-row input').click()");assert.equal(await run("document.querySelectorAll('iframe').length"),0);await run("document.querySelector('.mail-message-select-row input').click();document.querySelector('.mail-message-row').click()");await until("document.querySelectorAll('iframe').length===2 && [...document.querySelectorAll('iframe')].every(f=>f.getBoundingClientRect().height>450)");require('node:fs').writeFileSync(${JSON.stringify(join(appRoot,'../../docs/mail/evidence/eig-139-conversation-first-open.png'))},(await win.webContents.capturePage()).toPNG());await run("window.initialFrames=[...document.querySelectorAll('iframe')];window.initialDocs=initialFrames.map(f=>f.srcdoc);window.loads=0;initialFrames.forEach(f=>f.addEventListener('load',()=>window.loads++));document.querySelector('.mail-reader-pane').scrollTop=90");await new Promise(r=>setTimeout(r,11000));assert.equal(await run("initialFrames.every((f,i)=>f===document.querySelectorAll('iframe')[i]&&f.srcdoc===initialDocs[i])"),true);assert.equal(await run("window.loads"),0);assert.equal(await run("document.querySelector('.mail-reader-pane').scrollTop"),90);console.log('MAIL_AUTO_SYNC_PASS');win.destroy();app.quit();}).catch(e=>{console.error(e);app.exit(1)});`);
  const require=createRequire(resolve(appRoot,'../desktop/package.json'));const result=await new Promise<{code:number|null;output:string}>((resolveResult,reject)=>{const child=spawn(require('electron'),[probe],{env:{PATH:process.env.PATH,HOME:process.env.HOME,...(process.platform==='win32'?{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR}:{})},stdio:['ignore','pipe','pipe']});console.log('Synthetic Electron PID',child.pid);let output='';const timer=setTimeout(()=>{child.kill();reject(Error('renderer deadline '+output));},30000);child.stdout.on('data',chunk=>output+=chunk);child.stderr.on('data',chunk=>output+=chunk);child.on('error',reject);child.on('close',code=>{clearTimeout(timer);resolveResult({code,output});});});if(result.code!==0)throw Error(result.output);expect(result.output).toContain('MAIL_AUTO_SYNC_PASS');expect(mutations).toHaveLength(2);expect(polls).toBeGreaterThan(2);
 }finally{server.stop(true);await rm(root,{recursive:true,force:true});}
},45000);
