import {linkTestModules} from '../../../scripts/mail/link-test-modules.mjs';
import {test,expect} from 'bun:test';
import {mkdtemp,writeFile,rm,symlink,mkdir,copyFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,dirname} from 'node:path';import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import {createHash,randomUUID} from 'node:crypto';
test('actual mailbox and search context menus preserve selection and share journal, undo and permissions',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-context-')),appRoot=resolve(import.meta.dir,'..');const calls:unknown[]=[];const actions=new Map<string,unknown>();
 const messages=Array.from({length:27},(_,index)=>({accountId:index===1?'b':index===2?'offline':'a',key:'m'+index,locator:index===2?{provider:'archive',namespace:'11111111-1111-4111-8111-111111111111',entryId:'m2'}:{provider:index===1?'graph':'gmail',messageId:'m'+index},subject:['Vertragsentwurf – Prüfung','Due diligence – Rückfrage','Archivierte Korrespondenz'][index%3]+' '+index,threadId:'thread',rfcMessageId:null,removed:false,memberships:['INBOX'],contentState:'complete',mutationPrecondition:'synthetic-current',metadata:{subject:'Synthetic',from:'Anna Weber <anna@example.test>',to:'Owner <owner@example.test>',cc:null,bcc:null,replyTo:null,date:null,messageId:null},receivedAt:1700000000000-index*1000,rawReferenceId:null,isRead:false,isFlagged:false}));
 const body=Buffer.from(JSON.stringify({version:1,bodies:[{partId:'1',contentType:'text/plain',text:'Guten Morgen, anbei die Unterlagen zur gemeinsamen Prüfung.',presentation:true}]})),sha=createHash('sha256').update(body).digest('hex');
 const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(request){const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'X-LegalWork-Host-Token,Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};if(request.method==='OPTIONS')return new Response(null,{headers});if(request.headers.get('X-LegalWork-Host-Token')!=='synthetic')return new Response(null,{status:401,headers});const path=new URL(request.url).pathname,input=request.method==='POST'?await request.json():{},account=path.match(/accounts\/([^/]+)/)?.[1];let value:unknown;
 if(path.endsWith('/sync')){const count=messages.filter(item=>item.accountId===account).length;value={accountId:account,provider:account==='b'?'graph':account==='offline'?'archive':'gmail',state:'complete',enumerated:count,downloaded:count,projected:count,removed:0,retained:0,failed:0,pending:0,nextRetryAt:null,error:null,...(account==='b'?{inaccessible:0,referenceAttachments:0,unsupportedScopes:['in-place-archive-mailbox']}: {})};}
 else if(path.endsWith('/status')||path.endsWith('/unlock'))value={state:'ready'};
 else if(path.endsWith('/accounts'))value={items:[{id:'a',provider:'gmail',displayName:'Kanzlei · Google'},{id:'b',provider:'graph',displayName:'Transaktionen · Microsoft'},{id:'offline',provider:'archive',displayName:'Lokales Archiv'}],nextCursor:null};
 else if(path.includes('/actions/mutation')){calls.push({account,input});if(account==='b')return Response.json({error:'Synthetic provider unavailable'},{status:409,headers});const action={id:randomUUID(),kind:'mutation',state:'queued',version:{generation:randomUUID(),revision:1},attempts:0,maxAttempts:5,availableAt:0,cancelRequested:false,lastError:null,conflictPolicy:'manual',executionSupported:true,credentialCurrent:true,mutation:input};actions.set(action.id,action);value=action;}
 else if(path.includes('/actions/read'))value=actions.get(input.actionId);
 else if(path.includes('/actions/cancel')){const action=actions.get(input.actionId);value={...Object(action),state:'cancelled',version:{generation:randomUUID(),revision:2}};actions.set(input.actionId,value);calls.push({cancel:input.actionId});}
 else if(path.includes('/actions/query'))value={items:[],nextCursor:null};
 else if(path.endsWith('/folders'))value={items:[{id:'Legal',name:'Legal',parentId:null,kind:account==='a'?'label':'folder',messageCount:0,unreadCount:0}],nextCursor:null};
 else if(path.endsWith('/search/saved'))value={action:'list',items:[],nextCursor:null};
 else if(path.endsWith('/search'))value={items:messages.slice(0,3).map(item=>({accountId:item.accountId,locator:item.locator,subject:item.subject,snippet:'Unterlagen und Rückfragen zum laufenden Mandat.',date:new Date(item.receivedAt).toISOString(),hasAttachment:false})),total:3,pending:0,incomplete:0,nextOffset:null};
 else if(path.endsWith('/messages/query')){const own=messages.filter(item=>item.accountId===account);value={items:input.after?own.slice(24):own.slice(0,24),nextCursor:own.length>24&&!input.after?'next':null};}
 else if(path.endsWith('/messages/read')){await new Promise(resolve=>setTimeout(resolve,40));value=messages.find(item=>item.accountId===account&&JSON.stringify(item.locator)===JSON.stringify(input.locator))??messages[0];}
 else if(path.endsWith('/parts'))value={items:[{key:'body',kind:'body',partId:'',state:'stored',referenceId:'sha256:'+sha,bytes:body.length,sha256:sha,bytesAvailable:true,filename:null,contentType:'application/json',contentId:null}],nextCursor:null};
 else if(path.endsWith('/content'))value={accountId:account,referenceId:'sha256:'+sha,offset:0,totalBytes:body.length,sha256:sha,data:body.toString('base64'),nextOffset:null};
 else value={items:[],nextCursor:null};return Response.json(value,{headers});}});
 try{await linkTestModules(join(appRoot,'node_modules'),join(root,'node_modules'));await writeFile(join(root,'entry.tsx'),`import React from 'react';import{createRoot}from'react-dom/client';import{MemoryRouter}from'react-router-dom';import{MailRoute}from${JSON.stringify(join(appRoot,'src/react-app/domains/mail/mail-route.tsx'))};localStorage.setItem('legalwork.server.urlOverride','http://127.0.0.1:${server.port}');localStorage.setItem('legalwork.server.hostToken','synthetic');localStorage.setItem('legalwork.server.token','synthetic');createRoot(document.getElementById('root')).render(<MemoryRouter><MailRoute/></MemoryRouter>);`);
 const built=await Bun.build({entrypoints:[join(root,'entry.tsx')],target:'browser',outdir:root,alias:{'@':join(appRoot,'src')},minify:true,plugins:[{name:'zod',setup(build){build.onResolve({filter:/^zod$/},()=>({path:join(appRoot,'node_modules/zod/index.js')}));}}]});if(!built.success)throw Error(built.logs.map(String).join('\n'));
 const appRequire=createRequire(join(appRoot,'package.json'));const {compile}=await import(appRequire.resolve('@tailwindcss/node',{paths:[dirname(appRequire.resolve('@tailwindcss/vite'))]}));const css=await compile('@import \"tailwindcss\";',{base:appRoot,onDependency:()=>{}});await writeFile(join(root,'preflight.css'),css.build(['isolate','z-50','relative']));
 await writeFile(join(root,'index.html'),'<meta charset="utf-8"><link rel="stylesheet" href="preflight.css"><style>:root{--foreground:#252525;--background:#fff;--popover:#fff;--muted:#f4f4f4;--muted-foreground:#777;--border:#e5e5e5}body{font:14px system-ui;margin:0}#root{height:100vh}button{font:inherit}</style><link rel="stylesheet" href="entry.css"><div id="root"></div><script src="entry.js"></script>');
 const require=createRequire(resolve(appRoot,'../desktop/package.json'));const result=await new Promise<{code:number|null;output:string}>((done,reject)=>{const child=spawn(process.env.LEGALWORK_TEST_ELECTRON??require('electron'),[join(import.meta.dir,'fixtures/mail-context/probe.cjs'),join(root,'index.html')],{env:{HOME:process.env.HOME,PATH:process.env.PATH,...(process.platform==='win32'?{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR}:{})},stdio:['ignore','pipe','pipe']});let output='';const timer=setTimeout(()=>{child.kill();reject(Error(output));},35000);child.stdout.on('data',v=>output+=v);child.stderr.on('data',v=>output+=v);child.once('error',reject);child.once('close',code=>{clearTimeout(timer);done({code,output});});});if(result.code!==0)throw Error(result.output);expect(result.output).toContain('CONTEXT_PASS');expect(calls).toHaveLength(6);expect(calls[3]).toEqual(expect.objectContaining({account:'a',input:expect.objectContaining({change:{kind:'memberships',add:['Legal'],remove:[]}})}));expect(calls.slice(-2)).toEqual([expect.objectContaining({account:'a',input:expect.objectContaining({locator:messages[0].locator})}),expect.objectContaining({account:'b',input:expect.objectContaining({locator:messages[1].locator})})]);
 const evidence=process.env.MAIL_CONTEXT_EVIDENCE;if(evidence){await mkdir(evidence,{recursive:true});for(const file of ['mailbox.png','search.png','single.png'])await copyFile(join(root,file),join(evidence,file));}
 }finally{server.stop(true);await rm(root,{recursive:true,force:true});}
},45000);
