import {test,expect} from 'bun:test';
import {mkdtemp,writeFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import {pathToFileURL} from 'node:url';import {randomUUID,createHash} from 'node:crypto';

test('Mail keyboard workflows preserve shell/typing, select bulk ranges, restore focus and review sends on both platforms',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-keyboard-workflow-')),appRoot=resolve(import.meta.dir,'..'),mutations:unknown[]=[],submissions:unknown[]=[];let searched=false;const generation=randomUUID();
 const metadata={subject:'Review',from:'sender@example.test',to:'owner@example.test',cc:null,bcc:null,replyTo:null,date:null,messageId:'<original@example.test>'};
 const messages=['one','two','three'].map(id=>({accountId:'a',key:JSON.stringify(['gmail',id]),locator:{provider:'gmail',messageId:id},subject:id+' contract',threadId:null,rfcMessageId:'<original@example.test>',removed:false,memberships:['INBOX'],contentState:'complete',metadata,receivedAt:1000,rawReferenceId:null,isRead:false,isFlagged:false,mutationPrecondition:'gmail:observed'}));
 const raw=Buffer.from('From: sender@example.test\r\nMessage-ID: <original@example.test>\r\n\r\nSynthetic body'),bodyBytes=Buffer.from(JSON.stringify({version:1,bodies:[{partId:'text',contentType:'text/plain',text:'Synthetic body'},{partId:'html',contentType:'text/html',text:'<p>Sender HTML body</p>'}]}));
 const components=[{kind:'raw',bytes:raw,type:'message/rfc822'},{kind:'body',bytes:bodyBytes,type:'application/json'}].map(part=>({...part,hash:createHash('sha256').update(part.bytes).digest('hex')}));
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:async request=>{
  const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'X-LegalWork-Host-Token,Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};if(request.method==='OPTIONS')return new Response(null,{headers});
  const path=new URL(request.url).pathname,input=request.method==='POST'?await request.json():{};let value:unknown={};
  if(path.endsWith('/status')||path.endsWith('/unlock'))value={state:'ready'};
  if(path.endsWith('/accounts'))value={items:[{id:'a',provider:'gmail',displayName:'owner@example.test'}],nextCursor:null};
  if(path.endsWith('/folders'))value={items:[{id:'INBOX',name:'Inbox',kind:'folder',parentId:null,role:'inbox',mutationPrecondition:'folder:one'},{id:'work',name:'Work',kind:'folder',parentId:null,role:null,mutationPrecondition:'folder:two'}],nextCursor:null};
  if(path.endsWith('/sync'))value={state:'complete',enumerated:3,downloaded:3,projected:3,failed:0,pending:0,error:null};
  if(path.endsWith('/messages/query'))value={items:messages,nextCursor:null};
  if(path.endsWith('/messages/read')&&searched)await new Promise(resolve=>setTimeout(resolve,90));
  if(path.endsWith('/messages/read'))value=messages.find(item=>item.locator.messageId===input.locator.messageId);
  if(path.endsWith('/messages/parts'))value={items:components.map(part=>({key:part.kind,kind:part.kind,partId:'',state:'stored',referenceId:'sha256:'+part.hash,bytes:part.bytes.length,sha256:part.hash,bytesAvailable:true,filename:null,contentType:part.type,contentId:null})),nextCursor:null};
  if(path.endsWith('/messages/content')){const part=components.find(part=>'sha256:'+part.hash===input.request.referenceId)!;value={accountId:'a',locator:input.locator,referenceId:input.request.referenceId,offset:input.request.offset,totalBytes:part.bytes.length,sha256:part.hash,data:part.bytes.toString('base64'),nextOffset:null};}
  if(path.endsWith('/events/query'))value={stream:'fixture',nextCursor:1};
  if(path.endsWith('/actions/query'))value={items:[],nextCursor:null};
  if(path.endsWith('/actions/mutation')){mutations.push(input);value={id:randomUUID(),kind:'mutation',state:'succeeded',version:{generation,revision:1},attempts:1,maxAttempts:5,availableAt:Date.now(),cancelRequested:false,lastError:null,conflictPolicy:'manual',executionSupported:true,credentialCurrent:true,providerResult:null,mutation:{locator:input.locator,precondition:input.precondition,change:input.change}};}
  if(path.endsWith('/search')){searched=true;value={items:messages.map(item=>({accountId:item.accountId,locator:item.locator,subject:item.subject,snippet:'Synthetic match',date:null,hasAttachment:false})),total:3,pending:0,incomplete:0,nextOffset:null};}
  if(path.endsWith('/search/saved'))value={action:'list',items:[],nextCursor:null};
  if(path.endsWith('/senders'))value=[{id:'sender',accountId:'a',address:'owner@example.test',displayName:'Owner',source:'provider_verified',available:true,signature:'',defaultNew:true,defaultReply:true,sendMode:'self'}];
  if(path.endsWith('/drafts/query'))value={accountId:'a',items:[],nextCursor:null};
  if(path.endsWith('/drafts/save'))value={id:input.draftId,version:{generation,revision:(input.expected?.revision??0)+1},updatedAt:Date.now(),deleted:false,subject:input.content.subject,content:input.content};
  if(path.endsWith('/outbox'))value=[];
  if(path.endsWith('/outbox/queue')){submissions.push(input);value={id:randomUUID(),accountId:'a',draftId:input.draftId,version:input.version,subject:'Reply',from:'owner@example.test',state:'queued',attempts:0,createdAt:Date.now(),updatedAt:Date.now(),error:null,result:null,cancellationGuaranteed:true};}
  return Response.json(value,{headers});
 }});
 try{
  await symlink(join(appRoot,'node_modules'),join(root,'node_modules'),process.platform==='win32'?'junction':'dir');const entry=join(root,'entry.tsx');
  await writeFile(entry,`import React from 'react';import {createRoot} from 'react-dom/client';import {MemoryRouter} from 'react-router-dom';import {MailRoute} from ${JSON.stringify(join(appRoot,'src/react-app/domains/mail/mail-route.tsx'))};import {mailKeyboard,mailShortcut} from ${JSON.stringify(join(appRoot,'src/react-app/domains/mail/mail-keyboard.ts'))};
localStorage.setItem('legalwork.server.urlOverride','http://127.0.0.1:${server.port}');localStorage.setItem('legalwork.server.hostToken','synthetic');localStorage.setItem('legalwork.server.token','synthetic');window.platform='windows';Object.defineProperty(navigator,'platform',{get:()=>window.platform==='mac'?'MacIntel':'Win32'});window.shellKeys=[];window.addEventListener('keydown',event=>{if(!event.defaultPrevented&&(event.ctrlKey||event.metaKey))window.shellKeys.push(event.key)});window.keys=(selector,key,extra={})=>{const target=typeof selector==='string'?document.querySelector(selector):document.activeElement;if(!target)throw Error('Missing '+selector);target.focus();const event=new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true,...extra});if(extra.altGraph)Object.defineProperty(event,'getModifierState',{value:name=>name==='AltGraph'});target.dispatchEvent(event);return event.defaultPrevented;};window.shortcut=mailShortcut;createRoot(document.getElementById('root')).render(<MemoryRouter><MailRoute/></MemoryRouter>);`);
  const build=await Bun.build({entrypoints:[entry],target:'browser',outdir:root,alias:{'@':join(appRoot,'src')},minify:true,plugins:[{name:'zod',setup(build){build.onResolve({filter:/^zod$/},()=>({path:join(appRoot,'node_modules/zod/index.js')}));}}]});if(!build.success)throw Error(build.logs.map(String).join('\n'));
  await writeFile(join(root,'index.html'),'<meta charset="utf-8"><link rel="stylesheet" href="entry.css"><style>:root{--border:#ddd;--muted:#f4f4f5;--muted-foreground:#666;--background:white;--foreground:#222;--popover:white;--popover-foreground:#222;--ring:#46536a}body{margin:0;font-family:system-ui}#root{height:100vh}button,input,textarea{font:inherit}button{border:0;background:transparent} [role=dialog]{position:fixed;inset:10% 25%;background:white;padding:20px;border:1px solid #aaa;z-index:99}</style><input id="outside" aria-label="Other component"><div id="root"></div><script src="entry.js"></script>');
  const probe=join(root,'probe.cjs');await writeFile(probe,`
const {app,BrowserWindow}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs');app.setPath('userData',${JSON.stringify(join(root,'profile'))});app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1200,height:800,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});await win.loadFile(${JSON.stringify(join(root,'index.html'))});const run=s=>win.webContents.executeJavaScript(s),until=async s=>{for(let i=0;i<200;i++){if(await run(s))return;await new Promise(r=>setTimeout(r,20));}throw Error(s+' BODY '+await run('document.body.textContent'));};const key=(selector,k,extra={})=>run('window.keys('+JSON.stringify(selector)+','+JSON.stringify(k)+','+JSON.stringify(extra)+')');
await until("document.querySelectorAll('.mail-message-row').length===3");
assert.equal(await key('.mail-message-row','ArrowDown'),true);await until("document.querySelectorAll('.mail-message-row')[1]===document.activeElement");
await key(null,'Home');await key(null,'ArrowDown',{shiftKey:true});assert.equal(await run("document.querySelectorAll('.mail-message-select-row input:checked').length"),2);await key(null,'ArrowDown',{shiftKey:true});assert.equal(await run("document.querySelectorAll('.mail-message-select-row input:checked').length"),3);await key(null,'ArrowUp',{shiftKey:true});assert.equal(await run("document.querySelectorAll('.mail-message-select-row input:checked').length"),2);
await key(null,'a',{ctrlKey:true});assert.equal(await run("document.querySelectorAll('.mail-message-select-row input:checked').length"),3);await key(null,'q',{ctrlKey:true});await until("document.querySelector('[aria-label=\\"Mark read\\"]').disabled===false");await key(null,'Escape');assert.equal(await run("document.querySelectorAll('.mail-message-select-row input:checked').length"),0);await key(null,' ');assert.equal(await run("document.querySelectorAll('.mail-message-select-row input:checked').length"),1);await key(null,'Escape');
for(const [k,extra] of [['u',{ctrlKey:true}],['Insert',{}],['e',{}],['Delete',{}]]){await key('.mail-message-row',k,extra);await until("!document.querySelector('[aria-label=\\"Mark read\\"]').disabled");}await until("document.activeElement.classList.contains('mail-message-row')");
for(const [k,extra] of [['n',{ctrlKey:true}],['j',{ctrlKey:true}],['t',{ctrlKey:true}],['k',{ctrlKey:true}],['f',{ctrlKey:true,shiftKey:true}],['Delete',{shiftKey:true}],['r',{ctrlKey:true,altKey:true,altGraph:true}],['r',{isComposing:true}],['Delete',{repeat:true}]])assert.equal(await key('.mail-message-row',k,extra),false);
assert.equal(await key('#outside','r',{ctrlKey:true}),false);await key('.mail-message-row','e',{ctrlKey:true});assert.equal(await run("document.activeElement.getAttribute('aria-label')"),'Search mail');assert.equal(await key(null,'r',{ctrlKey:true}),false);await key(null,'Escape');
await run("Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(document.querySelector('[aria-label=\\"Search mail\\"]'),'contract');document.querySelector('[aria-label=\\"Search mail\\"]').dispatchEvent(new Event('input',{bubbles:true}))");await until("document.querySelectorAll('.mail-search-subject').length===3");
await key('.mail-search-subject','a',{ctrlKey:true});assert.equal(await run("document.querySelectorAll('[aria-label=\\"Search results\\"] input:checked').length"),3);assert.equal(await run("document.querySelector('[aria-label=\\"Mark read\\"]').disabled"),true);await until("!document.querySelector('[aria-label=\\"Mark read\\"]').disabled");await key('.mail-search-subject','Escape');await key('.mail-search-subject','ArrowDown',{shiftKey:true});await key(null,'ArrowDown',{shiftKey:true});await key(null,'ArrowUp',{shiftKey:true});await until("!document.querySelector('[aria-label=\\"Mark read\\"]').disabled");assert.equal(await run("document.querySelectorAll('[aria-label=\\"Search results\\"] input:checked').length"),2);await key(null,'q',{ctrlKey:true});await until("!document.querySelector('[aria-label=\\"Mark read\\"]').disabled");await key(null,'Escape');await key('[aria-label="Search mail"]','Escape');await until("document.querySelectorAll('.mail-message-row').length===3");
await key('.mail-message-row','y',{ctrlKey:true});await until("!!document.activeElement.closest('.mail-folders')");await key(null,'ArrowDown');await key(null,'F6');await until("!!document.activeElement.closest('.mail-message-list')");await key(null,'Enter');await until("document.activeElement.id==='mail-print-root'");await key(null,'Escape');await until("document.activeElement.classList.contains('mail-message-row')");
await key('.mail-message-row','?');await until("!!document.querySelector('[role=dialog]')");assert.equal(await key('[role=dialog]','Delete'),false);fs.writeFileSync(${JSON.stringify(join(tmpdir(),'eig175-keyboard-help.png'))},(await win.webContents.capturePage()).toPNG());await key('[role=dialog]','Escape');await until("!document.querySelector('[role=dialog]')");assert.equal(await run("document.activeElement.getAttribute('aria-label')"),'Mail keyboard shortcuts');
await key('.mail-message-row','n');await until("!!document.querySelector('[aria-label=\\"Compose message\\"]')");await until("document.activeElement.getAttribute('aria-label')==='To'");assert.equal(await key(null,'Delete'),false);assert.equal(await key(null,'Enter',{ctrlKey:true}),true);assert.equal(await run("!!document.querySelector('[role=dialog]')"),false);await key('[aria-label="Close composer"]','Escape');await until("!document.querySelector('[aria-label=\\"Compose message\\"]')");await until("document.activeElement.classList.contains('mail-message-row')");
await until("!document.querySelector('[aria-label=Reply]').disabled");await key('.mail-message-row','f',{ctrlKey:true});await until("!!document.querySelector('.mail-composer')");assert.equal(await run("document.querySelector('[aria-label=Subject]').value.startsWith('Fwd:')"),true);await run("document.querySelector('[aria-label=\\"Toggle rich text\\"]').click()");await until("!!document.querySelector('[aria-label=\\"Rich message body\\"]')");assert.equal(await key('[aria-label=\"Rich message body\"]','r',{ctrlKey:true}),false);assert.equal(await key(null,'Delete'),false);assert.equal(await key(null,'s',{ctrlKey:true}),true);await key('[aria-label=\"Close composer\"]','Escape');await until("!document.querySelector('.mail-composer')");
await until("!!document.querySelector('iframe') && document.querySelector('iframe').style.height!=='160px'");win.show();win.focus();await new Promise(r=>setTimeout(r,80));
win.webContents.debugger.attach('1.3');const frameKey=async key=>{await win.webContents.debugger.sendCommand('Input.dispatchKeyEvent',{type:'keyDown',key});await win.webContents.debugger.sendCommand('Input.dispatchKeyEvent',{type:'keyUp',key});};const focusSender=async()=>{const point=await run("(()=>{const r=document.querySelector('iframe').getBoundingClientRect();return{x:Math.round(r.left+40),y:Math.round(r.top+20)}})()");await win.webContents.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await win.webContents.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});await new Promise(r=>setTimeout(r,30));};
const sender=win.webContents.mainFrame.frames.find(frame=>frame.url==='about:srcdoc');assert.ok(sender);await sender.executeJavaScript("window.trustedKeys=[];document.addEventListener('keydown',e=>{if(e.isTrusted)window.trustedKeys.push(e.key)});document.body.tabIndex=0;document.body.focus();document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'r',bubbles:true}))");assert.equal(await run("!!document.querySelector('.mail-composer')"),false);const nonce=await sender.executeJavaScript("document.querySelector('script').nonce");await run("window.postMessage("+JSON.stringify({type:'mail-reader-key',token:nonce,key:'r',ctrlKey:false,metaKey:false,altKey:false,shiftKey:false})+",'*')");await sender.executeJavaScript("parent.postMessage({type:'mail-reader-key',token:'wrong',key:'r',ctrlKey:false,metaKey:false,altKey:false,shiftKey:false},'*')");await sender.executeJavaScript("parent.postMessage({type:'mail-reader-key',token:document.querySelector('script').nonce,key:'Delete',ctrlKey:false,metaKey:false,altKey:false,shiftKey:false},'*')");await new Promise(r=>setTimeout(r,30));assert.equal(await run("!!document.querySelector('.mail-composer')"),false);
await focusSender();await frameKey('/');await until("document.activeElement.getAttribute('aria-label')==='Search mail'");await key(null,'Escape');
await focusSender();await sender.executeJavaScript("document.body.focus();getSelection().selectAllChildren(document.querySelector('p'))");await frameKey('r');assert.ok((await sender.executeJavaScript('window.trustedKeys')).includes('r'));assert.equal(await run("!!document.querySelector('.mail-composer')"),false);await focusSender();await sender.executeJavaScript("getSelection().removeAllRanges();document.body.focus()");await frameKey('r');await until("!!document.querySelector('.mail-composer')");await key('[aria-label="Close composer"]','Escape');await until("!document.querySelector('.mail-composer')");
win.webContents.debugger.detach();const {createApplicationMenu}=await import(${JSON.stringify(pathToFileURL(resolve(appRoot,'../desktop/electron/app-menu.mjs')).href)});const {Menu}=require('electron');createApplicationMenu({appName:'Mail keyboard fixture',getWindow:async()=>win,collectSupportLogs:async()=>{}}).install();await run("window.platform="+JSON.stringify(process.platform==='darwin'?'mac':'windows')+";document.querySelector('.mail-message-row').focus()");await until("!document.querySelector('[aria-label=Reply]').disabled");Menu.getApplicationMenu().getMenuItemById('app-force-reload').click({triggeredByAccelerator:true},win);await until("!!document.querySelector('.mail-composer')");await key('[aria-label="Close composer"]','Escape');await until("!document.querySelector('.mail-composer')");await until("!document.querySelector('[aria-label=Reply]').disabled");await run("document.querySelector('.mail-message-row').focus()");Menu.getApplicationMenu().getMenuItemById('app-reload').click({triggeredByAccelerator:true},win);await until("!!document.querySelector('.mail-composer')");await until("document.activeElement.getAttribute('aria-label')==='Message body'");await run("window.repeatComposer=document.querySelector('.mail-composer')");for(let i=0;i<4;i++)Menu.getApplicationMenu().getMenuItemById('app-reload').click({triggeredByAccelerator:true},win);await new Promise(r=>setTimeout(r,100));assert.equal(await run("window.repeatComposer===document.querySelector('.mail-composer')"),true);await key('[aria-label="Close composer"]','Escape');await until("!document.querySelector('.mail-composer')");await run("window.platform='windows'");
await until("!document.querySelector('[aria-label=Reply]').disabled");await key('.mail-message-row','r',{ctrlKey:true});await until("!!document.querySelector('[aria-label=\\"Compose message\\"]')");await until("!document.querySelector('[aria-label=Send]').disabled");await key('[aria-label="Message body"]','s',{ctrlKey:true});await key(null,'Enter',{ctrlKey:true});await until("!!document.querySelector('[role=dialog]')");await until("document.activeElement.textContent==='Cancel'");await key(null,'Enter',{ctrlKey:true});await until("document.activeElement.textContent==='Cancel'");await key(null,'Escape');await until("!document.querySelector('[role=dialog]')");await until("document.activeElement.getAttribute('aria-label')==='Message body'");
await run("window.platform='mac'");for(const [k,extra] of [['j',{metaKey:true}],['t',{metaKey:true}],['q',{metaKey:true}],['n',{metaKey:true}],['f',{metaKey:true,shiftKey:true}]])assert.equal(await key('[aria-label="Message body"]',k,extra),false);
await key('[aria-label="Message body"]','Enter',{metaKey:true});await until("!!document.querySelector('[role=dialog]')");await until("document.activeElement.textContent==='Cancel'");await run("[...document.querySelector('[role=dialog]').querySelectorAll('button')].find(b=>b.textContent==='Confirm send').focus()");win.show();win.focus();await new Promise(r=>setTimeout(r,80));await run("[...document.querySelector('[role=dialog]').querySelectorAll('button')].find(b=>b.textContent==='Confirm send').focus()");assert.equal(await run('document.activeElement.disabled'),false);await win.webContents.sendInputEvent({type:'keyDown',keyCode:'Return'});await win.webContents.sendInputEvent({type:'char',keyCode:'\\r'});await win.webContents.sendInputEvent({type:'keyUp',keyCode:'Return'});await until("!!document.querySelector('[aria-label=Outbox]')");
await key('.mail-message-row','f',{metaKey:true,altKey:true});assert.equal(await run("document.activeElement.getAttribute('aria-label')"),'Search mail');assert.equal(await run("window.shortcut('forward','mac').hint"),'Shift+F');await run("window.reloadMarker=true;document.querySelector('#outside').focus()");Menu.getApplicationMenu().getMenuItemById('app-reload').click({triggeredByAccelerator:true},win);await until('!window.reloadMarker');await until("document.querySelectorAll('.mail-message-row').length===3");await run("window.reloadMarker=true;document.querySelector('.mail-message-row').focus()");Menu.getApplicationMenu().getMenuItemById('app-reload').click({},win);await until('!window.reloadMarker');console.log('MAIL_KEYBOARD_WORKFLOW_PASS');win.destroy();app.quit();}).catch(error=>{console.error(error);app.exit(1)});
`);
  const require=createRequire(resolve(appRoot,'../desktop/package.json'));const result=await new Promise<{code:number|null;output:string}>((done,reject)=>{const child=spawn(require('electron'),[probe],{env:{HOME:process.env.HOME,PATH:process.env.PATH,...process.platform==='win32'?{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR}:{}},stdio:['ignore','pipe','pipe']});let output='';const timer=setTimeout(()=>{child.kill();reject(Error(output));},25000);child.stdout.on('data',value=>output+=value);child.stderr.on('data',value=>output+=value);child.on('error',reject);child.on('close',code=>{clearTimeout(timer);done({code,output});});});if(result.code!==0)throw Error(result.output);expect(result.output).toContain('MAIL_KEYBOARD_WORKFLOW_PASS');expect(mutations).toHaveLength(9);expect(submissions).toHaveLength(1);
 }finally{server.stop(true);await rm(root,{recursive:true,force:true});}
},35000);
