import { test, expect } from 'bun:test';
import { mkdtemp,writeFile,rm,copyFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import { createHash,randomUUID } from 'node:crypto';
import { mailDraftSaveSchema,type MailDraftView } from '../../server/src/mail/local-view';
import type {MailMessageView} from '../src/react-app/domains/mail/mail-client';
import { replyCompose } from '../src/react-app/domains/mail/mail-compose-model';

test('reply-all excludes sender/duplicates/BCC and preserves reference chain; forwarding clears reply headers',()=>{
 const item:MailMessageView={accountId:'a',key:'one',locator:{provider:'gmail',messageId:'one'},subject:'Case',threadId:'thread',rfcMessageId:'<parent@example.test>',removed:false,memberships:[],contentState:'complete',metadata:{subject:'Case',from:'Partner <partner@example.test>',replyTo:'Reply <reply@example.test>',to:'Me <me@example.test>, Client <client@example.test>',cc:'client@example.test, counsel@example.test, me@example.test',bcc:'hidden@example.test',date:'Yesterday',messageId:'<parent@example.test>'}};
 const reply=replyCompose(item,'秘密\nSecond line','reply-all','me@example.test',['<root@example.test>']);expect(reply.to).toEqual(['reply@example.test','client@example.test']);expect(reply.cc).toEqual(['counsel@example.test']);expect(reply.bcc).toEqual([]);expect(reply.references).toEqual(['<root@example.test>','<parent@example.test>']);expect(reply.text).toContain('> 秘密\n> Second line');const forward=replyCompose(item,'Original','forward','me@example.test');expect(forward.inReplyTo).toBeNull();expect(forward.references).toEqual([]);expect(forward.to).toEqual([]);
});

test('isolated compose UI saves/reopens incomplete work, formats safely, attaches files and keeps Send unavailable',async()=>{
 const root=await mkdtemp(join(tmpdir(),'mail-compose-ui-')),app=resolve(import.meta.dir,'..');const saved=new Map<string,MailDraftView>(),uploads=new Map<string,Buffer>();let saveCount=0;
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:async request=>{
  const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'X-LegalWork-Host-Token,Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};if(request.method==='OPTIONS')return new Response(null,{headers});expect(request.headers.get('X-LegalWork-Host-Token')).toBe('synthetic');const path=new URL(request.url).pathname,input=request.method==='GET'?{}:await request.json();let value:unknown;
  if(path.endsWith('/senders'))value=[{id:'self',accountId:'a',address:'me@example.test',displayName:'',source:'provider_verified',available:true,signature:'',defaultNew:true,defaultReply:true,sendMode:'self'}];
  else if(path.endsWith('/sync/read'))value={accountId:'a',draftId:input.draftId,state:'local',enabled:false,dirty:false,revision:0,remote:null,remoteHash:null,error:null,operation:'upsert',updatedAt:0};
  else if(path.endsWith('/save')){const parsed=mailDraftSaveSchema.parse(input),old=saved.get(parsed.draftId);if(JSON.stringify(parsed.expected)!==JSON.stringify(old?.version??null))return Response.json({error:'conflict'},{status:409,headers});const content=mailDraftSaveSchema.parse(input).content;const item:MailDraftView={id:parsed.draftId,version:{generation:old?.version.generation??randomUUID(),revision:(old?.version.revision??0)+1},updatedAt:Date.now(),deleted:false,subject:content.subject,content};saved.set(item.id,item);saveCount++;value=item;}
  else if(path.endsWith('/query'))value={accountId:'a',items:[...saved.values()].map(({content,...summary})=>summary),nextCursor:null};
  else if(path.endsWith('/read'))value=saved.get(input.draftId);
  else if(path.endsWith('/attachment')){const draft=saved.get(input.draftId),part=draft?.content.attachments[input.ordinal],bytes=uploads.get(part?.partId??'')??Buffer.alloc(0),end=Math.min(bytes.length,input.offset+input.limit);value={draftId:input.draftId,version:input.version,ordinal:input.ordinal,chunk:{accountId:'a',locator:null,referenceId:part?.referenceId,offset:input.offset,totalBytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),data:bytes.subarray(input.offset,end).toString('base64'),nextOffset:end===bytes.length?null:end}};}
  else if(path.endsWith('/upload')){const old=uploads.get(input.uploadId)??Buffer.alloc(0),bytes=Buffer.concat([old,Buffer.from(input.data,'base64')]);uploads.set(input.uploadId,bytes);value={uploadId:input.uploadId,nextOffset:bytes.length,bytes:bytes.length,referenceId:input.complete?'draft:sha256:'+createHash('sha256').update(bytes).digest('hex'):null};}
  else return new Response('unknown',{status:404,headers});return Response.json(value,{headers});
 }});
 try{
  const entry=join(root,'entry.tsx');await writeFile(entry,`
   import React,{useState} from ${JSON.stringify(join(app,'node_modules/react/index.js'))};import{createRoot}from ${JSON.stringify(join(app,'node_modules/react-dom/client.js'))};
   import{MailComposer,MailDrafts}from ${JSON.stringify(join(app,'src/react-app/domains/mail/mail-composer.tsx'))};import{MailClient}from ${JSON.stringify(join(app,'src/react-app/domains/mail/mail-client.ts'))};import{emptyCompose}from ${JSON.stringify(join(app,'src/react-app/domains/mail/mail-compose-model.ts'))};
   const transport=async(input,init)=>{if(window.__holdReads&&String(input).endsWith('/drafts/read')){window.__readHeld=true;await new Promise(resolve=>window.__releaseRead=resolve);const response=await fetch(input,{...init,signal:undefined});window.__readReturned=true;return response;}return fetch(input,init);};
   const makeClient=()=>new MailClient('http://127.0.0.1:${server.port}','synthetic',transport),accounts=[{id:'a',provider:'gmail',displayName:'me@example.test'}];
   function Fixture(){const[client,setClient]=useState(makeClient),[visible,setVisible]=useState(true),[selection,set]=useState({account:'a',id:crypto.randomUUID(),version:null,content:emptyCompose('me@example.test')});window.__swapClient=()=>setClient(makeClient());if(!visible)return React.createElement('div',null,'Left drafts');return selection?React.createElement(MailComposer,{key:selection.id,client,accounts,initial:selection,onClose:()=>set(null),onSwitch:set}):React.createElement(MailDrafts,{client,accounts,onOpen:value=>{window.__opens=(window.__opens||0)+1;set(value);},onClose:()=>setVisible(false)})}
   createRoot(document.getElementById('root')).render(React.createElement(Fixture));
  `);
  const result=await Bun.build({entrypoints:[entry],outdir:root,target:'browser',minify:true,plugins:[{name:'zod',setup(build){build.onResolve({filter:/^zod$/},()=>({path:join(app,'node_modules/zod/index.js')}));}}]});if(!result.success)throw Error(result.logs.map(String).join('\n'));
  const css=await Bun.file(join(app,'src/react-app/domains/mail/mail-reader.css')).text();await writeFile(join(root,'index.html'),`<meta charset="utf-8"><style>:root{--border:#ddd;--foreground:#222;--muted:#eee}body{font-family:system-ui;margin:0;height:700px}#root{height:100%}${css}</style><div id="root"></div><script src="entry.js"></script>`);
  const probe=join(root,'probe.cjs');await writeFile(probe,`
   const{app,BrowserWindow}=require('electron'),assert=require('node:assert/strict');app.setPath('userData',${JSON.stringify(join(root,'profile'))});app.whenReady().then(async()=>{
    const win=new BrowserWindow({show:false,width:900,height:760,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false}});await win.loadFile(${JSON.stringify(join(root,'index.html'))});const run=code=>win.webContents.executeJavaScript(code).catch(error=>{console.error('FAILED CODE',code);throw error;});win.webContents.on('console-message',(_,level,message)=>console.error('renderer',message));const until=async code=>{for(let i=0;i<300;i++){if(await run(code))return;await new Promise(r=>setTimeout(r,20));}throw Error('UI timeout '+code+' '+await run('document.body.textContent'));};
    await until("document.body.textContent.includes('Saved locally')");
    const set=async(label,value)=>run("(()=>{const el=document.querySelector('[aria-label='+JSON.stringify("+JSON.stringify(label)+")+']');Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(el,"+JSON.stringify(value)+");el.dispatchEvent(new Event('input',{bubbles:true}));})()");
    await set('To','unfinished@');await set('Bcc','private@example.test');await set('Subject','Prüfung 秘密');await set('Message body','Draft survives navigation 秘密');await until("document.body.textContent.includes('Saved locally')");
    assert.equal(await run("[...document.querySelectorAll('button')].find(x=>x.textContent==='Send').disabled"),true);
    await run("document.querySelector('[aria-label=\\\"Close composer\\\"]').click()");await until("!!document.querySelector('[aria-label=\\\"Saved drafts\\\"]')");await until("!!document.querySelector('.mail-draft-row')");await run("document.querySelector('.mail-draft-row').click()");await until("!!document.querySelector('[aria-label=\\\"Message body\\\"]')");assert.equal(await run("document.querySelector('[aria-label=To]').value"),'unfinished@');assert.equal(await run("document.querySelector('[aria-label=Bcc]').value"),'private@example.test');
    await run("document.querySelector('[aria-label=\\\"Toggle rich text\\\"]').click()");await until("!!document.querySelector('[contenteditable]')");
    await run("(()=>{const el=document.querySelector('[contenteditable]');el.innerHTML='<p>Rich <b>秘密</b><script>window.pwned=true<'+ '/script><img src=https://example.invalid/tracker></p>';el.dispatchEvent(new Event('input',{bubbles:true}));})()");await until("document.body.textContent.includes('Saved locally')");assert.equal(await run("!!document.querySelector('[contenteditable] script')"),false);assert.equal(await run("!!document.querySelector('[contenteditable] img')"),false);
    await run("(()=>{const transfer=new DataTransfer();transfer.items.add(new File(['Synthetic attachment'], '秘密.txt',{type:'text/plain'}));const el=document.querySelector('input[type=file]');el.files=transfer.files;el.dispatchEvent(new Event('change',{bubbles:true}));})()");await until("document.body.textContent.includes('秘密.txt')&&document.body.textContent.includes('Saved locally')");
    await run("document.querySelector('[aria-label=\\\"Close composer\\\"]').click()");await until("!!document.querySelector('.mail-draft-row')");await until("!!document.querySelector('.mail-draft-row')");await run("document.querySelector('.mail-draft-row').click()");await until("document.body.textContent.includes('秘密.txt')");
    await run("(()=>{const transfer=new DataTransfer();transfer.items.add(new File([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jS1kAAAAASUVORK5CYII='),c=>c.charCodeAt(0))], 'pixel.png',{type:'image/png'}));const el=document.querySelectorAll('input[type=file]')[1];el.files=transfer.files;el.dispatchEvent(new Event('change',{bubbles:true}));})()");await until("!!document.querySelector('[contenteditable] img[src^=blob]')&&document.body.textContent.includes('Saved locally')");
    await win.capturePage().then(image=>require('node:fs').writeFileSync(${JSON.stringify(join(root,'compose.png'))},image.toPNG()));
    await run("document.querySelector('[aria-label=\\\"Close composer\\\"]').click()");await until("!!document.querySelector('.mail-draft-row')");const opens=await run('window.__opens');
    await run("window.__holdReads=true;document.querySelector('.mail-draft-row').click()");await until('window.__readHeld');await run('window.__swapClient()');await until("!!document.querySelector('.mail-draft-row')");await run('window.__releaseRead()');await until('window.__readReturned');await new Promise(r=>setTimeout(r,30));assert.equal(await run('window.__opens'),opens);assert.equal(await run("!!document.querySelector('[aria-label=\\\"Compose message\\\"]')"),false);
    await run("window.__readHeld=false;window.__readReturned=false;document.querySelector('.mail-draft-row').click()");await until('window.__readHeld');await run("document.querySelector('[aria-label=\\\"Close drafts\\\"]').click()");await until("document.body.textContent.includes('Left drafts')");await run('window.__releaseRead()');await until('window.__readReturned');await new Promise(r=>setTimeout(r,30));assert.equal(await run('window.__opens'),opens);assert.equal(await run("document.body.textContent.includes('Left drafts')"),true);
    console.log('COMPOSE_PASS');app.exit(0);
   }).catch(error=>{console.error(error);app.exit(1)});
  `);
  const require=createRequire(resolve(app,'../desktop/package.json'));const outcome=await new Promise<{code:number|null;output:string}>((done,reject)=>{const child=spawn(require('electron'),[probe],{env:{PATH:process.env.PATH,HOME:process.env.HOME,...(process.platform==='win32'?{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR}:{})},stdio:['ignore','pipe','pipe']});let output='';const timer=setTimeout(()=>{child.kill();reject(Error(output+' compose UI timeout'));},20000);child.stdout.on('data',value=>output+=value);child.stderr.on('data',value=>output+=value);child.on('error',reject);child.on('close',code=>{clearTimeout(timer);done({code,output});});});if(outcome.code!==0)throw Error(outcome.output);expect(outcome.output).toContain('COMPOSE_PASS');expect(saveCount).toBeGreaterThan(4);expect([...saved.values()][0].content.attachments).toHaveLength(2);if(process.env.EIG142_SCREENSHOT)await copyFile(join(root,'compose.png'),process.env.EIG142_SCREENSHOT);
 }finally{server.stop(true);await rm(root,{recursive:true,force:true});}
},30000);
