import {createHash} from 'node:crypto';
import {ImapFlow,type ImapFlowOptions} from 'imapflow';
import type {ImapSettings} from './imap-config.js';
import {DraftProviderError,type DraftAdapter,type RemoteDraft} from './draft-adapter.js';
import type {DraftRemoteRef} from '../draft-sync-view.js';
export class ImapDraftAdapter implements DraftAdapter{
 readonly replaceMode='copy_then_delete';private client:ImapFlow;private folder='';
 constructor(settings:ImapSettings,password:string,factory:(options:ImapFlowOptions)=>ImapFlow=options=>new ImapFlow(options),private beforeMutation:()=>void=()=>{}){this.client=factory({host:settings.host,port:settings.port,secure:true,auth:{user:settings.username,pass:password},tls:{rejectUnauthorized:true,minVersion:'TLSv1.2'},logger:false,emitLogs:false,logRaw:false,disableAutoIdle:true,disableCompression:true,disableBinary:true,qresync:true,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:30000,maxLiteralSize:32*1024*1024,maxResponseSize:34*1024*1024});this.client.on('error',()=>this.close());}
 async connect(signal:AbortSignal){signal.addEventListener('abort',()=>this.close(),{once:true});if(signal.aborted)throw new DraftProviderError('retryable');await this.client.connect();if(!this.client.secureConnection)throw new DraftProviderError('permission');const folders=await this.client.list(),selected=folders.filter(folder=>folder.specialUse==='\\Drafts'&&!folder.flags.has('\\Noselect'));if(selected.length!==1||!this.client.capabilities.has('UIDPLUS'))throw new DraftProviderError('unsupported');this.folder=selected[0].path;}
 close(){this.client.close();}
 private check(signal:AbortSignal){if(signal.aborted)throw new DraftProviderError('retryable');}
 async read(ref:DraftRemoteRef,signal:AbortSignal,verifyDeleted=false):Promise<RemoteDraft|null>{this.check(signal);if(ref.folder!==this.folder||!ref.uidValidity||!/^\d+$/.test(ref.id))throw new DraftProviderError('remote_changed');const opened=await this.client.mailboxOpen(this.folder,{readOnly:!verifyDeleted});if(Number(opened.uidValidity)!==ref.uidValidity)throw new DraftProviderError('remote_changed');const item=await this.client.fetchOne(ref.id,{uid:true,flags:true},{uid:true});if(!item)return null;if(!item.flags?.has('\\Draft'))throw new DraftProviderError('remote_changed');if(verifyDeleted&&!item.flags.has('\\Deleted'))throw new DraftProviderError('remote_changed');if(!verifyDeleted&&item.flags.has('\\Deleted'))return null;const download=await this.client.download(ref.id,undefined,{uid:true,maxBytes:30*1024*1024+1,chunkSize:65536}),chunks:Uint8Array[]=[];let size=0;for await(const value of download.content){this.check(signal);if(!(value instanceof Uint8Array)||(size+=value.length)>30*1024*1024)throw new DraftProviderError('unsupported');chunks.push(value);}const raw=Buffer.concat(chunks),hash=createHash('sha256').update(raw).digest('hex');return{ref:{...ref,version:item.modseq?.toString()??hash},raw,hash};}
 async find(messageId:string,signal:AbortSignal){this.check(signal);const mailbox=await this.client.mailboxOpen(this.folder,{readOnly:true}),uids=await this.client.search({header:{'Message-ID':messageId}},{uid:true});if(!uids)return[];if(uids.length>100)throw new DraftProviderError('unsupported');const found:RemoteDraft[]=[];for(const uid of uids){const draft=await this.read({id:String(uid),version:'unknown',messageId,folder:this.folder,uidValidity:Number(mailbox.uidValidity)},signal);if(draft&&Buffer.from(draft.raw).toString('latin1').split(/\r?\n\r?\n/,1)[0].match(/^Message-ID:[ \t]*(.+)$/im)?.[1].trim()===messageId)found.push(draft);}return found;}
 async create(raw:Uint8Array,signal:AbortSignal){this.check(signal);this.beforeMutation();const added=await this.client.append(this.folder,Buffer.from(raw),['\\Draft']);if(!added||!added.uid||!added.uidValidity)throw new DraftProviderError('provider_rejected');const draft=await this.read({id:String(added.uid),version:'unknown',messageId:null,folder:this.folder,uidValidity:Number(added.uidValidity)},signal);if(!draft)throw new DraftProviderError('provider_rejected');return draft;}
 async replace(_ref:DraftRemoteRef,_raw:Uint8Array,_signal:AbortSignal):Promise<RemoteDraft>{throw new DraftProviderError('unsupported');}
 async remove(ref:DraftRemoteRef,signal:AbortSignal){this.check(signal);const current=await this.read(ref,signal);if(!current)return;if(current.ref.version!==ref.version)throw new DraftProviderError('remote_changed');const writable=await this.client.mailboxOpen(this.folder,{readOnly:false});if(Number(writable.uidValidity)!==ref.uidValidity)throw new DraftProviderError('remote_changed');this.check(signal);this.beforeMutation();if(!await this.client.messageFlagsAdd(ref.id,['\\Deleted'],{uid:true,...(/^\d+$/.test(ref.version)&&this.client.enabled.has('CONDSTORE')?{unchangedSince:BigInt(ref.version)}:{})}))throw new DraftProviderError('remote_changed');const verified=await this.read(ref,signal,true);if(!verified)return;if(verified.hash!==current.hash||(this.client.enabled.has('CONDSTORE')&&/^\d+$/.test(ref.version)&&(!/^\d+$/.test(verified.ref.version)||BigInt(verified.ref.version)<=BigInt(ref.version))))throw new DraftProviderError('remote_changed');this.beforeMutation();if(!await this.client.messageDelete(ref.id,{uid:true}))throw new DraftProviderError('provider_rejected');}
}
