import {z} from 'zod';
import {OutboxStore,type OutboxRow} from '../storage/outbox.js';
import type {MailDatabase} from '../storage/database-interface.js';
import type {MailAccessCoordinator} from '../providers/access-coordinator.js';
import {MailContentStore} from '../storage/content-store.js';
import {SmtpCustody} from '../storage/smtp-custody.js';
import {ImapCustody} from '../storage/imap-custody.js';
import {GraphMailboxRepository} from '../storage/graph-mailboxes.js';
import {DraftSyncStore} from '../storage/draft-sync.js';
import {SmtpSubmission,SubmissionFailure} from '../providers/smtp-submit.js';
import {HttpSubmission} from '../providers/http-submit.js';
import {smtpSentCopy} from '../providers/sent-copy.js';
import {OutboxError,outboxResultSchema,type OutboxResult,type OutboxErrorCode} from '../outbox-view.js';
export type OutboxConnection={prepare(row:OutboxRow):Promise<string|null>;send(row:OutboxRow,draftId:string|null):Promise<OutboxResult>;reconcile(row:OutboxRow):Promise<OutboxResult|null>;close():void};
export class OutboxRunner{
 private store:OutboxStore;private controller=new AbortController();private running:Promise<void>|undefined;private timer:ReturnType<typeof setInterval>|undefined;private closed=false;
 constructor(private options:{database:MailDatabase;ownerId:string;access:MailAccessCoordinator;connection?:(row:OutboxRow,signal:AbortSignal)=>Promise<OutboxConnection>}){this.store=new OutboxStore(options.database,options.ownerId);}
 private async connection(row:OutboxRow,signal:AbortSignal):Promise<OutboxConnection>{if(this.options.connection)return this.options.connection(row,signal);const provider=this.store.account(row.account_id);this.store.assert(row);
  if(provider==='imap'){const credential=new SmtpCustody(this.options.database,this.options.ownerId).read(row.account_id);const smtp=new SmtpSubmission(credential.settings,credential.password,signal);try{await smtp.prepare();}catch(error){smtp.close();throw error;}return{prepare:async()=>null,send:async row=>{const result=await smtp.send(this.store.envelope(row),row.mime_bytes);return{...result,sentCopy:credential.settings.sentCopy==='provider'?'provider':'pending'};},reconcile:async row=>{const imap=new ImapCustody(this.options.database,this.options.ownerId).read(row.account_id);const saved=await smtpSentCopy({settings:imap.settings,password:imap.password,raw:row.api_mime_bytes,messageId:row.message_id,from:this.store.envelope(row).from,signal,append:false,fence:()=>this.store.assert(row)});return saved==='saved'?{accepted:[],rejected:[],providerId:null,sentCopy:'saved',delivery:'unknown',reconciled:true}:null;},close:()=>smtp.close()};}
  const granted=await this.options.access.acquire(row.account_id);this.store.assert(row);if(granted.version.generation!==row.credential_generation)throw new OutboxError('credentials_changed');const http=new HttpSubmission(provider,granted.accessToken,signal);
  return{prepare:row=>http.prepare({raw:row.api_mime_bytes,content:this.store.content(row),messageId:row.message_id,previous:row.preparation_json?JSON.parse(row.preparation_json):null,attachment:part=>Buffer.concat([...new MailContentStore(this.options.database,this.options.ownerId).read(row.account_id,part.referenceId)]),persist:value=>this.store.preparation(row,value),fence:()=>{if(signal.aborted)throw new OutboxError('preparation_unknown');this.store.assert(row);}}),send:(row,draftId)=>http.send(row.api_mime_bytes,this.store.envelope(row),draftId),reconcile:row=>http.reconcile(row.message_id,this.store.envelope(row).from),close:()=>{}};
 }
 private accounts(){return this.options.database.all("SELECT DISTINCT o.account_id FROM mail_outbox o JOIN mail_accounts a ON a.id=o.account_id WHERE a.owner_id=?",[this.options.ownerId]).map(row=>z.string().parse(row.account_id));}
 /** Exclusive encrypted worker startup: abandoned dispatches become uncertain, never queued. */
 recover(){for(const accountId of this.accounts()){this.options.database.run("UPDATE mail_action_jobs SET lease_until=0 WHERE account_id=? AND kind='submission' AND state IN ('running','dispatching')",[accountId]);this.store.journal.recoverExpired(accountId);for(const row of this.store.list(accountId))if(row.state==='uncertain')this.store.error(this.store.row(accountId,row.id),'outcome_unknown');}}
 resume(){if(this.closed||this.timer)return;if(this.controller.signal.aborted)this.controller=new AbortController();this.timer=setInterval(()=>void this.run().catch(()=>{}),2000);this.timer.unref();void this.run().catch(()=>{});}
 async suspend(){if(this.timer)clearInterval(this.timer);this.timer=undefined;this.controller.abort();await this.running;}
 async close(){this.closed=true;await this.suspend();}
 run(){if(this.running)return this.running;if(this.closed||this.controller.signal.aborted)return Promise.resolve();this.running=this.work().finally(()=>{this.running=undefined;});return this.running;}
 private async work(){for(const accountId of this.accounts()){if(this.controller.signal.aborted)return;this.store.journal.recoverExpired(accountId);await this.turn(accountId);for(const item of this.store.list(accountId)){if(this.controller.signal.aborted)return;if(item.state==='accepted')await this.cleanup(this.store.row(accountId,item.id),false);}}}
 async turn(accountId:string){const claimed=this.store.journal.claim(accountId,300000,'submission');if(!claimed)return;let row:OutboxRow;try{row=this.store.row(accountId,claimed.lease.id);}catch{this.store.journal.failBeforeDispatch(claimed.lease,false);return;}let connection:OutboxConnection|undefined,dispatched=false;const signal=AbortSignal.any([this.controller.signal,AbortSignal.timeout(240000)]);
  this.store.attempt(row,claimed.status.attempts,'preparing');
  try{this.store.assert(row);connection=await this.connection(row,signal);const draftId=await connection.prepare(this.store.row(accountId,row.action_id));this.store.assert(row);if(signal.aborted)throw new OutboxError('retryable');this.options.database.transaction(()=>{this.store.journal.markDispatched(claimed.lease);this.store.attempt(row,claimed.status.attempts,'dispatching');});dispatched=true;
   const result=await connection.send(row,draftId);
   // Record known acceptance even if cancellation or credential revocation raced the response.
   this.options.database.transaction(()=>{const status=this.store.journal.read(accountId,row.action_id);if(status.state==='uncertain')this.store.journal.reconcile(accountId,row.action_id,status.version,'succeeded');else this.store.journal.recordOutcome(claimed.lease,'succeeded');this.store.result(row,result);this.store.attempt(row,claimed.status.attempts,'accepted');});await this.cleanup(this.store.row(accountId,row.action_id),true);
  }catch(error){const code:OutboxErrorCode=error instanceof OutboxError?error.code:dispatched?'outcome_unknown':'retryable';try{this.options.database.transaction(()=>{const status=this.store.journal.read(accountId,row.action_id);if(status.state==='cancelled')return;if(dispatched){const rejected=error instanceof SubmissionFailure&&error.knownRejected;if(status.state==='dispatching')this.store.journal.recordOutcome(claimed.lease,rejected?'rejected':'unknown');this.store.error(row,rejected?code:'outcome_unknown');this.store.attempt(row,claimed.status.attempts,rejected?'failed':'uncertain',code);}else{this.store.journal.failBeforeDispatch(claimed.lease,code==='retryable');this.store.error(row,code);this.store.attempt(row,claimed.status.attempts,'failed',code);}});}catch{/* A cancelled/recovered lease is never replayed here. */}
   if(code==='permission'&&this.store.account(accountId)==='graph'){const shared=new GraphMailboxRepository(this.options.database,this.options.ownerId);if(shared.read(accountId))shared.revoke(accountId);}
  }finally{connection?.close();}
 }
 async reconcile(accountId:string,actionId:string){if(this.controller.signal.aborted||this.closed)throw new OutboxError('retryable');const row=this.store.row(accountId,actionId),status=this.store.journal.read(accountId,actionId);if(status.state!=='uncertain')return this.store.item(accountId,actionId);const signal=AbortSignal.any([this.controller.signal,AbortSignal.timeout(30000)]);let connection:OutboxConnection|undefined;try{let result:OutboxResult|null;if(this.store.account(accountId)==='imap'&&!this.options.connection){this.store.assert(row);const imap=new ImapCustody(this.options.database,this.options.ownerId).read(accountId);const saved=await smtpSentCopy({settings:imap.settings,password:imap.password,raw:row.api_mime_bytes,messageId:row.message_id,from:this.store.envelope(row).from,signal,append:false,fence:()=>this.store.assert(row)});result=saved==='saved'?{accepted:[],rejected:[],providerId:null,sentCopy:'saved',delivery:'unknown',reconciled:true}:null;}else{connection=await this.connection(row,signal);result=await connection.reconcile(row);}if(result)this.options.database.transaction(()=>{const current=this.store.journal.read(accountId,actionId);if(current.state!=='uncertain')return;this.store.journal.reconcile(accountId,actionId,current.version,'succeeded');this.store.result(row,result);});}finally{connection?.close();}if(this.store.journal.read(accountId,actionId).state==='succeeded')await this.cleanup(this.store.row(accountId,actionId),false);return this.store.item(accountId,actionId);}
 private async cleanup(row:OutboxRow,append:boolean){if(this.store.restored(row.account_id,row.action_id)||!row.result_json)return;let result=outboxResultSchema.parse(JSON.parse(row.result_json));if(result.sentCopy==='pending'&&this.store.account(row.account_id)==='imap'){try{this.store.assert(row);const credential=new ImapCustody(this.options.database,this.options.ownerId).read(row.account_id);const saved=await smtpSentCopy({settings:credential.settings,password:credential.password,raw:row.api_mime_bytes,messageId:row.message_id,from:this.store.envelope(row).from,signal:this.controller.signal,append,fence:()=>this.store.assert(row)});result={...result,sentCopy:saved};this.store.result(row,result);}catch{this.store.result(row,{...result,sentCopy:'unavailable'});}}
  if(result.rejected.length||result.sentCopy==='unavailable'||result.reconciled&&this.store.account(row.account_id)==='imap')return;
  try{const drafts=new DraftSyncStore(this.options.database,this.options.ownerId);if(drafts.cleanupAfterSend(row.account_id,row.action_id))return;if(drafts.row(row.account_id,row.draft_id))return;const draft=this.store.local.readDraft(row.account_id,{draftId:row.draft_id});if(draft.version.generation===row.draft_generation&&draft.version.revision===row.draft_revision)this.store.local.deleteDraft(row.account_id,{draftId:row.draft_id,expected:draft.version});}catch{/* Keep newer, disconnected or remotely unsettled drafts recoverable. */}
 }
}
