import assert from 'node:assert/strict';
import {createServer as createTlsServer,createSecureContext,TLSSocket} from 'node:tls';
import {createServer as createNetServer} from 'node:net';
import {execFileSync} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
export async function smtpServerFixture({starttls=false,noTls=false,lostAck=false},body){const dir=await mkdtemp(join(tmpdir(),'smtp-synthetic-'));execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',join(dir,'key.pem'),'-out',join(dir,'cert.pem'),'-days','1','-subj','/CN=localhost','-addext','subjectAltName=DNS:localhost,IP:127.0.0.1'],{stdio:'ignore'});const key=await readFile(join(dir,'key.pem')),cert=await readFile(join(dir,'cert.pem')),context=createSecureContext({key,cert}),sockets=new Set(),commands=[];let messages=0;
 function attach(socket,secure,greet=true){sockets.add(socket);socket.on('error',()=>{});socket.on('close',()=>sockets.delete(socket));if(greet)socket.write('220 synthetic.example ESMTP\r\n');let pending='',data=false;const receive=chunk=>{pending+=chunk.toString();while(pending.includes('\r\n')){const at=pending.indexOf('\r\n'),line=pending.slice(0,at);pending=pending.slice(at+2);if(data){if(line!=='.')continue;data=false;messages++;if(lostAck){socket.destroy();return;}socket.write('250 2.0.0 synthetic accepted\r\n');continue;}const verb=line.split(' ')[0];commands.push(verb);if(verb==='EHLO')socket.write('250-synthetic.example\r\n'+(!secure&&!noTls?'250-STARTTLS\r\n':'')+(secure?'250-AUTH PLAIN\r\n':'')+'250 DSN\r\n');else if(verb==='STARTTLS'&&!noTls){socket.write('220 Ready for TLS\r\n');socket.removeListener('data',receive);const upgraded=new TLSSocket(socket,{isServer:true,secureContext:context});attach(upgraded,true,false);return;}else if(verb==='AUTH'){assert.equal(secure,true);socket.write('235 2.7.0 authenticated\r\n');}else if(verb==='MAIL')socket.write('250 2.1.0 sender ok\r\n');else if(verb==='RCPT')socket.write(line.includes('rejected@example.com')?'550 5.1.1 rejected\r\n':'250 2.1.5 accepted\r\n');else if(verb==='DATA'){data=true;socket.write('354 Send data\r\n');}else if(verb==='QUIT'){socket.end('221 bye\r\n');}else socket.write('500 unsupported\r\n');}};socket.on('data',receive);}
 const server=starttls?createNetServer(socket=>attach(socket,false)):createTlsServer({key,cert},socket=>attach(socket,true));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;
 try{await body({port,cert,commands,get messages(){return messages;}});}finally{for(const socket of sockets)socket.destroy();await new Promise(resolve=>server.close(resolve));await rm(dir,{recursive:true,force:true});}}
